const {test,expect}=require('@playwright/test');
const path=require('node:path');
async function fixture(page,status='accepted',realRouter=false,processing=true){
 await page.setContent('<button id="origin">Gestionar</button><div id="view-dashboard" style="height:180px;overflow:auto"><div style="height:900px">Listado</div></div>');
 await page.addStyleTag({path:path.resolve('assets/app.css')});
 await page.evaluate(status=>{
  const o={id:'op',record_id:'record',pipeline_id:'pipe',stage_id:'pending',updated_at:'version',client_name:'Ana Ejemplo',phone:'600000000',contract_party:{holder_name:'Ana Ejemplo',holder_dni:'12345678Z',contact_dni:'12345678Z',recipient_name:'Ana',recipient_phone:'600000000'},after_sale_preferences:{previous_operator:'Orange'}};
  const x={id:'offer',opportunity_id:'op',contact_id:'record',status,updated_at:'offer-version',snapshot:{recipient_phone:'600000000'},message_text:'Oferta enviada original',operator:'Vodafone',offer_name:'Fibra y móvil',total_price:35,accepted_at:'2026-09-10T10:00:00Z'};
  window.__fixture={o,x,conflict:false,writes:0,queries:[]};
  window.sb={from(table){const q={async like(){return{data:[]}},select(){return q},eq(k,v){window.__fixture.queries.push([table,k,v]);return q},update(p){window.__fixture.writes++;q.payload=p;return q},single(){return Promise.resolve(q.payload?(window.__fixture.conflict?{error:{code:'PGRST116'}}:{data:Object.assign(table==='crm_offer_instances'?x:o,q.payload,{updated_at:'saved-version'})}):{data:table==='crm_offer_instances'?x:o})},maybeSingle(){return Promise.resolve({data:{data:{APODO:'Anita'}}})},then(resolve){resolve({data:[{id:'processed',name:'Tramitado',pipeline_id:'pipe'}]})}};return q}};
  window.TPFOfferFollowup={state:{offers:[x]},summary(){return{label:'Sin envíos pendientes',age:'Enviada hace 19 días',next:'Sin recordatorio pendiente'}},htmlOffer(){return '<p>Seguimiento registrado</p>'},async load(){return this.state}};
  window.TPFControlWhatsappOffer=async()=>true;
  window.TPFRouterReturn={async preview(){return{available:true}},bind(root,data,opts){window.__fixture.send=opts.preferences.send;root.innerHTML='<label>Compañía anterior<select data-previous><option>Orange</option></select></label><label>Mensaje<textarea data-text>Hola Ana, avísanos cuando te instalen la fibra.</textarea></label><label><input type="checkbox" checked>Enviar al cliente</label>';return{get(){return{send:true,text:root.querySelector('textarea').value,previous_operator:'Orange'}},async saveTemplate(){}}}};
  window.sb.rpc=async(name,args)=>{window.__fixture.rpc={name,args};return{data:{available:true,text:'Hola Ana 👋\n\nCuando te instalen la fibra, avísanos.',recipient:'Ana',phone:'600000000',operator:'Vodafone'}}};
  window.openContact=()=>{};window.openOpportunityFull=()=>{};
  document.addEventListener('click',e=>{if(e.target.closest('[data-of-close]'))e.target.closest('dialog').close()});
 },status);
 await page.addScriptTag({path:path.resolve('js/modules/offer-work-plan.js')});
 if(realRouter)await page.addScriptTag({path:path.resolve('js/modules/router-return.js')});
 await page.addScriptTag({path:path.resolve('js/modules/home-manage-panel.js')});
 await page.locator('#origin').focus();await page.evaluate(()=>{document.getElementById('view-dashboard').scrollTop=300;window.TPFHomeManage.open('offer')});
 await expect(page.locator('#ofManageDialog')).toBeVisible();if(status==='accepted'&&processing){await page.getByRole('button',{name:'Preparar tramitación',exact:true}).click();await expect(page.locator('[data-confirm-processing]')).toBeEnabled({timeout:5000});}
}
test('Gestionar shows identity, saved offer and checked send; closes preserving list',async({page})=>{
 await page.setViewportSize({width:1280,height:800});await fixture(page,'accepted',false,false);
 await expect(page.locator('.ofClientIdentity')).toContainText('Ana Ejemplo');await expect(page.locator('.ofClientIdentity')).toContainText('12345678Z');await expect(page.locator('.ofClientIdentity')).toContainText('600000000');await expect(page.locator('.ofClientIdentity')).toContainText('Orange');await expect(page.locator('[data-of-view]')).toHaveText('Ver oferta');
 await expect(page.locator('[data-processing]')).toBeHidden();await page.getByRole('button',{name:'Preparar tramitación',exact:true}).click();expect(await page.evaluate(()=>window.__fixture.send)).toBe(true);await page.getByRole('button',{name:'Volver a la gestión'}).click();
 const box=await page.locator('#ofManageDialog').boundingBox();expect(box.x+box.width).toBeCloseTo(1280,0);expect(box.height).toBeCloseTo(800,0);
 await page.getByRole('button',{name:'Volver al listado'}).click();await expect(page.locator('dialog')).toHaveCount(0);expect(await page.locator('#view-dashboard').evaluate(el=>el.scrollTop)).toBe(300);await expect(page.locator('#origin')).toBeFocused();
});
test('conflict keeps reviewed message open and does not show false success',async({page})=>{
 await fixture(page);await page.evaluate(()=>window.__fixture.conflict=true);await page.locator('[data-text]').fill('Texto revisado');await page.locator('[data-confirm-processing]').click();await expect(page.locator('[data-process-error]')).toContainText('otro dispositivo');await expect(page.locator('[data-text]')).toHaveValue('Texto revisado');await expect(page.locator('dialog')).toBeVisible();
});
test('Gestionar opens conversation, WhatsApp and task actions after closing the drawer',async({page})=>{
 await fixture(page,'following');await page.getByRole('button',{name:'Volver al listado'}).click();await page.addScriptTag({path:path.resolve('js/modules/offer-followup-ui.js')});await page.evaluate(()=>{TPFOfferFollowup.state.offers=[__fixture.x];TPFOfferFollowup.state.byOpportunity=new Map([['op',[__fixture.x]]]);TPFOfferFollowup.load=async()=>TPFOfferFollowup.state;window.quickOpened=[];TPFOfferFollowup.quickAction=(kind,id,o)=>quickOpened.push({kind,id,opportunityId:o.id,drawerClosed:!document.getElementById('ofManageDialog')?.open});});
 for(const kind of ['conversation','message','task']){await page.evaluate(()=>TPFHomeManage.open('offer'));await page.locator('[data-of-quick="'+kind+'"]').click();await expect(page.locator('#ofManageDialog')).toHaveCount(0);}
 const results=await page.evaluate(()=>quickOpened);expect(results.map(r=>r.kind)).toEqual(['conversation','message','task']);expect(results.every(r=>r.id==='op'&&r.opportunityId==='op'&&r.drawerClosed)).toBe(true);expect(await page.evaluate(()=>__fixture.writes)).toBe(0);
});
test('acceptance prepares tramitation without losing controls or leaving confirm disabled',async({page})=>{
 await fixture(page,'following');
 await page.getByRole('button',{name:'Marcar aceptada y preparar tramitación'}).click();await expect(page.locator('[data-confirm-processing]')).toBeEnabled();await page.locator('[data-confirm-processing]').click();await expect(page.locator('dialog')).toHaveCount(0);expect(await page.evaluate(()=>window.__fixture.writes)).toBe(1);
});
test('mobile drawer fits the viewport',async({page})=>{
 await page.setViewportSize({width:390,height:844});await fixture(page);const box=await page.locator('dialog').boundingBox();expect(box.width).toBeLessThanOrEqual(390);expect(await page.locator('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
});

test('real router controls validate the previous operator and preserve the edited message',async({page})=>{
 await fixture(page,'accepted',true);await expect(page.locator('[data-send]')).toBeChecked();await expect(page.locator('[data-previous]')).toHaveValue('Orange');await page.locator('[data-text]').fill('Hola Ana. Texto revisado para tu instalación.');await page.locator('[data-confirm-processing]').click();await expect(page.locator('dialog')).toHaveCount(0);expect(await page.evaluate(()=>window.__fixture.writes)).toBe(1);
});
test('pausing opens the existing reason and Agenda review form',async({page})=>{
 await fixture(page,'following');await page.getByRole('button',{name:'Pausar seguimiento',exact:true}).click();await expect(page.locator('.ofPlanForm')).toBeVisible();await expect(page.locator('[name=reason]')).toBeVisible();await page.locator('[name=reason]').fill('Cliente pendiente de decidir');await page.getByRole('button',{name:'Guardar pausa',exact:true}).click();await expect(page.locator('dialog')).toHaveCount(0);expect(await page.evaluate(()=>window.__fixture.rpc.name)).toBe('crm_save_offer_work_plan');expect(await page.evaluate(()=>window.__fixture.rpc.args.p_pause)).toBe(true);
});

test('editing the previous company preserves the sent offer and supports clearing and reopen',async({page})=>{
 await fixture(page,'following');await page.getByRole('button',{name:'Editar compañía anterior'}).click();await page.locator('#ofPreviousInput').fill('Lowi');await page.getByRole('button',{name:'Guardar compañía',exact:true}).click();await expect(page.locator('[data-previous-label]')).toHaveText('Lowi');await expect(page.locator('[data-previous-status]')).toHaveText('Compañía guardada');
 expect(await page.evaluate(()=>window.__fixture.x.message_text)).toBe('Oferta enviada original');expect(await page.evaluate(()=>window.__fixture.o.after_sale_preferences.previous_operator)).toBe('Orange');
 await page.getByRole('button',{name:'Volver al listado'}).click();await expect(page.locator('dialog')).toHaveCount(0);await page.evaluate(()=>window.TPFHomeManage.open('offer'));await expect(page.locator('[data-previous-label]')).toHaveText('Lowi');await page.getByRole('button',{name:'Editar compañía anterior'}).click();await page.locator('#ofPreviousInput').fill('');await page.getByRole('button',{name:'Guardar compañía',exact:true}).click();await expect(page.locator('[data-previous-label]')).toHaveText('Sin indicar');
 await page.getByRole('button',{name:'Pausar seguimiento',exact:true}).click();await page.locator('[name=reason]').fill('Revisar después');await page.getByRole('button',{name:'Guardar pausa',exact:true}).click();expect(await page.evaluate(()=>window.__fixture.rpc.args.p_expected_at)).toBe('saved-version');
});
test('a conflict keeps the previous company draft and allows cancel without writing',async({page})=>{
 await fixture(page,'following');await page.getByRole('button',{name:'Editar compañía anterior'}).click();await page.locator('#ofPreviousInput').fill('Digi');await page.evaluate(()=>window.__fixture.conflict=true);await page.getByRole('button',{name:'Guardar compañía',exact:true}).click();await expect(page.locator('[data-previous-error]')).toContainText('otro dispositivo');await expect(page.locator('#ofPreviousInput')).toHaveValue('Digi');await expect(page.locator('[data-previous-label]')).toHaveText('Orange');const writes=await page.evaluate(()=>window.__fixture.writes);await page.getByRole('button',{name:'Cancelar',exact:true}).click();expect(await page.evaluate(()=>window.__fixture.writes)).toBe(writes);
});
test('recipient is checked on opening and an empty recipient never borrows the client phone',async({page})=>{
 await fixture(page,'following');await expect(page.locator('section [data-recipient]')).toContainText('Ana · 600000000');await page.getByRole('button',{name:'Volver al listado'}).click();await expect(page.locator('dialog')).toHaveCount(0);await page.evaluate(()=>{window.sb.rpc=async()=>({data:{recipient:'Titular sin teléfono',phone:''}});window.TPFHomeManage.open('offer')});await expect(page.locator('section [data-recipient]')).toContainText('sin destinatario con teléfono válido');await expect(page.locator('section [data-recipient]')).not.toContainText('600000000');
});
test('short desktop and mobile panels scroll inside the body without footer overlap',async({page})=>{
 for(const viewport of [{width:1280,height:650},{width:390,height:650}]){await page.setViewportSize(viewport);await fixture(page,'following');await page.locator('.ofDrawerBody').evaluate(el=>el.scrollTop=el.scrollHeight);const body=await page.locator('.ofDrawerBody').boundingBox(),footer=await page.locator('.ofDrawerFoot').boundingBox();expect(body.y+body.height).toBeLessThanOrEqual(footer.y+1);await page.getByRole('button',{name:'Finalizar seguimiento',exact:true}).scrollIntoViewIfNeeded();const action=await page.getByRole('button',{name:'Finalizar seguimiento',exact:true}).boundingBox();expect(action.y+action.height).toBeLessThanOrEqual(footer.y+1);await page.getByRole('button',{name:'Volver al listado'}).click();}
});

test('copy buttons confirm the copied DNI and phone',async({page})=>{
 await fixture(page,'following');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async value=>window.__copied=value},configurable:true}));await page.getByRole('button',{name:'Copiar DNI / NIF',exact:true}).click();expect(await page.evaluate(()=>window.__copied)).toBe('12345678Z');await expect(page.getByRole('button',{name:'Copiar DNI / NIF',exact:true})).toHaveText('Copiado');await page.getByRole('button',{name:'Copiar Teléfono',exact:true}).click();expect(await page.evaluate(()=>window.__copied)).toBe('600000000');
});
test('recipient lookup failure is visible and keeps the registered details qualified',async({page})=>{
 await fixture(page,'following');await page.getByRole('button',{name:'Volver al listado'}).click();await expect(page.locator('dialog')).toHaveCount(0);await page.evaluate(()=>{window.sb.rpc=async()=>({error:{message:'Unavailable'}});window.TPFHomeManage.open('offer')});await expect(page.locator('section [data-recipient]')).toContainText('No se pudo comprobar');await expect(page.locator('section [data-recipient]')).toContainText('Registrado: Ana · 600000000');
});

test('previous company edits refresh the processing draft while leaving saved messages intact',async({page})=>{
 await fixture(page,'accepted',true);await page.getByRole('button',{name:'Volver a la gestión'}).click();const sent=await page.evaluate(()=>window.__fixture.x.message_text);await page.getByRole('button',{name:'Editar compañía anterior'}).click();await page.locator('#ofPreviousInput').fill('Lowi');await page.getByRole('button',{name:'Guardar compañía',exact:true}).click();await expect(page.locator('[data-previous]')).toHaveValue('Lowi');await expect(page.locator('[data-text]')).toHaveValue(/Lowi/);expect(await page.evaluate(()=>window.__fixture.x.message_text)).toBe(sent);expect(await page.evaluate(()=>window.__fixture.o.after_sale_preferences.previous_operator)).toBe('Orange');await page.getByRole('button',{name:'Volver al listado'}).click();await expect(page.locator('dialog')).toHaveCount(0);await page.evaluate(()=>window.TPFHomeManage.open('offer'));await page.getByRole('button',{name:'Preparar tramitación',exact:true}).click();await expect(page.locator('[data-previous]')).toHaveValue('Lowi');
});

test('State control stays visible, checks both versions and keeps a conflict draft',async({page})=>{
 await fixture(page,'following');await page.getByRole('button',{name:'Cambiar estado',exact:true}).click();await page.locator('[data-new-state]').selectOption('perdido');await page.evaluate(()=>{sb.rpc=async(name,args)=>{__fixture.rpc={name,args};return{error:{message:'La oferta cambió en otro dispositivo'}}};});await page.getByRole('button',{name:'Continuar',exact:true}).click();await expect(page.locator('[data-state-error]')).toContainText('otro dispositivo');await expect(page.locator('[data-new-state]')).toHaveValue('perdido');const call=await page.evaluate(()=>__fixture.rpc);expect(call.name).toBe('crm_change_offer_stage');expect(call.args.p_expected_offer_at).toBe('offer-version');expect(call.args.p_expected_opportunity_at).toBe('version');expect(call.args.p_stage).toBe('perdido');expect(call.args.p_preferences).toBeNull();
});
test('Choosing Tramitado opens one review step with a fixed primary action and preserves the draft on back',async({page})=>{
 await fixture(page,'accepted',true,false);await page.getByRole('button',{name:'Cambiar estado',exact:true}).click();await page.locator('[data-new-state]').selectOption('tramitado');await page.getByRole('button',{name:'Continuar',exact:true}).click();await expect(page.locator('[data-processing]')).toBeVisible();await expect(page.locator('.ofClientIdentity')).toBeHidden();await expect(page.locator('.ofDrawerFoot [data-confirm-processing]')).toBeEnabled();await page.locator('[data-text]').fill('Aviso revisado una sola vez');await page.getByRole('button',{name:'Volver a la gestión'}).click();await expect(page.getByRole('button',{name:'Cambiar estado',exact:true})).toBeVisible();await page.getByRole('button',{name:'Preparar tramitación',exact:true}).click();await expect(page.locator('[data-text]')).toHaveValue('Aviso revisado una sola vez');
});

test('Gestionar and the appointment review show the real compact installation interface',async({page})=>{
 for(const viewport of [{width:1280,height:800},{width:390,height:844}]){
 await page.setViewportSize(viewport);await fixture(page,'accepted',true,false);await page.addStyleTag({path:path.resolve('assets/crm-reference.css')});await page.evaluate(()=>{document.body.classList.add('tpfUnified');sb.rpc=async()=>({data:{workflow:'installation_v1',available:true,operator:'Vodafone',recipient:'Ana Ejemplo',phone:'600000000',installation_config:{slots:[{from:'10:00',to:'12:00'}],appointment_text:'Hola {nombre} 👋\n\nTu instalación de {operador} está prevista para el {fecha}, {franja}. Estate pendiente del teléfono: el técnico podría llamarte para confirmar o adelantar la visita.\n\nSi tienes algún problema, {ayuda}.',no_appointment_text:'Hola {nombre} 👋\n\nHemos tramitado tu contrato con {operador}. Estamos pendientes de que el operador confirme la cita. Estate pendiente del teléfono por si el técnico te llama para concertar o adelantar la visita.\n\nSi tienes algún problema, {ayuda}.'}}});});await page.addScriptTag({path:path.resolve('js/modules/installation-communications.js')});await expect(page.getByRole('button',{name:'Cambiar estado',exact:true})).toBeVisible();if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/manage-'+viewport.width+'.png'});await page.getByRole('button',{name:'Preparar tramitación',exact:true}).click();await expect(page.locator('[data-appointment-fields]')).toBeHidden();await expect(page.locator('[data-notice-preview]')).toContainText('Estate pendiente');await page.locator('[data-appointment-mode=scheduled]').click();await page.locator('[data-date]').fill('2026-10-08');await page.locator('[data-slot]').selectOption('0');await expect(page.locator('[data-notice-preview]')).toContainText('08/10/2026');const footer=await page.locator('.ofDrawerFoot').boundingBox(),confirm=await page.locator('[data-confirm-processing]').boundingBox();expect(confirm.y+confirm.height).toBeLessThanOrEqual(footer.y+footer.height);expect(await page.locator('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/processing-'+viewport.width+'.png'});await page.getByRole('button',{name:'Volver a la gestión'}).click();await page.getByRole('button',{name:'Volver al listado'}).click();
 }
});
