const {test,expect}=require('@playwright/test');
test.setTimeout(240000);test.use({viewport:{width:1440,height:950},actionTimeout:15000,screenshot:'off',trace:'off',video:'off'});
async function shot(page,name){const root=page.locator('#view-whatsapplive');await root.screenshot({path:test.info().outputPath(name+'.png'),mask:[root.locator('#waLiveChats,#waMessages,.waFieldValue,.waFieldPeek,.waFieldEditor input,.waFieldEditor textarea,#waSideName,#waSideNickname,#waSideAvatar,#waSideIdentity,#waChatName,#waChatNickname,#waChatPhone,#waChatAvatar,#waCleanRelationRows,#waCleanOfferRows,#tpfWaAliasCard p,#waSideTags,#waSideNotes,#waInternalNote,#waActivityTimeline'.split(',').map(s=>s+':visible').join(','))],maskColor:'#dce5ef'});}
async function fits(page,selector){const box=await page.locator(selector).boundingBox();expect(box).toBeTruthy();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.y).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(page.viewportSize().width+1);expect(box.y+box.height).toBeLessThanOrEqual(page.viewportSize().height+1);}
test('WhatsApp sidebar, native actions and composer fit normal and fullscreen',async({page,request})=>{
const net=[];page.on('response',r=>{if(/bootstrap_user_permissions|current_user_permissions/.test(r.url()))net.push({path:new URL(r.url()).pathname,status:r.status()});});page.on('pageerror',e=>console.log('PAGE_ERROR',e.message.slice(0,250)));
const h=await(await request.get('/api/health')).json();expect(h.commit).toBe(process.env.E2E_EXPECTED_COMMIT);expect(h.environment).toBe('preview');
await page.goto('/');await page.locator('#email').fill(process.env.CRM_TEST_EMAIL);await page.locator('#password').fill(process.env.CRM_TEST_PASSWORD);await page.locator('#signin').click();try{await expect(page.locator('#app')).toBeVisible({timeout:30000});}catch(e){console.log('LOGIN_DIAGNOSTIC',JSON.stringify(net));throw e;}
await page.locator('.nav[data-view="whatsapplive"]').click();await expect(page.locator('#waLiveChats .waChatRow').first()).toBeVisible({timeout:40000});
let found=false;for(let i=0;i<Math.min(15,await page.locator('#waLiveChats .waChatRow').count());i++){await page.locator('#waLiveChats .waChatRow').nth(i).click();try{await expect(page.locator('#waSideNewOffer')).toBeVisible({timeout:8000});found=true;break;}catch(_){}}expect(found).toBeTruthy();
await expect(page.locator('#waCleanReview')).toBeVisible();await expect(page.locator('#waCleanRelations')).toBeVisible();await page.locator('#waCleanRelations summary').click();await expect(page.locator('#waCleanRelationRows')).not.toHaveText(/Cargando/,{timeout:15000});await page.locator('#waCleanRelations summary').click();
await page.locator('#waCleanOffers summary').click();await expect(page.locator('#waCleanOfferRows')).not.toHaveText(/Cargando/,{timeout:15000});await page.locator('#waCleanOffers summary').click();
await expect(page.locator('#waSideEditContact')).toBeHidden();
await expect(page.locator('#waSideOpenContact')).toBeHidden();
for(const [field,section] of [['contactName',null],['contactNickname',null],['contactPhone',null],['contactDni',null],['contactEmail','#waFieldMore'],['contactBank','#waFieldMore'],['contactObservations','#waField-contactObservations'],['contactNotes','#waField-contactNotes']]){
 if(section&&!(await page.locator(section).getAttribute('open')!==null))await page.locator(section+' > summary').click();
 await page.locator('[data-wa-edit="'+field+'"]').click();await expect(page.locator('.waFieldEditor')).toBeVisible();
 if(field==='contactObservations'){await page.locator('.waFieldEditor textarea').fill('Prueba visual sin guardar');await shot(page,'wa-inline-edit');}
 await page.locator('[data-wa-field-cancel]').click();await expect(page.locator('.waFieldEditor')).toHaveCount(0);
}
for(const s of ['#waFieldMore','#waField-contactObservations','#waField-contactNotes'])if(await page.locator(s).getAttribute('open')!==null)await page.locator(s+' > summary').click();
await page.locator('#waContactPanel').evaluate(el=>el.scrollTop=0);
await expect(page.locator('[data-wa-tab="archived"]')).toBeVisible();
await page.locator('.waCleanFilters summary').click();await expect(page.locator('.waCleanFilters [popover]')).toBeVisible();await shot(page,'wa-filters');await fits(page,'.waCleanFilters [popover]');await page.locator('.waCleanFilters [popover]').screenshot({path:test.info().outputPath('wa-filter-options.png')});await page.locator('[data-wa-tab="groups"]').click();await expect(page.locator('[data-wa-tab="groups"]')).toHaveClass(/active/);await page.locator('[data-wa-tab="all"]').click();
await page.locator('#waScheduleBtn').click();await expect(page.locator('#tpfSched3')).toBeVisible();
for(const height of [950,700]){await page.setViewportSize({width:1440,height});await fits(page,'#tpfS3save');await page.locator('.tpfS3b').evaluate(el=>el.scrollTop=el.scrollHeight);await fits(page,'#tpfS3save');}
await page.locator('#tpfSched3').screenshot({path:test.info().outputPath('wa-schedule.png'),mask:[page.locator('#tpfS3phone,#tpfS3msg,#tpfS3contact')],maskColor:'#dce5ef'});
await page.locator('#tpfSched3 [data-close]').last().click();await page.setViewportSize({width:1440,height:950});

for(const width of [1440,1100]){await page.setViewportSize({width,height:950});await page.waitForTimeout(300);await fits(page,'#waComposerText');await fits(page,'#waComposerSend');await fits(page,'#waCleanReview');await page.locator('.waChatTopActions .waCleanMore summary').click();await fits(page,'#waMediaChat');await page.locator('#waMediaChat').click();await expect(page.locator('#waMediaModal')).toBeVisible();await page.locator('#waMediaClose').click();await shot(page,'wa-normal-'+width);const before=await page.locator('.waChatPane').boundingBox();await page.locator('#waClientToggle').click();await expect(page.locator('.waContactPane')).toBeHidden();const after=await page.locator('.waChatPane').boundingBox();expect(after.width).toBeGreaterThan(before.width+200);await fits(page,'#waComposerSend');await shot(page,'wa-chat-'+width);await page.locator('#waClientToggle').click();}
await page.setViewportSize({width:1440,height:950});await page.locator('#waCleanExpand').click();await expect(page.locator('#view-whatsapplive')).toHaveClass(/waCleanFullscreen/);await expect(page.locator('.referenceSidebar')).toBeHidden();await fits(page,'#waComposerSend');await shot(page,'wa-fullscreen');
await page.locator('#waSideNewOffer').click();await expect(page.locator('#opOfferModal')).toBeVisible();await page.locator('#opOfferClose').click();await expect(page.locator('#contactModal')).toBeHidden();
await page.locator('#waSideDirectSale').click();await expect(page.locator('#directSaleModal')).toBeVisible();await page.locator('#directSaleModal [data-direct-close]').first().click();
await page.locator('#waCleanReview').click();await expect(page.locator('.tpfReviewBack')).toBeVisible();await page.locator('.tpfReviewBack').getByRole('button',{name:'Cancelar',exact:true}).click();await expect(page.locator('.tpfReviewBack')).toBeHidden();
await page.locator('#waSideNewTask').click();await expect(page.locator('#agendaCreateCard')).toBeVisible();await page.locator('#agendaCloseCreate').click();
await page.locator('#waSideNewOpp').click();await expect(page.locator('#oppDetailModal')).toBeVisible();await page.locator('#oppModalClose').click();await expect(page.locator('#contactModal')).toBeHidden();
await page.locator('#waCleanExpand').click();await expect(page.locator('#view-whatsapplive')).not.toHaveClass(/waCleanFullscreen/);
await page.locator('.waCleanFilters summary').click();await expect(page.locator('[data-wa-tab="groups"]')).toBeVisible();await fits(page,'[data-wa-tab="archived"]');await page.locator('[data-wa-tab="all"]').click();
await page.locator('.waChatTopActions .waCleanMore summary').click();await expect(page.locator('#waMediaChat')).toBeVisible();await page.locator('#waMediaChat').click();await expect(page.locator('#waMediaModal')).toBeVisible();
});
