const {test,expect}=require('@playwright/test'),path=require('node:path');
test('Sales floating menu closes across stopped clicks, view changes, Escape and scroll',async({page})=>{
 await page.route('**/*',r=>r.abort());await page.setContent('<div id="view-sales"><button class="tpfListMenuBtn">Acciones</button></div><button id="nav-home">Inicio</button>');await page.evaluate(()=>{window.TPFModules={register(){}};window.salesCache={opportunities:[{id:'op',phone:'600000001'}]};document.getElementById('nav-home').onclick=e=>e.stopPropagation()});
 const fs=require('node:fs'),source=fs.readFileSync(path.resolve('js/modules/sales-list-ui.js'),'utf8').replace("M.register('sales-list-ui'","window.salesMenuFixture={installMenuLifecycle,menu};M.register('sales-list-ui'");await page.addScriptTag({content:source});await page.evaluate(()=>{salesMenuFixture.installMenuLifecycle();document.querySelector('.tpfListMenuBtn').onclick=e=>salesMenuFixture.menu(e,'op')});
 const open=async()=>{await page.locator('.tpfListMenuBtn').click();await expect(page.locator('.tpfListMenu')).toBeVisible()};await open();await page.locator('#nav-home').click();await expect(page.locator('.tpfListMenu')).toHaveCount(0);await open();await page.keyboard.press('Escape');await expect(page.locator('.tpfListMenu')).toHaveCount(0);await open();await page.evaluate(()=>document.getElementById('view-sales').classList.add('hidden'));await expect(page.locator('.tpfListMenu')).toHaveCount(0);await page.evaluate(()=>document.getElementById('view-sales').classList.remove('hidden'));await open();await page.evaluate(()=>document.dispatchEvent(new Event('scroll')));await expect(page.locator('.tpfListMenu')).toHaveCount(0);
});
test('Labels keep typing and an open draft when asynchronous data refresh finishes',async({page})=>{
 await page.route('**/*',r=>r.abort());await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><div id="view-labels"></div>');
 await page.evaluate(()=>{
  window.TPFModules={register(_name,module){module.install()}};window.labelsReads=0;
  window.sb={
   rpc(){return new Promise(resolve=>window.finishLabels=()=>resolve({data:[{id:1,name:'Vodafone'}]}))},
   from(){return{select(){return this},eq(){return this},async maybeSingle(){return{data:{value:{}}}},then(resolve){labelsReads++;return Promise.resolve({data:[{label_id:1}]}).then(resolve)}};}
  };
 });
 const source=require('node:fs').readFileSync(path.resolve('js/modules/labels-modern-ui.js'),'utf8').replace("M.register('labels-modern-ui'","window.labelsFixture={load};M.register('labels-modern-ui'");await page.addScriptTag({content:source});const input=page.locator('#lmSearch');await input.pressSequentially('zzzz rendimiento');
 await page.evaluate(()=>{window.searchBefore=document.getElementById('lmSearch');finishLabels();});
 await expect(page.locator('#view-labels')).not.toHaveAttribute('aria-busy','true');await expect(input).toBeFocused();await page.keyboard.type(' teclado');await expect(input).toHaveValue('zzzz rendimiento teclado');
 expect(await page.evaluate(()=>searchBefore===document.getElementById('lmSearch'))).toBe(true);await expect(page.locator('.lmFooter')).toContainText('0 etiquetas');await input.fill('Vodafone');await expect(page.locator('.lmFooter')).toContainText('1 etiqueta');
 await page.locator('#lmNew').click();await page.locator('#lmName').fill('Borrador sin guardar');await page.locator('#lmCategory').fill('Categoría nueva');
 await page.evaluate(()=>{void labelsFixture.load()});await expect(page.locator('#view-labels')).toHaveAttribute('aria-busy','true');await page.evaluate(()=>finishLabels());
 await expect(page.locator('#view-labels')).not.toHaveAttribute('aria-busy','true');await expect(page.locator('#lmModalBack')).toBeVisible();await expect(page.locator('#lmName')).toHaveValue('Borrador sin guardar');await expect(page.locator('#lmCategory')).toHaveValue('Categoría nueva');expect(await page.evaluate(()=>labelsReads)).toBe(2);
});
async function fixture(page){
 await page.route('**/*',r=>r.abort());await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><style>.hidden{display:none!important}body{margin:0;font:14px Arial;color:#24354b}button{cursor:pointer}</style><div id="app"><div id="view-dashboard" class="tpfDashPro"><div class="tdCommercialDetails"></div></div></div><div id="settings"></div><div id="editor"></div>');
 await page.clock.setFixedTime(new Date('2026-10-03T16:30:00Z'));
 await page.evaluate(()=>{
  const defaults={shop_phone:'',slots:[],return_time:'10:00',appointment_text:'Hola {nombre}. Instalación de {operador} el {fecha}, {franja}. Estate pendiente del teléfono. Si hay algún problema, {ayuda}. Pulsa Instalado.',no_appointment_text:'Hola {nombre}. Pendiente de cita de {operador}. Si hay algún problema, {ayuda}.',date_prompt_text:'¿Qué día te instalaron?',date_other_text:'Fecha DD/MM/AAAA',confirmed_text:'Instalación del {fecha_instalacion} registrada.'};
  window.fixture={defaults,operators:{Vodafone:{...defaults,operator:'Vodafone',updated_at:'first',slots:[{from:'10:00',to:'12:00'}]}},calls:[],fail:false,i:null};
  window.sb={auth:{onAuthStateChange(){}},from(){return{select(){return this},eq(){return this},async single(){return{data:window.salesCache?.opportunities?.[0]||{id:'op',stage_id:'pending'}}},async like(){return{data:[]}}}},rpc(name,args){fixture.calls.push({name,args});let result;
   if(name==='crm_installation_preview')result={data:{workflow:'installation_v1',available:true,operator:'Vodafone',recipient:'Gestora Ejemplo',recipient_first_name:'Gestora',phone:'600000001',opportunity_updated_at:'op-version',installation_config:fixture.operators.Vodafone,preferences:{previous_operator:'Yoigo'},installation:fixture.i}};
   else if(name==='crm_installation_settings')result={data:{defaults,operators:fixture.operators}};
   else if(name==='crm_operator_communication_templates')result={data:[{rule_id:'rule',rule_name:'3 meses · '+args.p_operator,template_id:1,template_name:'Seguridad',enabled:true,body:'Mensaje original 3 meses',schedule:'Regla existente'}]};
   else if(name==='crm_installation_save_settings'){if(fixture.fail)result={error:{message:'Conflicto en otro dispositivo'}};else{fixture.operators[args.p_operator]={...args.p_config,operator:args.p_operator,updated_at:'saved'};result={data:fixture.operators[args.p_operator]};}}
   else if(name==='crm_installation_update'||name==='crm_installation_adopt'||name==='crm_operator_communication_save')result=fixture.fail?{error:{message:'Cambió en otro dispositivo'}}:{data:{}};
   else if(name==='crm_installations_list')result={data:fixture.registry||[{opportunity_id:'op3',client_name:'Ana Ejemplo',operator:'Vodafone',price:35,appointment_date:'2026-10-08',time_from:'10:00',time_to:'12:00',status:'scheduled',offer_instance_id:'offer3',offer_sent:true},{opportunity_id:'op1',client_name:'Luis Ejemplo',operator:'O2',price:30,appointment_date:'2026-10-06',time_from:'09:00',time_to:'11:00',status:'scheduled'},{opportunity_id:'op2',client_name:'Sara Ejemplo',operator:'MásMóvil',status:'confirmed',installed_on:'2026-10-02',return_due_at:'2026-10-06T08:00:00Z'},{opportunity_id:'op4',client_name:'Elena Ejemplo',operator:'Orange',status:'excel',excel_date:'2026-09-20'}]};
   else throw Error('Unexpected RPC '+name);
   const promise=Promise.resolve(result);promise.range=()=>Promise.resolve(result);return promise;
  }};
 });
 for(const file of ['router-return','installation-communications','installation-settings','installation-registry','router-return-settings'])await page.addScriptTag({path:path.resolve('js/modules/'+file+'.js')});
}
test('Processing edits appointment, preserves client draft, copies recipient and separates return',async({page})=>{
 await fixture(page);await page.evaluate(async()=>{const data=await TPFRouterReturn.preview({id:'op'});window.controller=TPFRouterReturn.bind(document.getElementById('editor'),data,{preferences:{previous_operator:'Yoigo'}});});
 const root=page.locator('#editor');await expect(root).toContainText('Gestora Ejemplo');await expect(root.locator('[data-send]')).toBeChecked();await root.locator('[data-appointment-mode=scheduled]').click();await root.locator('[data-date]').fill('2026-10-08');await root.locator('[data-slot]').selectOption('0');await expect(root.locator('[data-text]')).toHaveValue(/08\/10\/2026.*10:00.*12:00/);
 await expect(root.locator('[data-text]')).not.toHaveValue(/router de Yoigo/);await expect(root.locator('[data-return-text]')).toHaveValue(/router de Yoigo/);
 await root.locator('[data-edit-notice]').click();await root.locator('[data-text]').fill('Aviso personalizado de Gestora');await root.locator('[data-date]').fill('2026-10-09');await root.locator('[data-from]').focus();await expect(root.locator('[data-text]')).toHaveValue('Aviso personalizado de Gestora');
 const p=await page.evaluate(()=>controller.get());expect(p.workflow).toBe('installation_v1');expect(p.appointment_date).toBe('2026-10-09');expect(p.send_at).toBeNull();expect(p.previous_operator).toBe('Yoigo');expect(p.text).toBe('Aviso personalizado de Gestora');
 await root.locator('[data-extra] summary').click();await root.locator('[data-previous]').selectOption('Ninguno');await expect(root.locator('[data-return-text]')).toBeDisabled();await expect(root).toContainText('Sin router anterior que devolver');
});
test('Unknown date is allowed; invalid ranges and dates are rejected without sends',async({page})=>{
 await fixture(page);await page.evaluate(async()=>{window.controller=TPFInstallations.bind(document.getElementById('editor'),await TPFInstallations.preview({id:'op'}),{});});
 expect((await page.evaluate(()=>controller.get())).appointment_date).toBeNull();await expect(page.locator('#editor [data-text]')).toHaveValue(/Pendiente de cita/);
 await page.locator('#editor [data-appointment-mode=scheduled]').click();await page.locator('#editor [data-from]').fill('12:00');expect(await page.evaluate(()=>{try{controller.get();return '';}catch(e){return e.message;}})).toContain('fecha y la hora');
 await page.locator('#editor [data-date]').fill('2026-10-05');await page.locator('#editor [data-to]').fill('09:00');expect(await page.evaluate(()=>{try{controller.get();return '';}catch(e){return e.message;}})).toContain('posterior');expect(await page.evaluate(()=>fixture.calls.some(x=>/update|adopt/.test(x.name)))).toBe(false);
 expect(await page.evaluate(()=>TPFInstallations.businessDays('2026-10-02'))).toBe('2026-10-06');expect(await page.evaluate(()=>TPFInstallations.businessDays('2026-10-03'))).toBe('2026-10-06');
});
test('Configuration groups all texts per operator, saves atomically and keeps conflicts visible',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFRouterSettings.mount(document.getElementById('settings')));const root=page.locator('#settings');await expect(root.locator('[data-title]')).toHaveText('Vodafone');await expect(root).toContainText('Devolución del router de este operador');
 await root.getByText('Teléfono de ayuda',{exact:true}).click();await root.locator('[data-shop-phone]').fill('958000000');await expect(root.locator('[data-preview]')).toContainText('958000000');await root.getByRole('tab',{name:'Devolución',exact:true}).click();await root.locator('[data-router-text]').fill('Instrucciones editadas de Vodafone');await root.locator('[data-save]').click();await expect(root.locator('[data-status]')).toContainText('guardada para todos');
 const c=await page.evaluate(()=>fixture.calls.find(x=>x.name==='crm_installation_save_settings'));expect(c.args.p_config.router_text).toBe('Instrucciones editadas de Vodafone');expect(c.args.p_expected_at).toBe('first');
 await root.locator('[data-operator="Yoigo"]').click();await root.getByRole('tab',{name:'Instalación',exact:true}).click();await root.locator('[data-appointment-text]').fill('Texto nuevo Yoigo');await page.evaluate(()=>fixture.fail=true);await root.locator('[data-save]').click();await expect(root.locator('[data-status]')).toContainText('otro dispositivo');await expect(root.locator('[data-appointment-text]')).toHaveValue('Texto nuevo Yoigo');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('Registry orders visits, filters client confirmation and exposes Excel separately',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFInstallationRegistry.open());const d=page.locator('#tpfInstallRegistryDialog');await expect(d.locator('tbody tr').first()).toContainText('Luis Ejemplo');await expect(d.locator('[data-count]')).toContainText('4 instalaciones');
 await d.locator('[data-filter="confirmed"]').click();await expect(d.locator('tbody tr')).toHaveCount(1);await expect(d.locator('tbody')).toContainText('Sara Ejemplo');await expect(d.locator('tbody')).toContainText('Devolución:');
 await d.locator('[data-filter="excel"]').click();await expect(d.locator('tbody')).toContainText('Elena Ejemplo');await expect(d.locator('tbody')).toContainText('20/09/2026 · Excel');await d.locator('footer [data-close]').click();await expect(d).toHaveCount(0);
});
test('Home installations exclude old undated sales and paginate beyond the first eight',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.registry=[...Array.from({length:31},(_,i)=>({opportunity_id:'new-'+i,client_name:'Cliente nuevo '+i,operator:'Vodafone',legacy:false,status:'undated',created_at:'2026-10-03T10:'+String(i).padStart(2,'0')+':00Z'})),{opportunity_id:'old',client_name:'Antigua sin fecha',operator:'Yoigo',legacy:true,status:'undated'},{opportunity_id:'excel',client_name:'Antigua Excel',operator:'Yoigo',legacy:true,status:'excel',excel_date:'2026-09-01'}];document.getElementById('tpfInstallHome')?.remove();});await page.evaluate(()=>window.dispatchEvent(new Event('tpf:dashboard-rendered')));const home=page.locator('#tpfInstallHome');await home.locator('summary').click();await expect(home.locator('summary')).toContainText('31 en seguimiento');await expect(home.locator('tbody tr')).toHaveCount(10);await expect(home).not.toContainText('Antigua sin fecha');await home.locator('[data-home-next]').click();await expect(home.locator('[data-home-page]')).toHaveText('11–20 de 31 instalaciones');await expect(home.locator('tbody tr').first()).toContainText('Cliente nuevo 10');await home.locator('[data-home-size]').selectOption('all');await expect(home.locator('tbody tr')).toHaveCount(31);await expect(home.locator('[data-home-next]')).toBeDisabled();
 await home.locator('[data-install-all]').click();const dialog=page.locator('#tpfInstallRegistryDialog');await expect(dialog.locator('[data-count]')).toContainText('32 instalaciones');await expect(dialog).not.toContainText('Antigua sin fecha');await dialog.locator('[data-filter="excel"]').click();await expect(dialog.locator('tbody')).toContainText('Antigua Excel');
});
test('Pending processing and processed sales have separate tabs and counters',async({page})=>{
 await fixture(page);await page.evaluate(()=>{window.TPFModules={register(){}};});const source=require('node:fs').readFileSync(path.resolve('js/modules/dashboard-performance-guard.js'),'utf8').replace("M.register('dashboard-performance-guard'","window.dashboardFixture={D,build,renderHomePanels,renderPulse};M.register('dashboard-performance-guard'");await page.addScriptTag({content:source});await page.evaluate(()=>{const t=dashboardFixture;t.build();const accepted={early:Date.parse('2026-09-01'),late:Date.parse('2026-09-20'),done:Date.parse('2026-08-01')};window.TPFOfferFollowup={acceptanceTime:id=>accepted[id],html:()=>'',state:{byOpportunity:new Map()}};t.D.data={today:'2026-10-03',stages:[{id:'p',name:'Pendiente de tramitar'},{id:'d',name:'Tramitado'}],opps:[{id:'late',client_name:'Pendiente reciente',stage_id:'p',expected_date:'2026-10-03'},{id:'done',client_name:'Venta antigua tramitada',stage_id:'d',expected_date:'2026-09-01'},{id:'early',client_name:'Pendiente antigua',stage_id:'p',expected_date:'2026-11-01'}],tasks:[],recordMap:new Map(),reminders:[]};t.renderHomePanels();t.renderPulse(t.D.data,new Map(t.D.data.stages.map(s=>[s.id,s])),[],[],[]);});await expect(page.locator('#tdPulseProcessing')).toHaveText('2');await expect(page.locator('#tdTabCountProcessed')).toHaveText('1');await page.locator('.tdWorkTab[data-home-filter="processing"]').click();await expect(page.locator('#dashAlerts tbody tr')).toHaveCount(2);await expect(page.locator('#dashAlerts tbody tr').first()).toContainText('Pendiente antigua');await expect(page.locator('#dashAlerts')).not.toContainText('Venta antigua tramitada');await page.locator('.tdWorkTab[data-home-filter="processed"]').click();await expect(page.locator('#dashAlerts tbody tr')).toHaveCount(1);await expect(page.locator('#dashAlerts')).toContainText('Venta antigua tramitada');await page.locator('.tdWorkTab[data-home-filter="priority"]').click();await expect(page.locator('#dashAlerts')).not.toContainText('Venta antigua tramitada');
});
test('Operator configuration closes nested installation dialogs and reaches its destination',async({page},info)=>{
 await fixture(page);await page.evaluate(mobile=>{if(mobile){const el=document.createElement('div');el.id='mobileView';document.body.appendChild(el);}else{const nav=document.createElement('button');nav.className='nav';nav.dataset.view='settings';nav.onclick=()=>{window.settingsReached=true;};document.body.appendChild(nav);const tab=document.createElement('button');tab.id='view-settings-router-texts-tab';tab.onclick=()=>{window.operatorTabReached=true;};document.body.appendChild(tab);}},info.project.name==='mobile');
 await page.evaluate(()=>TPFRouterSettings.mount(document.getElementById('settings')));await page.evaluate(()=>TPFInstallationRegistry.open());await page.locator('#tpfInstallRegistryDialog [data-install-manage]').first().click();const d=page.locator('#tpfInstallationDialog');await d.locator('[data-edit-appointment]').click();await d.locator('[data-extra] summary').click();await expect(d.locator('[data-config]')).toBeVisible();await d.locator('[data-config]').click();await expect(d).toHaveCount(0);await expect(page.locator('#tpfInstallRegistryDialog')).toHaveCount(0);await expect(page.locator('#settings [data-title]')).toHaveText('Vodafone');
 if(info.project.name==='mobile')expect(await page.evaluate(()=>location.hash)).toBe('#router-texts');else expect(await page.evaluate(()=>settingsReached&&operatorTabReached)).toBe(true);
});
test('Manage existing installation checks version, does not manually mark installed, preserves failure draft',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'version-i',appointment_date:'2026-10-08',time_from:'10:00',time_to:'12:00',previous_operator:'Yoigo',return_text:'Devolución guardada',notice_text:'Aviso guardado',incident:''};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await expect(d.locator('[data-save]')).toBeEnabled();await expect(d.locator('[data-send]')).not.toBeChecked();await d.locator('[data-incident]').fill('Técnico pendiente de llamar');await page.evaluate(()=>fixture.fail=true);await d.locator('[data-save]').click();await expect(d.locator('[data-status]')).toContainText('otro dispositivo');await expect(d.locator('[data-incident]')).toHaveValue('Técnico pendiente de llamar');
 const call=await page.evaluate(()=>fixture.calls.find(x=>x.name==='crm_installation_update'));expect(call.args.p_expected_at).toBe('version-i');expect(call.args.p_patch).not.toHaveProperty('installed_on');expect(call.args.p_patch).not.toHaveProperty('return_text');expect(call.args.p_patch.send).toBe(false);
});

test('Operator tabs preserve unsaved drafts and switch WhatsApp previews without sends',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFInstallationSettings.mount(document.getElementById('settings')));const root=page.locator('#settings');await root.locator('[data-appointment-text]').fill('Hola {nombre}, texto con cita de {operador}.');await root.getByRole('tab',{name:'Devolución',exact:true}).click();await root.locator('[data-router-text]').fill('Texto router personalizado');await expect(root.locator('[data-preview]')).toContainText('Texto router personalizado');await root.getByRole('tab',{name:'Seguimientos',exact:true}).click();await root.locator('[data-other-select]').selectOption('rule:1');await root.locator('[data-message] textarea').fill('Texto revisado 3 meses');await expect(root.locator('[data-preview]')).toContainText('Texto revisado 3 meses');await root.locator('[data-operator="Yoigo"]').click();await root.locator('[data-operator="Vodafone"]').click();await expect(root.locator('[data-message] textarea')).toHaveValue('Texto revisado 3 meses');await root.getByRole('tab',{name:'Instalación',exact:true}).click();await expect(root.locator('[data-appointment-text]')).toHaveValue('Hola {nombre}, texto con cita de {operador}.');await expect(root.locator('[data-router-text]')).toHaveValue('Texto router personalizado');await root.locator('[data-notice-kind]').selectOption('no-appointment');await expect(root.locator('[data-no-appointment-text]')).toBeVisible();await expect(root.locator('[data-preview]')).toContainText('Pendiente de cita');expect(await page.evaluate(()=>fixture.calls.some(c=>/save|update|adopt/.test(c.name)))).toBe(false);
});
test('An existing installation opens as a summary and allows incident edits with a past confirmed appointment',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'version-i',appointment_date:'2026-09-29',time_from:'10:00',time_to:'12:00',installed_on:'2026-10-01',previous_operator:'Yoigo',return_text:'Devolución guardada',notice_text:'Aviso guardado',incident:''};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await expect(d.locator('[data-installation-summary]')).toContainText('29/09/2026');await expect(d.locator('[data-editor]')).toBeHidden();await expect(d.locator('[data-open-notice]')).toHaveCount(0);await d.locator('[data-incident]').fill('Cliente pidió ayuda');await d.locator('[data-save]').click();await expect(d).toHaveCount(0);const call=await page.evaluate(()=>fixture.calls.find(c=>c.name==='crm_installation_update'));expect(call.args.p_patch).toEqual({send:false,incident:'Cliente pidió ayuda'});
});
test('Editing a saved notice preserves its date and explicitly requests a single resend',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'version-i',appointment_date:'2026-10-08',time_from:'10:00',time_to:'12:00',previous_operator:'Yoigo',return_text:'Devolución guardada',notice_text:'Aviso guardado'};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await expect(d.locator('[data-editor]')).toBeHidden();await d.locator('[data-open-notice]').click();await d.locator('[data-text]').fill('Aviso personalizado actualizado');await d.locator('[data-send]').check();await d.locator('[data-save]').click();const call=await page.evaluate(()=>fixture.calls.find(c=>c.name==='crm_installation_update'));expect(call.args.p_patch.send).toBe(true);expect(call.args.p_patch.text).toBe('Aviso personalizado actualizado');expect(call.args.p_patch).not.toHaveProperty('appointment_date');expect(call.args.p_patch).not.toHaveProperty('time_from');
});

test('Home groups actions in one cell, keeps tabs on a row and exposes accessible menus',async({page},info)=>{
 await fixture(page);await page.addStyleTag({path:path.resolve('assets/dashboard-home.css')});await page.addStyleTag({path:path.resolve('assets/crm-reference.css')});await page.evaluate(()=>{document.body.classList.add('tpfUnified');window.TPFModules={register(){}};});await page.addScriptTag({path:path.resolve('js/modules/offer-followup-ui.js')});const source=require('node:fs').readFileSync(path.resolve('js/modules/dashboard-performance-guard.js'),'utf8').replace("M.register('dashboard-performance-guard'","window.dashboardFixture={D,build,renderHomePanels};M.register('dashboard-performance-guard'");await page.addScriptTag({content:source});await page.evaluate(()=>{const t=dashboardFixture;t.build();TPFOfferFollowup.state.byOpportunity=new Map([['new',[{id:'offer-new',status:'accepted',operator:'Vodafone',offer_name:'Fibra y móvil',sent_at:'2026-10-01T10:00:00Z',created_at:'2026-10-01T10:00:00Z',accepted_at:'2026-10-02T10:00:00Z'}]]]);t.D.data={today:'2026-10-03',stages:[{id:'p',name:'Pendiente de tramitar'}],opps:[{id:'new',client_name:'Ana Ejemplo',record_id:'contact-new',phone:'600000002',stage_id:'p',title:'Vodafone · Fibra y móvil',amount:35,expected_date:'2026-10-03'}],tasks:[],recordMap:new Map(),reminders:[]};t.D.filter='processing';t.renderHomePanels();});
 const row=page.locator('#dashAlerts tbody tr');await expect(row.locator('.tdReminder [data-of-manage]')).toHaveCount(0);await expect(row.locator('.tdMenuCell [data-of-manage]')).toHaveCount(1);await expect(row.locator('.tdMenuCell [data-of-opportunity]')).toHaveText('Ver oferta');const tabs=await page.locator('#tdFilterBar .tdWorkTab').evaluateAll(els=>els.map(el=>Math.round(el.getBoundingClientRect().top)));expect(new Set(tabs).size).toBe(1);const dots=row.locator('[data-dots]');await dots.click();await expect(dots).toHaveAttribute('aria-expanded','true');await expect(row.locator('.tdRowMenu')).toBeVisible();await page.keyboard.press('Escape');await expect(dots).toHaveAttribute('aria-expanded','false');await expect(row.locator('.tdRowMenu')).toBeHidden();const box=await dots.boundingBox();expect(box.width).toBeGreaterThanOrEqual(35.9);expect(box.height).toBeGreaterThanOrEqual(35.9);await page.evaluate(()=>{window.quickOpened=[];window.crmCan=()=>true;window.openWaQuick=x=>quickOpened.push({kind:'message',prefill:x});window.openAgendaComposer=(x,y)=>quickOpened.push({kind:'task',prefill:x,opportunityId:y.opportunityId});});await dots.click();await expect(row.getByRole('button',{name:'Abrir conversación',exact:true})).toBeVisible();await row.getByRole('button',{name:'Enviar WhatsApp',exact:true}).click();expect(await page.evaluate(()=>quickOpened[0].prefill)).toEqual({phone:'600000002',name:'Ana Ejemplo',contactId:'contact-new'});await dots.click();await row.getByRole('button',{name:'Crear tarea',exact:true}).click();expect(await page.evaluate(()=>quickOpened[1].opportunityId)).toBe('new');expect(await page.evaluate(()=>fixture.calls.some(c=>/send|update|save/.test(c.name)))).toBe(false);
 if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/home-'+info.project.name+'.png'});
});
test('Operator editor and preview fit desktop and mobile layouts',async({page},info)=>{
 await fixture(page);await page.addStyleTag({path:path.resolve('assets/app.css')});await page.addStyleTag({path:path.resolve('assets/crm-reference.css')});await page.evaluate(desktop=>{document.body.classList.add('tpfUnified');const root=document.getElementById('settings');root.style.cssText=desktop?'padding:24px;max-width:1100px;margin:0 auto':'padding:16px';document.getElementById('view-dashboard').remove();},info.project.name==='desktop');await page.evaluate(()=>TPFInstallationSettings.mount(document.getElementById('settings')));await expect(page.locator('#settings [data-preview]')).toContainText('Vodafone');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);if(info.project.name==='desktop'){const editor=await page.locator('.tpfOperatorEditor').boundingBox(),preview=await page.locator('.tpfOperatorPreview').boundingBox();expect(preview.x).toBeGreaterThan(editor.x+editor.width);}
 if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/settings-'+info.project.name+'.png',fullPage:true});
});

test('Staff confirmation records an actual date, preserves conflict drafts and replies immediately with the router instructions',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'staff-version',appointment_date:'2026-10-08',time_from:'10:00',previous_operator:'Yoigo',return_text:'Router anterior',notice_text:'Aviso guardado'};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await d.locator('[data-confirm-store]').click();await expect(d.locator('[data-save]')).toHaveText('Confirmar instalación');await expect(d.locator('[data-store-due]')).toContainText('Se enviarán ahora');await d.locator('[data-installed-date]').fill('2026-10-04');await d.locator('[data-save]').click();await expect(d.locator('[data-status]')).toContainText('pasada o de hoy');expect(await page.evaluate(()=>fixture.calls.filter(c=>c.name==='crm_installation_update').length)).toBe(0);
 await d.locator('[data-installed-date]').fill('2026-10-02');await page.evaluate(()=>fixture.fail=true);await d.locator('[data-save]').click();await expect(d.locator('[data-status]')).toContainText('otro dispositivo');await expect(d.locator('[data-installed-date]')).toHaveValue('2026-10-02');await expect(d.locator('[data-save]')).toBeEnabled();await page.evaluate(()=>fixture.fail=false);await d.locator('[data-save]').click();await expect(d).toHaveCount(0);const calls=await page.evaluate(()=>fixture.calls.filter(c=>c.name==='crm_installation_update'));expect(calls[1].args).toEqual({p_opportunity_id:'op',p_expected_at:'staff-version',p_patch:{confirm_installed_on:'2026-10-02',incident:''}});expect(await page.evaluate(()=>fixture.calls.some(c=>/stage|direct_sale/.test(c.name)))).toBe(false);
});
test('Other notices select one message, expose active status and keep preview after losing focus',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFInstallationSettings.mount(document.getElementById('settings')));const root=page.locator('#settings');await root.getByRole('tab',{name:'Seguimientos',exact:true}).click();await expect(root.locator('[data-netflix-panel]')).toBeHidden();await expect(root.locator('[data-preview]')).toContainText('Selecciona un aviso');await root.locator('[data-other-select]').selectOption('rule:1');await expect(root.locator('[data-other-meta]')).toContainText('Activo');await expect(root.locator('[data-message] h4')).toHaveText('Seguimiento a los 3 meses');await root.locator('[data-message] textarea').fill('Hola {nombre}, revisión de {operador}');await root.locator('[data-other-select]').focus();await expect(root.locator('[data-preview]')).toContainText('Hola Ana, revisión de Vodafone');await page.evaluate(()=>fixture.fail=true);await root.locator('[data-save-message]').click();await expect(root.locator('[data-message-status]')).toContainText('otro dispositivo');await expect(root.locator('[data-message] textarea')).toHaveValue('Hola {nombre}, revisión de {operador}');const call=await page.evaluate(()=>fixture.calls.find(c=>c.name==='crm_operator_communication_save'));expect(call.args.p_expected_body).toBe('Mensaje original 3 meses');await root.locator('[data-other-select]').selectOption('netflix');await expect(root.locator('[data-netflix-panel]')).toBeVisible();await expect(root.locator('[data-other-meta]')).toContainText('solo si');await expect(root.locator('[data-save]')).toBeVisible();
});
test('Home installation card opens daily review with confirmation and date filters',async({page})=>{
 await fixture(page);await page.evaluate(()=>window.TPFModules={register(){}});const source=require('node:fs').readFileSync(path.resolve('js/modules/dashboard-performance-guard.js'),'utf8').replace("M.register('dashboard-performance-guard'","window.dashboardFixture={D,build};M.register('dashboard-performance-guard'");await page.addScriptTag({content:source});await page.evaluate(()=>dashboardFixture.build());await page.evaluate(async()=>{await TPFInstallationRegistry.load(true);window.dispatchEvent(new Event('tpf:dashboard-rendered'));});await expect(page.locator('#tdPulseInstallations')).toHaveText('3');await expect(page.locator('#tdPulseInstallationsText')).toHaveText('0 hoy · 2 sin confirmar');await page.locator('.tdPulse[data-install-all]').click();const d=page.locator('#tpfInstallRegistryDialog');await expect(d.locator('[data-filter=active]')).toHaveAttribute('aria-pressed','true');await expect(d.locator('tbody tr')).toHaveCount(3);await d.locator('[data-filter=pending]').click();await expect(d.locator('tbody tr')).toHaveCount(2);await d.locator('[data-from]').fill('2026-10-07');await d.locator('[data-until]').fill('2026-10-08');await expect(d.locator('tbody')).toContainText('Ana Ejemplo');await expect(d.locator('tbody')).not.toContainText('Luis Ejemplo');await d.locator('[data-clear-dates]').click();await expect(d.locator('tbody tr')).toHaveCount(2);await d.locator('[data-filter=confirmed]').click();await expect(d.locator('tbody')).toContainText('Sara Ejemplo');
});
test('Customer quick actions preserve holder and recipient and open editors without sending',async({page})=>{
 await fixture(page);await page.addScriptTag({path:path.resolve('js/modules/offer-followup-ui.js')});const results=await page.evaluate(async()=>{const calls=[];window.openWaQuick=x=>calls.push({kind:'message',prefill:x});window.openAgendaComposer=(x,y)=>calls.push({kind:'task',prefill:x,opportunityId:y.opportunityId});window.crmCan=()=>true;const o={id:'quick',record_id:'holder-id',client_name:'Titular Ejemplo',phone:'600000009',title:'CAMBIO VODAFONE',contract_party:{same:false,recipient_contact_id:'manager-id',recipient_name:'Gestora Ejemplo',recipient_phone:'600000001'}};await TPFOfferFollowup.quickAction('message',o.id,o);await TPFOfferFollowup.quickAction('task',o.id,o);let error;try{await TPFOfferFollowup.quickAction('message',o.id,{...o,contract_party:{...o.contract_party,recipient_phone:''}});}catch(e){error=e.message;}return {calls,error};});expect(results.calls[0].prefill).toEqual({phone:'600000001',name:'Gestora Ejemplo',contactId:'manager-id'});expect(results.calls[1].prefill.contactId).toBe('holder-id');expect(results.calls[1].opportunityId).toBe('quick');expect(results.calls[1].prefill.overlay).toBe(true);expect(results.error).toContain('teléfono');expect(await page.evaluate(()=>fixture.calls.length)).toBe(0);
});

test('Confirmed installation keeps its appointment time and actual date visible',async({page},info)=>{
 await fixture(page);await page.evaluate(()=>{fixture.registry=[{opportunity_id:'time',client_name:'Cliente Ejemplo',operator:'MásMóvil',status:'confirmed',appointment_date:'2026-10-05',time_from:'19:33',time_to:'22:36',installed_on:'2026-10-03',confirmation_source:'customer',return_status:'done',return_job_id:'return'}];});await page.evaluate(()=>TPFInstallationRegistry.open());const d=page.locator('#tpfInstallRegistryDialog');await expect(d.locator('tbody')).toContainText('05/10/2026 · 19:33–22:36');await expect(d.locator('tbody')).toContainText('Instalada el 03/10/2026 · Confirmada por el cliente');await expect(d.locator('tbody')).toContainText('Devolución: Enviado');if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/installation-dates-'+info.project.name+'.png'});
});
test('Installation offers only appointment notices and routes the installed reply to router instructions',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFInstallationSettings.mount(document.getElementById('settings')));const root=page.locator('#settings');await expect(root.locator('[data-notice-kind] option')).toHaveText(['Con cita confirmada','Sin cita todavía']);await expect(root.locator('[data-confirmed-text]')).toBeHidden();await expect(root.locator('[data-preview-button]')).toBeVisible();await expect(root.locator('[data-date-prompt-text]')).toHaveCount(0);await root.getByRole('tab',{name:'Devolución',exact:true}).click();await expect(root).toContainText('a cualquier hora y también en fin de semana');await expect(root.locator('[data-return-time]')).toHaveCount(0);
});
test('Manage displays the single confirmation and return message and its actual recipient',async({page},info)=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'version',operator:'Vodafone',appointment_date:'2026-10-05',time_from:'19:33',time_to:'22:36',installed_on:'2026-10-03',confirmation_source:'store',previous_operator:'Yoigo',return_status:'done',return_message:'Gracias Gestora. Instalación registrada el 03/10/2026.\n\n📦 Devolución del router de Yoigo\nEntrega el equipo y conserva el justificante.',notice_text:'Aviso de cita guardado'};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await expect(d).toContainText('Confirmada por la tienda');await expect(d).toContainText('05/10/2026 · 19:33–22:36');await d.getByText('Devolución del router · Enviado',{exact:true}).click();await expect(d.locator('.tpfInstallationMessages')).toContainText('Devolución del router de Yoigo');await expect(d.locator('.tpfInstallationMessages')).toContainText('Gestora');await expect(d.locator('[data-confirm-store]')).toHaveCount(0);if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/installation-message-'+info.project.name+'.png'});
});

test('Sales processing chooser loads its own layout and keeps close and confirm visible on short screens',async({page},info)=>{
 await page.setViewportSize(info.project.name==='desktop'?{width:1280,height:650}:{width:390,height:650});await fixture(page);await page.addStyleTag({path:path.resolve('assets/app.css')});await page.addStyleTag({path:path.resolve('assets/crm-reference.css')});await page.evaluate(()=>{document.body.classList.add('tpfUnified');fixture.operators.Vodafone.no_appointment_text+='\n\n'+('Instrucciones adicionales del operador.\n').repeat(18);window.choice='pending';void TPFRouterReturn.choose({id:'op'}).then(result=>window.choice=result);});
 const d=page.locator('#tpfRouterDialog');await expect(d).toBeVisible();await expect(page.locator('#tpfRouterStyle')).toHaveCount(1);const footer=d.locator('footer'),close=d.getByRole('button',{name:'Cerrar',exact:true}),confirm=footer.locator('button.primary');
 const fits=async()=>{for(const target of [close,confirm]){const box=await target.boundingBox();expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThanOrEqual(650);}expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);};await fits();
 await d.locator('[data-appointment-mode=scheduled]').click();await confirm.click();await expect(d.locator('[data-error]')).toContainText('fecha y la hora');await expect(d.locator('[data-error]')).toBeInViewport();await fits();
 await d.locator('[data-date]').fill('2026-10-08');await d.locator('[data-slot]').selectOption('0');await d.locator('[data-extra] summary').click();await d.locator('[data-return-text]').fill('Instrucciones personalizadas del router');await d.locator('[data-fields]').evaluate(el=>el.scrollTop=el.scrollHeight);await fits();
 if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-dialog/processing-'+info.project.name+'.png'});await confirm.click();await expect(d).toHaveCount(0);expect(await page.evaluate(()=>choice)).toMatchObject({workflow:'installation_v1',appointment_date:'2026-10-08',time_from:'10:00',time_to:'12:00',return_text:'Instrucciones personalizadas del router',send:true});
 await page.evaluate(()=>{window.choice='pending';void TPFRouterReturn.choose({id:'op'}).then(result=>window.choice=result);});await d.locator('[data-appointment-mode=scheduled]').click();await close.click();await expect(d).toHaveCount(0);expect(await page.evaluate(()=>choice)).toBeNull();expect(await page.evaluate(()=>fixture.calls.filter(c=>!['crm_installation_preview','crm_installations_list'].includes(c.name)))).toEqual([]);
});
test('Confirmed sales chooser and return management show history without a frozen appointment form',async({page},info)=>{
 await page.setViewportSize(info.project.name==='desktop'?{width:1280,height:650}:{width:390,height:650});await fixture(page);await page.addStyleTag({path:path.resolve('assets/app.css')});await page.addStyleTag({path:path.resolve('assets/crm-reference.css')});await page.evaluate(()=>{document.body.classList.add('tpfUnified');fixture.i={id:'installation',updated_at:'confirmed-version',operator:'Vodafone',appointment_date:'2026-09-29',time_from:'19:33',time_to:'22:36',installed_on:'2026-10-03',confirmation_source:'customer',previous_operator:'Yoigo',return_text:'Instrucciones guardadas',return_status:'done',notice_status:'done',notice_text:'Aviso enviado que se conserva'};window.choice='pending';void TPFRouterReturn.choose({id:'op'}).then(result=>window.choice=result);});
 const d=page.locator('#tpfRouterDialog');await expect(d.locator('[data-installation-summary]')).toContainText('29/09/2026 · 19:33–22:36');await expect(d.locator('[data-installation-summary]')).toContainText('Instalada el 03/10/2026');await expect(d.locator('[data-appointment-editor]')).toBeHidden();await expect(d.locator('[data-lock-info]')).toContainText('confirmada');await expect(d.locator('[data-extra]')).not.toHaveAttribute('open','');await d.locator('[data-extra] summary').click();await expect(d.locator('[data-previous]')).toBeDisabled();await expect(d.locator('[data-return-editor]')).toBeHidden();await expect(d.locator('[data-return-preview]')).not.toContainText('{nombre}');
 await d.locator('footer button.primary').click();await expect(d).toHaveCount(0);expect(await page.evaluate(()=>choice)).toMatchObject({appointment_date:'2026-09-29',time_from:'19:33',time_to:'22:36',text:'Aviso enviado que se conserva',previous_operator:'Yoigo',return_text:'Instrucciones guardadas',send:false});
 await page.evaluate(()=>TPFInstallations.manage('op'));const manage=page.locator('#tpfInstallationDialog');await manage.locator('[data-edit-return]').click();await expect(manage.locator('[data-previous]')).toBeDisabled();await expect(manage.locator('[data-return-editor]')).toBeHidden();await expect(manage.locator('[data-return-preview]')).not.toContainText('{nombre}');await manage.locator('[data-close]').first().click();expect(await page.evaluate(()=>fixture.calls.some(c=>/update|adopt|send|stage|direct_sale/.test(c.name)))).toBe(false);

});
test('Cancelling or failing Tramitado restores the persisted pending stage without replacing focused sales controls',async({page})=>{
 await fixture(page);await page.evaluate(()=>{document.getElementById('view-dashboard').remove();document.getElementById('editor').innerHTML='<div id="salesListView"><div id="salesListRows"></div></div>';window.$=id=>document.getElementById(id);window.esc=String;window.fmtMoney=String;window.fmtDateOnly=String;window.updateSalesBulkUi=()=>{};window.salesCache={stages:[{id:'pending',name:'Pendiente de tramitar'},{id:'processed',name:'Tramitado'}],opportunities:[{id:'op',stage_id:'pending',title:'Oferta de prueba',client_name:'Cliente Ejemplo',expected_date:'2026-10-08'}]};window.salesFilteredOpps=()=>salesCache.opportunities;window.loadSales=async()=>renderSalesList();});
 const fs=require('node:fs'),core=fs.readFileSync(path.resolve('js/core/20-main.js'),'utf8'),sales=fs.readFileSync(path.resolve('js/modules/contacts-sales-core.js'),'utf8');await page.addScriptTag({content:core.slice(core.indexOf('function renderSalesList(){'),core.indexOf('\nfunction setSalesView'))});await page.addScriptTag({content:sales.slice(sales.indexOf('window.moveOpp='),sales.indexOf('\n\nwindow.deleteOpp='))});await page.evaluate(()=>renderSalesList());
 const select=page.locator('.salesListRow select'),input=page.locator('.salesListDateInput');await select.selectOption('processed');await expect(page.locator('#tpfRouterDialog')).toBeVisible();await page.locator('#tpfRouterDialog').getByRole('button',{name:'Cancelar',exact:true}).click();await expect(page.locator('#tpfRouterDialog')).toHaveCount(0);await expect(select).toHaveValue('pending');await input.fill('Borrador de fecha');await input.focus();await page.evaluate(()=>{window.keptInput=document.querySelector('.salesListDateInput');renderSalesList();});await expect(input).toHaveValue('Borrador de fecha');await expect(input).toBeFocused();expect(await page.evaluate(()=>keptInput===document.querySelector('.salesListDateInput'))).toBe(true);expect(await page.evaluate(()=>salesCache.opportunities[0].stage_id)).toBe('pending');expect(await page.evaluate(()=>fixture.calls.filter(c=>!['crm_installation_preview','crm_installations_list'].includes(c.name)))).toEqual([]);
 await page.evaluate(()=>{window.stageAlerts=[];window.stageWriteAttempts=0;window.alert=message=>stageAlerts.push(message);const read=sb.from;sb.from=table=>{if(table!=='sales_opportunities')return read(table);const q=read(table);q.update=()=>{stageWriteAttempts++;return{eq(){return this},then(resolve){return Promise.resolve({error:{message:'No tienes permiso para guardar'}}).then(resolve)}}};return q;};});
 for(const handler of [sales.slice(sales.indexOf('window.moveOpp='),sales.indexOf('\n\nwindow.deleteOpp=')),core.slice(core.indexOf('window.moveOpp=async(id,stage)=>{'),core.indexOf('\nwindow.deleteOpp='))]){await page.addScriptTag({content:handler});await select.selectOption('processed');await expect(page.locator('#tpfRouterDialog')).toBeVisible();await page.locator('#tpfRouterDialog footer .primary').click();await expect(page.locator('#tpfRouterDialog')).toHaveCount(0);await expect(select).toHaveValue('pending');await expect(input).toHaveValue('Borrador de fecha');}expect(await page.evaluate(()=>stageWriteAttempts)).toBe(2);expect(await page.evaluate(()=>stageAlerts)).toEqual(['No tienes permiso para guardar','No tienes permiso para guardar']);expect(await page.evaluate(()=>salesCache.opportunities[0].stage_id)).toBe('pending');
});
test('Sales and contact processing use the shared drawer and show actual sent messages as history',async({page},info)=>{
 await page.setViewportSize({width:info.project.name==='desktop'?1280:390,height:650});await fixture(page);await page.addScriptTag({path:path.resolve('js/modules/home-manage-panel.js')});await page.evaluate(()=>{fixture.i={id:'installation',opportunity_id:'op',updated_at:'confirmed-version',operator:'Vodafone',appointment_date:'2026-10-05',time_from:'12:00',time_to:'14:00',installed_on:'2026-10-03',confirmation_source:'customer',previous_operator:'Yoigo',return_text:'Hola {nombre}. Router anterior',return_status:'done',return_message:'Gracias Ana. Devuelve el router de Yoigo en Correos.',return_sent_at:'2026-10-03T10:45:00Z',notice_status:'done',notice_text:'Mensaje que recibió Ana',notice_sent_at:'2026-10-02T11:00:00Z'};window.choice='pending';void TPFRouterReturn.choose({id:'op'}).then(result=>window.choice=result)});
 const d=page.locator('#tpfRouterDialog');await expect(d).toHaveClass(/ofManageDrawer/);await expect(d.locator('[data-fields]')).toBeHidden();await expect(d).toContainText('05/10/2026 · 12:00–14:00');await expect(d).toContainText('Instalada el 03/10/2026');await d.getByText('Devolución del router · Enviado').click();await expect(d).toContainText('Gracias Ana. Devuelve el router de Yoigo en Correos.');await expect(d.locator('.tpfInstallationMessages')).not.toContainText('{nombre}');await expect(d.locator('.tpfInstallationMessages')).toContainText('12:45');const box=await d.boundingBox(),foot=await d.locator('footer').boundingBox();expect(box.x+box.width).toBeCloseTo(info.project.name==='desktop'?1280:390,0);expect(foot.y+foot.height).toBeLessThanOrEqual(650);await d.getByRole('button',{name:'Volver',exact:true}).click();await expect(d).toHaveCount(0);expect(await page.evaluate(()=>choice)).toBeNull();await page.evaluate(()=>{void TPFRouterReturn.choose({id:'op'}).then(result=>window.choice=result)});await d.getByRole('button',{name:'Continuar sin reenviar'}).click();await expect(d).toHaveCount(0);expect((await page.evaluate(()=>choice)).send).toBe(false);expect(await page.evaluate(()=>fixture.calls.some(c=>/update|cancel_confirmation|send|stage/.test(c.name)))).toBe(false);
});
test('Undo confirmation keeps the reason on conflict and requires an explicit audited save',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',opportunity_id:'op',updated_at:'confirmed-version',operator:'Vodafone',installed_on:'2026-10-03',confirmation_source:'customer',previous_operator:'Yoigo',return_status:'done',return_message:'Mensaje que ya salió',confirmation_history:[]};const rpc=sb.rpc;sb.rpc=(name,args)=>{if(name!=='crm_installation_cancel_confirmation')return rpc(name,args);fixture.calls.push({name,args});if(fixture.fail)return Promise.resolve({error:{message:'Cambió en otro dispositivo'}});fixture.i={...fixture.i,installed_on:null,return_status:null,return_message:null,updated_at:'corrected-version',confirmation_history:[{reason:args.p_reason,actor_name:'Tienda',installed_on:'2026-10-03',created_at:'2026-10-03T12:00:00Z',return_message:'Mensaje que ya salió'}]};return Promise.resolve({data:fixture.i})};void TPFInstallations.manage('op')});
 const d=page.locator('#tpfInstallationDialog');await d.getByRole('button',{name:'Confirmación por error: anular'}).click();await d.locator('[name=reason]').fill('Prueba realizada por error');await page.evaluate(()=>fixture.fail=true);await d.getByRole('button',{name:'Anular confirmación',exact:true}).click();await expect(d.locator('.tpfInstallationCorrection [role=alert]')).toContainText('otro dispositivo');await expect(d.locator('[name=reason]')).toHaveValue('Prueba realizada por error');await expect(d.locator('[data-installation-summary]')).toContainText('Instalada el 03/10/2026');await page.evaluate(()=>fixture.fail=false);await d.getByRole('button',{name:'Anular confirmación',exact:true}).click();await expect(d.locator('[data-installation-summary]')).toContainText('Pendiente de confirmar');await expect(d).toContainText('Historial de correcciones');expect(await page.evaluate(()=>fixture.calls.filter(c=>c.name==='crm_installation_cancel_confirmation').at(-1).args)).toEqual({p_opportunity_id:'op',p_expected_at:'confirmed-version',p_reason:'Prueba realizada por error'});expect(await page.evaluate(()=>fixture.calls.some(c=>/installation_update|adopt|send|stage/.test(c.name)))).toBe(false);
});

test('Moving back to pending keeps history visible and hides installation actions until processing',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',opportunity_id:'op',updated_at:'pending-version',operator:'Vodafone',installed_on:'2026-10-03',confirmation_source:'customer',previous_operator:'Yoigo',return_status:'done',return_message:'Mensaje que ya salió'};const rpc=sb.rpc;sb.rpc=async(name,args)=>{const result=await rpc(name,args);if(name==='crm_installation_preview')result.data.stage_name='Pendiente de tramitar';return result};void TPFInstallations.manage('op')});
 const d=page.locator('#tpfInstallationDialog');await expect(d).toContainText('Estado actual: Pendiente de tramitar');await expect(d.locator('[data-confirm-store]')).toHaveCount(0);await expect(d.locator('[data-edit-appointment]')).toHaveCount(0);await expect(d.locator('[data-save]')).toBeHidden();await expect(d.getByRole('button',{name:'Confirmación por error: anular'})).toBeVisible();await d.getByText('Devolución del router · Enviado').click();await expect(d).toContainText('Mensaje que ya salió');await d.getByRole('button',{name:'Volver al listado'}).click();await expect(d).toHaveCount(0);expect(await page.evaluate(()=>fixture.calls.some(c=>/update|cancel_confirmation|send|stage/.test(c.name)))).toBe(false);
});

test('Automatic rollback shows the previous installation and sent return only in correction history',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',opportunity_id:'op',updated_at:'pending-version',operator:'Vodafone',installed_on:null,previous_operator:'Yoigo',appointment_date:'2026-10-05',time_from:'12:00',time_to:'14:00',confirmation_history:[{event_type:'processing_reverted',reason:'Tramitación anulada al volver a Pendiente de tramitar',actor_name:'Tienda',installed_on:'2026-10-03',created_at:'2026-10-03T12:00:00Z',return_message:'Mensaje que ya salió',return_sent_at:'2026-10-03T10:00:00Z'}]};const rpc=sb.rpc;sb.rpc=async(name,args)=>{const result=await rpc(name,args);if(name==='crm_installation_preview')result.data.stage_name='Pendiente de tramitar';return result};void TPFInstallations.manage('op')});
 const d=page.locator('#tpfInstallationDialog');await expect(d.locator('[data-installation-summary]')).toContainText('Pendiente de confirmar');await expect(d.locator('[data-installation-summary]')).not.toContainText('Instalada el');await expect(d.locator('[data-installation-summary]')).toContainText('05/10/2026 · 12:00–14:00');await expect(d.getByRole('button',{name:'Confirmación por error: anular'})).toHaveCount(0);
 await d.getByText('Historial de correcciones · 1').click();await expect(d.locator('.tpfInstallationHistory')).toContainText('Tramitación anulada');await d.getByText('Mensaje anterior ·').click();await expect(d.locator('.tpfInstallationHistory')).toContainText('Mensaje que ya salió');expect(await page.evaluate(()=>fixture.calls.some(c=>/update|cancel_confirmation|send|stage/.test(c.name)))).toBe(false);
});
