const {test,expect}=require('@playwright/test'),path=require('node:path');
test('Labels keep typing and an open draft when asynchronous data refresh finishes',async({page})=>{
 await page.route('**/*',r=>r.abort());await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><div id="view-labels"></div>');
 await page.evaluate(()=>{
  window.TPFModules={register(_name,module){module.install()}};window.labelsReads=0;
  window.sb={
   rpc(){return new Promise(resolve=>window.finishLabels=()=>resolve({data:[{id:1,name:'Vodafone'}]}))},
   from(){return{select(){return this},eq(){return this},async maybeSingle(){return{data:{value:{}}}},then(resolve){labelsReads++;return Promise.resolve({data:[{label_id:1}]}).then(resolve)}};}
  };
 });
 const source=require('node:fs').readFileSync(path.resolve('js/modules/labels-modern-ui.js'),'utf8').replace("M.register('labels-modern-ui'","window.labelsFixture={load};M.register('labels-modern-ui'");await page.addScriptTag({content:source});const input=page.locator('#lmSearch');await input.pressSequentially('zzzz rendimiento');
 await page.evaluate(()=>{window.searchBefore=document.getElementById('lmSearch');finishLabels();});
 await expect(page.locator('#view-labels')).not.toHaveAttribute('aria-busy','true');await expect(input).toBeFocused();await page.keyboard.type(' teclado');await expect(input).toHaveValue('zzzz rendimiento teclado');
 expect(await page.evaluate(()=>searchBefore===document.getElementById('lmSearch'))).toBe(true);await expect(page.locator('.lmFooter')).toContainText('0 etiquetas');await input.fill('Vodafone');await expect(page.locator('.lmFooter')).toContainText('1 etiqueta');
 await page.locator('#lmNew').click();await page.locator('#lmName').fill('Borrador sin guardar');await page.locator('#lmCategory').fill('Categoría nueva');
 await page.evaluate(()=>{void labelsFixture.load()});await expect(page.locator('#view-labels')).toHaveAttribute('aria-busy','true');await page.evaluate(()=>finishLabels());
 await expect(page.locator('#view-labels')).not.toHaveAttribute('aria-busy','true');await expect(page.locator('#lmModalBack')).toBeVisible();await expect(page.locator('#lmName')).toHaveValue('Borrador sin guardar');await expect(page.locator('#lmCategory')).toHaveValue('Categoría nueva');expect(await page.evaluate(()=>labelsReads)).toBe(2);
});
async function fixture(page){
 await page.route('**/*',r=>r.abort());await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><style>.hidden{display:none!important}body{margin:0;font:14px Arial;color:#24354b}button{cursor:pointer}</style><div id="app"><div id="view-dashboard" class="tpfDashPro"><div class="tdCommercialDetails"></div></div></div><div id="settings"></div><div id="editor"></div>');
 await page.clock.setFixedTime(new Date('2026-10-03T16:30:00Z'));
 await page.evaluate(()=>{
  const defaults={shop_phone:'',slots:[],return_time:'10:00',appointment_text:'Hola {nombre}. Instalación de {operador} el {fecha}, {franja}. Estate pendiente del teléfono. Si hay algún problema, {ayuda}. Pulsa Instalado.',no_appointment_text:'Hola {nombre}. Pendiente de cita de {operador}. Si hay algún problema, {ayuda}.',date_prompt_text:'¿Qué día te instalaron?',date_other_text:'Fecha DD/MM/AAAA',confirmed_text:'Instalación del {fecha_instalacion} registrada.'};
  window.fixture={defaults,operators:{Vodafone:{...defaults,operator:'Vodafone',updated_at:'first',slots:[{from:'10:00',to:'12:00'}]}},calls:[],fail:false,i:null};
  window.sb={auth:{onAuthStateChange(){}},from(){return{select(){return this},async like(){return{data:[]}}}},rpc(name,args){fixture.calls.push({name,args});let result;
   if(name==='crm_installation_preview')result={data:{workflow:'installation_v1',available:true,operator:'Vodafone',recipient:'Gestora Ejemplo',recipient_first_name:'Gestora',phone:'600000001',opportunity_updated_at:'op-version',installation_config:fixture.operators.Vodafone,preferences:{previous_operator:'Yoigo'},installation:fixture.i}};
   else if(name==='crm_installation_settings')result={data:{defaults,operators:fixture.operators}};
   else if(name==='crm_operator_communication_templates')result={data:[{rule_id:'rule',rule_name:'3 meses · '+args.p_operator,template_id:1,template_name:'Seguridad',enabled:true,body:'Mensaje original 3 meses',schedule:'Regla existente'}]};
   else if(name==='crm_installation_save_settings'){if(fixture.fail)result={error:{message:'Conflicto en otro dispositivo'}};else{fixture.operators[args.p_operator]={...args.p_config,operator:args.p_operator,updated_at:'saved'};result={data:fixture.operators[args.p_operator]};}}
   else if(name==='crm_installation_update'||name==='crm_installation_adopt'||name==='crm_operator_communication_save')result=fixture.fail?{error:{message:'Cambió en otro dispositivo'}}:{data:{}};
   else if(name==='crm_installations_list')result={data:fixture.registry||[{opportunity_id:'op3',client_name:'Ana Ejemplo',operator:'Vodafone',price:35,appointment_date:'2026-10-08',time_from:'10:00',time_to:'12:00',status:'scheduled',offer_instance_id:'offer3',offer_sent:true},{opportunity_id:'op1',client_name:'Luis Ejemplo',operator:'O2',price:30,appointment_date:'2026-10-06',time_from:'09:00',time_to:'11:00',status:'scheduled'},{opportunity_id:'op2',client_name:'Sara Ejemplo',operator:'MásMóvil',status:'confirmed',installed_on:'2026-10-02',return_due_at:'2026-10-06T08:00:00Z'},{opportunity_id:'op4',client_name:'Elena Ejemplo',operator:'Orange',status:'excel',excel_date:'2026-09-20'}]};
   else throw Error('Unexpected RPC '+name);
   const promise=Promise.resolve(result);promise.range=()=>Promise.resolve(result);return promise;
  }};
 });
 for(const file of ['router-return','installation-communications','installation-settings','installation-registry','router-return-settings'])await page.addScriptTag({path:path.resolve('js/modules/'+file+'.js')});
}
test('Processing edits appointment, preserves client draft, copies recipient and separates return',async({page})=>{
 await fixture(page);await page.evaluate(async()=>{const data=await TPFRouterReturn.preview({id:'op'});window.controller=TPFRouterReturn.bind(document.getElementById('editor'),data,{preferences:{previous_operator:'Yoigo'}});});
 const root=page.locator('#editor');await expect(root).toContainText('Gestora Ejemplo');await expect(root.locator('[data-send]')).toBeChecked();await root.locator('[data-appointment-mode=scheduled]').click();await root.locator('[data-date]').fill('2026-10-08');await root.locator('[data-slot]').selectOption('0');await expect(root.locator('[data-text]')).toHaveValue(/08\/10\/2026.*10:00.*12:00/);
 await expect(root.locator('[data-text]')).not.toHaveValue(/router de Yoigo/);await expect(root.locator('[data-return-text]')).toHaveValue(/router de Yoigo/);
 await root.locator('[data-edit-notice]').click();await root.locator('[data-text]').fill('Aviso personalizado de Gestora');await root.locator('[data-date]').fill('2026-10-09');await root.locator('[data-from]').focus();await expect(root.locator('[data-text]')).toHaveValue('Aviso personalizado de Gestora');
 const p=await page.evaluate(()=>controller.get());expect(p.workflow).toBe('installation_v1');expect(p.appointment_date).toBe('2026-10-09');expect(p.send_at).toBeNull();expect(p.previous_operator).toBe('Yoigo');expect(p.text).toBe('Aviso personalizado de Gestora');
 await root.locator('[data-extra] summary').click();await root.locator('[data-previous]').selectOption('Ninguno');await expect(root.locator('[data-return-text]')).toBeDisabled();await expect(root).toContainText('Sin router anterior que devolver');
});
test('Unknown date is allowed; invalid ranges and dates are rejected without sends',async({page})=>{
 await fixture(page);await page.evaluate(async()=>{window.controller=TPFInstallations.bind(document.getElementById('editor'),await TPFInstallations.preview({id:'op'}),{});});
 expect((await page.evaluate(()=>controller.get())).appointment_date).toBeNull();await expect(page.locator('#editor [data-text]')).toHaveValue(/Pendiente de cita/);
 await page.locator('#editor [data-appointment-mode=scheduled]').click();await page.locator('#editor [data-from]').fill('12:00');expect(await page.evaluate(()=>{try{controller.get();return '';}catch(e){return e.message;}})).toContain('fecha y la hora');
 await page.locator('#editor [data-date]').fill('2026-10-05');await page.locator('#editor [data-to]').fill('09:00');expect(await page.evaluate(()=>{try{controller.get();return '';}catch(e){return e.message;}})).toContain('posterior');expect(await page.evaluate(()=>fixture.calls.some(x=>/update|adopt/.test(x.name)))).toBe(false);
 expect(await page.evaluate(()=>TPFInstallations.businessDays('2026-10-02'))).toBe('2026-10-06');expect(await page.evaluate(()=>TPFInstallations.businessDays('2026-10-03'))).toBe('2026-10-06');
});
test('Configuration groups all texts per operator, saves atomically and keeps conflicts visible',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFRouterSettings.mount(document.getElementById('settings')));const root=page.locator('#settings');await expect(root.locator('[data-title]')).toHaveText('Vodafone');await expect(root).toContainText('Devolución del router de este operador');
 await root.getByText('Teléfono de ayuda',{exact:true}).click();await root.locator('[data-shop-phone]').fill('958000000');await expect(root.locator('[data-preview]')).toContainText('958000000');await root.getByRole('tab',{name:'Devolución',exact:true}).click();await root.locator('[data-router-text]').fill('Instrucciones editadas de Vodafone');await root.locator('[data-save]').click();await expect(root.locator('[data-status]')).toContainText('guardada para todos');
 const c=await page.evaluate(()=>fixture.calls.find(x=>x.name==='crm_installation_save_settings'));expect(c.args.p_config.router_text).toBe('Instrucciones editadas de Vodafone');expect(c.args.p_expected_at).toBe('first');
 await root.locator('[data-operator="Yoigo"]').click();await root.getByRole('tab',{name:'Instalación',exact:true}).click();await root.locator('[data-appointment-text]').fill('Texto nuevo Yoigo');await page.evaluate(()=>fixture.fail=true);await root.locator('[data-save]').click();await expect(root.locator('[data-status]')).toContainText('otro dispositivo');await expect(root.locator('[data-appointment-text]')).toHaveValue('Texto nuevo Yoigo');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('Registry orders visits, filters client confirmation and exposes Excel separately',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFInstallationRegistry.open());const d=page.locator('#tpfInstallRegistryDialog');await expect(d.locator('tbody tr').first()).toContainText('Luis Ejemplo');await expect(d.locator('[data-count]')).toContainText('4 instalaciones');
 await d.locator('[data-filter="confirmed"]').click();await expect(d.locator('tbody tr')).toHaveCount(1);await expect(d.locator('tbody')).toContainText('Sara Ejemplo');await expect(d.locator('tbody')).toContainText('Devolución:');
 await d.locator('[data-filter="excel"]').click();await expect(d.locator('tbody')).toContainText('Elena Ejemplo');await expect(d.locator('tbody')).toContainText('20/09/2026 · Excel');await d.locator('footer [data-close]').click();await expect(d).toHaveCount(0);
});
test('Home installations exclude old undated sales and paginate beyond the first eight',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.registry=[...Array.from({length:31},(_,i)=>({opportunity_id:'new-'+i,client_name:'Cliente nuevo '+i,operator:'Vodafone',legacy:false,status:'undated',created_at:'2026-10-03T10:'+String(i).padStart(2,'0')+':00Z'})),{opportunity_id:'old',client_name:'Antigua sin fecha',operator:'Yoigo',legacy:true,status:'undated'},{opportunity_id:'excel',client_name:'Antigua Excel',operator:'Yoigo',legacy:true,status:'excel',excel_date:'2026-09-01'}];document.getElementById('tpfInstallHome')?.remove();});await page.evaluate(()=>window.dispatchEvent(new Event('tpf:dashboard-rendered')));const home=page.locator('#tpfInstallHome');await home.locator('summary').click();await expect(home.locator('summary')).toContainText('31 en seguimiento');await expect(home.locator('tbody tr')).toHaveCount(10);await expect(home).not.toContainText('Antigua sin fecha');await home.locator('[data-home-next]').click();await expect(home.locator('[data-home-page]')).toHaveText('11–20 de 31 instalaciones');await expect(home.locator('tbody tr').first()).toContainText('Cliente nuevo 10');await home.locator('[data-home-size]').selectOption('all');await expect(home.locator('tbody tr')).toHaveCount(31);await expect(home.locator('[data-home-next]')).toBeDisabled();
 await home.locator('[data-install-all]').click();const dialog=page.locator('#tpfInstallRegistryDialog');await expect(dialog.locator('[data-count]')).toContainText('32 instalaciones');await expect(dialog).not.toContainText('Antigua sin fecha');await dialog.locator('[data-filter="excel"]').click();await expect(dialog.locator('tbody')).toContainText('Antigua Excel');
});
test('Pending processing and processed sales have separate tabs and counters',async({page})=>{
 await fixture(page);await page.evaluate(()=>{window.TPFModules={register(){}};});const source=require('node:fs').readFileSync(path.resolve('js/modules/dashboard-performance-guard.js'),'utf8').replace("M.register('dashboard-performance-guard'","window.dashboardFixture={D,build,renderHomePanels,renderPulse};M.register('dashboard-performance-guard'");await page.addScriptTag({content:source});await page.evaluate(()=>{const t=dashboardFixture;t.build();const accepted={early:Date.parse('2026-09-01'),late:Date.parse('2026-09-20'),done:Date.parse('2026-08-01')};window.TPFOfferFollowup={acceptanceTime:id=>accepted[id],html:()=>'',state:{byOpportunity:new Map()}};t.D.data={today:'2026-10-03',stages:[{id:'p',name:'Pendiente de tramitar'},{id:'d',name:'Tramitado'}],opps:[{id:'late',client_name:'Pendiente reciente',stage_id:'p',expected_date:'2026-10-03'},{id:'done',client_name:'Venta antigua tramitada',stage_id:'d',expected_date:'2026-09-01'},{id:'early',client_name:'Pendiente antigua',stage_id:'p',expected_date:'2026-11-01'}],tasks:[],recordMap:new Map(),reminders:[]};t.renderHomePanels();t.renderPulse(t.D.data,new Map(t.D.data.stages.map(s=>[s.id,s])),[],[],[]);});await expect(page.locator('#tdPulseProcessing')).toHaveText('2');await expect(page.locator('#tdTabCountProcessed')).toHaveText('1');await page.locator('.tdWorkTab[data-home-filter="processing"]').click();await expect(page.locator('#dashAlerts tbody tr')).toHaveCount(2);await expect(page.locator('#dashAlerts tbody tr').first()).toContainText('Pendiente antigua');await expect(page.locator('#dashAlerts')).not.toContainText('Venta antigua tramitada');await page.locator('.tdWorkTab[data-home-filter="processed"]').click();await expect(page.locator('#dashAlerts tbody tr')).toHaveCount(1);await expect(page.locator('#dashAlerts')).toContainText('Venta antigua tramitada');await page.locator('.tdWorkTab[data-home-filter="priority"]').click();await expect(page.locator('#dashAlerts')).not.toContainText('Venta antigua tramitada');
});
test('Operator configuration closes nested installation dialogs and reaches its destination',async({page},info)=>{
 await fixture(page);await page.evaluate(mobile=>{if(mobile){const el=document.createElement('div');el.id='mobileView';document.body.appendChild(el);}else{const nav=document.createElement('button');nav.className='nav';nav.dataset.view='settings';nav.onclick=()=>{window.settingsReached=true;};document.body.appendChild(nav);const tab=document.createElement('button');tab.id='view-settings-router-texts-tab';tab.onclick=()=>{window.operatorTabReached=true;};document.body.appendChild(tab);}},info.project.name==='mobile');
 await page.evaluate(()=>TPFRouterSettings.mount(document.getElementById('settings')));await page.evaluate(()=>TPFInstallationRegistry.open());await page.locator('#tpfInstallRegistryDialog [data-install-manage]').first().click();const d=page.locator('#tpfInstallationDialog');await d.locator('[data-edit-appointment]').click();await d.locator('[data-extra] summary').click();await expect(d.locator('[data-config]')).toBeVisible();await d.locator('[data-config]').click();await expect(d).toHaveCount(0);await expect(page.locator('#tpfInstallRegistryDialog')).toHaveCount(0);await expect(page.locator('#settings [data-title]')).toHaveText('Vodafone');
 if(info.project.name==='mobile')expect(await page.evaluate(()=>location.hash)).toBe('#router-texts');else expect(await page.evaluate(()=>settingsReached&&operatorTabReached)).toBe(true);
});
test('Manage existing installation checks version, does not manually mark installed, preserves failure draft',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'version-i',appointment_date:'2026-10-08',time_from:'10:00',time_to:'12:00',previous_operator:'Yoigo',return_text:'Devolución guardada',notice_text:'Aviso guardado',incident:''};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await expect(d.locator('[data-save]')).toBeEnabled();await expect(d.locator('[data-send]')).not.toBeChecked();await d.locator('[data-incident]').fill('Técnico pendiente de llamar');await page.evaluate(()=>fixture.fail=true);await d.locator('[data-save]').click();await expect(d.locator('[data-status]')).toContainText('otro dispositivo');await expect(d.locator('[data-incident]')).toHaveValue('Técnico pendiente de llamar');
 const call=await page.evaluate(()=>fixture.calls.find(x=>x.name==='crm_installation_update'));expect(call.args.p_expected_at).toBe('version-i');expect(call.args.p_patch).not.toHaveProperty('installed_on');expect(call.args.p_patch).not.toHaveProperty('return_text');expect(call.args.p_patch.send).toBe(false);
});

test('Operator tabs preserve unsaved drafts and switch WhatsApp previews without sends',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFInstallationSettings.mount(document.getElementById('settings')));const root=page.locator('#settings');await root.locator('[data-appointment-text]').fill('Hola {nombre}, texto con cita de {operador}.');await root.getByRole('tab',{name:'Devolución',exact:true}).click();await root.locator('[data-router-text]').fill('Texto router personalizado');await expect(root.locator('[data-preview]')).toContainText('Texto router personalizado');await root.getByRole('tab',{name:'Otros avisos',exact:true}).click();await root.locator('[data-other-select]').selectOption('rule:1');await root.locator('[data-message] textarea').fill('Texto revisado 3 meses');await expect(root.locator('[data-preview]')).toContainText('Texto revisado 3 meses');await root.locator('[data-operator="Yoigo"]').click();await root.locator('[data-operator="Vodafone"]').click();await expect(root.locator('[data-message] textarea')).toHaveValue('Texto revisado 3 meses');await root.getByRole('tab',{name:'Instalación',exact:true}).click();await expect(root.locator('[data-appointment-text]')).toHaveValue('Hola {nombre}, texto con cita de {operador}.');await expect(root.locator('[data-router-text]')).toHaveValue('Texto router personalizado');await root.locator('[data-notice-kind]').selectOption('no-appointment');await expect(root.locator('[data-no-appointment-text]')).toBeVisible();await expect(root.locator('[data-preview]')).toContainText('Pendiente de cita');expect(await page.evaluate(()=>fixture.calls.some(c=>/save|update|adopt/.test(c.name)))).toBe(false);
});
test('An existing installation opens as a summary and allows incident edits with a past confirmed appointment',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'version-i',appointment_date:'2026-09-29',time_from:'10:00',time_to:'12:00',installed_on:'2026-10-01',previous_operator:'Yoigo',return_text:'Devolución guardada',notice_text:'Aviso guardado',incident:''};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await expect(d.locator('[data-installation-summary]')).toContainText('29/09/2026');await expect(d.locator('[data-editor]')).toBeHidden();await expect(d.locator('[data-open-notice]')).toHaveCount(0);await d.locator('[data-incident]').fill('Cliente pidió ayuda');await d.locator('[data-save]').click();await expect(d).toHaveCount(0);const call=await page.evaluate(()=>fixture.calls.find(c=>c.name==='crm_installation_update'));expect(call.args.p_patch).toEqual({send:false,incident:'Cliente pidió ayuda'});
});
test('Editing a saved notice preserves its date and explicitly requests a single resend',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'version-i',appointment_date:'2026-10-08',time_from:'10:00',time_to:'12:00',previous_operator:'Yoigo',return_text:'Devolución guardada',notice_text:'Aviso guardado'};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await expect(d.locator('[data-editor]')).toBeHidden();await d.locator('[data-open-notice]').click();await d.locator('[data-text]').fill('Aviso personalizado actualizado');await d.locator('[data-send]').check();await d.locator('[data-save]').click();const call=await page.evaluate(()=>fixture.calls.find(c=>c.name==='crm_installation_update'));expect(call.args.p_patch.send).toBe(true);expect(call.args.p_patch.text).toBe('Aviso personalizado actualizado');expect(call.args.p_patch).not.toHaveProperty('appointment_date');expect(call.args.p_patch).not.toHaveProperty('time_from');
});

test('Home groups actions in one cell, keeps tabs on a row and exposes accessible menus',async({page},info)=>{
 await fixture(page);await page.addStyleTag({path:path.resolve('assets/dashboard-home.css')});await page.addStyleTag({path:path.resolve('assets/crm-reference.css')});await page.evaluate(()=>{document.body.classList.add('tpfUnified');window.TPFModules={register(){}};});await page.addScriptTag({path:path.resolve('js/modules/offer-followup-ui.js')});const source=require('node:fs').readFileSync(path.resolve('js/modules/dashboard-performance-guard.js'),'utf8').replace("M.register('dashboard-performance-guard'","window.dashboardFixture={D,build,renderHomePanels};M.register('dashboard-performance-guard'");await page.addScriptTag({content:source});await page.evaluate(()=>{const t=dashboardFixture;t.build();TPFOfferFollowup.state.byOpportunity=new Map([['new',[{id:'offer-new',status:'accepted',operator:'Vodafone',offer_name:'Fibra y móvil',sent_at:'2026-10-01T10:00:00Z',created_at:'2026-10-01T10:00:00Z',accepted_at:'2026-10-02T10:00:00Z'}]]]);t.D.data={today:'2026-10-03',stages:[{id:'p',name:'Pendiente de tramitar'}],opps:[{id:'new',client_name:'Ana Ejemplo',record_id:'contact-new',phone:'600000002',stage_id:'p',title:'Vodafone · Fibra y móvil',amount:35,expected_date:'2026-10-03'}],tasks:[],recordMap:new Map(),reminders:[]};t.D.filter='processing';t.renderHomePanels();});
 const row=page.locator('#dashAlerts tbody tr');await expect(row.locator('.tdReminder [data-of-manage]')).toHaveCount(0);await expect(row.locator('.tdMenuCell [data-of-manage]')).toHaveCount(1);await expect(row.locator('.tdMenuCell [data-of-opportunity]')).toHaveText('Ver oferta');const tabs=await page.locator('#tdFilterBar .tdWorkTab').evaluateAll(els=>els.map(el=>Math.round(el.getBoundingClientRect().top)));expect(new Set(tabs).size).toBe(1);const dots=row.locator('[data-dots]');await dots.click();await expect(dots).toHaveAttribute('aria-expanded','true');await expect(row.locator('.tdRowMenu')).toBeVisible();await page.keyboard.press('Escape');await expect(dots).toHaveAttribute('aria-expanded','false');await expect(row.locator('.tdRowMenu')).toBeHidden();const box=await dots.boundingBox();expect(box.width).toBeGreaterThanOrEqual(35.9);expect(box.height).toBeGreaterThanOrEqual(35.9);await page.evaluate(()=>{window.quickOpened=[];window.crmCan=()=>true;window.openWaQuick=x=>quickOpened.push({kind:'message',prefill:x});window.openAgendaComposer=(x,y)=>quickOpened.push({kind:'task',prefill:x,opportunityId:y.opportunityId});});await dots.click();await expect(row.getByRole('button',{name:'Abrir conversación',exact:true})).toBeVisible();await row.getByRole('button',{name:'Enviar WhatsApp',exact:true}).click();expect(await page.evaluate(()=>quickOpened[0].prefill)).toEqual({phone:'600000002',name:'Ana Ejemplo',contactId:'contact-new'});await dots.click();await row.getByRole('button',{name:'Crear tarea',exact:true}).click();expect(await page.evaluate(()=>quickOpened[1].opportunityId)).toBe('new');expect(await page.evaluate(()=>fixture.calls.some(c=>/send|update|save/.test(c.name)))).toBe(false);
 if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/home-'+info.project.name+'.png'});
});
test('Operator editor and preview fit desktop and mobile layouts',async({page},info)=>{
 await fixture(page);await page.addStyleTag({path:path.resolve('assets/app.css')});await page.addStyleTag({path:path.resolve('assets/crm-reference.css')});await page.evaluate(desktop=>{document.body.classList.add('tpfUnified');const root=document.getElementById('settings');root.style.cssText=desktop?'padding:24px;max-width:1100px;margin:0 auto':'padding:16px';document.getElementById('view-dashboard').remove();},info.project.name==='desktop');await page.evaluate(()=>TPFInstallationSettings.mount(document.getElementById('settings')));await expect(page.locator('#settings [data-preview]')).toContainText('Vodafone');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);if(info.project.name==='desktop'){const editor=await page.locator('.tpfOperatorEditor').boundingBox(),preview=await page.locator('.tpfOperatorPreview').boundingBox();expect(preview.x).toBeGreaterThan(editor.x+editor.width);}
 if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/settings-'+info.project.name+'.png',fullPage:true});
});

test('Staff confirmation records an actual date, preserves conflict drafts and replies immediately with the router instructions',async({page})=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'staff-version',appointment_date:'2026-10-08',time_from:'10:00',previous_operator:'Yoigo',return_text:'Router anterior',notice_text:'Aviso guardado'};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await d.locator('[data-confirm-store]').click();await expect(d.locator('[data-save]')).toHaveText('Confirmar instalación');await expect(d.locator('[data-store-due]')).toContainText('Se enviarán ahora');await d.locator('[data-installed-date]').fill('2026-10-04');await d.locator('[data-save]').click();await expect(d.locator('[data-status]')).toContainText('pasada o de hoy');expect(await page.evaluate(()=>fixture.calls.filter(c=>c.name==='crm_installation_update').length)).toBe(0);
 await d.locator('[data-installed-date]').fill('2026-10-02');await page.evaluate(()=>fixture.fail=true);await d.locator('[data-save]').click();await expect(d.locator('[data-status]')).toContainText('otro dispositivo');await expect(d.locator('[data-installed-date]')).toHaveValue('2026-10-02');await expect(d.locator('[data-save]')).toBeEnabled();await page.evaluate(()=>fixture.fail=false);await d.locator('[data-save]').click();await expect(d).toHaveCount(0);const calls=await page.evaluate(()=>fixture.calls.filter(c=>c.name==='crm_installation_update'));expect(calls[1].args).toEqual({p_opportunity_id:'op',p_expected_at:'staff-version',p_patch:{confirm_installed_on:'2026-10-02',incident:''}});expect(await page.evaluate(()=>fixture.calls.some(c=>/stage|direct_sale/.test(c.name)))).toBe(false);
});
test('Other notices select one message, expose active status and keep preview after losing focus',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFInstallationSettings.mount(document.getElementById('settings')));const root=page.locator('#settings');await root.getByRole('tab',{name:'Otros avisos',exact:true}).click();await expect(root.locator('[data-netflix-panel]')).toBeHidden();await expect(root.locator('[data-preview]')).toContainText('Selecciona un aviso');await root.locator('[data-other-select]').selectOption('rule:1');await expect(root.locator('[data-other-meta]')).toContainText('Activo');await expect(root.locator('[data-message] h4')).toHaveText('Seguimiento a los 3 meses');await root.locator('[data-message] textarea').fill('Hola {nombre}, revisión de {operador}');await root.locator('[data-other-select]').focus();await expect(root.locator('[data-preview]')).toContainText('Hola Ana, revisión de Vodafone');await page.evaluate(()=>fixture.fail=true);await root.locator('[data-save-message]').click();await expect(root.locator('[data-message-status]')).toContainText('otro dispositivo');await expect(root.locator('[data-message] textarea')).toHaveValue('Hola {nombre}, revisión de {operador}');const call=await page.evaluate(()=>fixture.calls.find(c=>c.name==='crm_operator_communication_save'));expect(call.args.p_expected_body).toBe('Mensaje original 3 meses');await root.locator('[data-other-select]').selectOption('netflix');await expect(root.locator('[data-netflix-panel]')).toBeVisible();await expect(root.locator('[data-other-meta]')).toContainText('solo si');await expect(root.locator('[data-save]')).toBeVisible();
});
test('Home installation card opens daily review with confirmation and date filters',async({page})=>{
 await fixture(page);await page.evaluate(()=>window.TPFModules={register(){}});const source=require('node:fs').readFileSync(path.resolve('js/modules/dashboard-performance-guard.js'),'utf8').replace("M.register('dashboard-performance-guard'","window.dashboardFixture={D,build};M.register('dashboard-performance-guard'");await page.addScriptTag({content:source});await page.evaluate(()=>dashboardFixture.build());await page.evaluate(async()=>{await TPFInstallationRegistry.load(true);window.dispatchEvent(new Event('tpf:dashboard-rendered'));});await expect(page.locator('#tdPulseInstallations')).toHaveText('3');await expect(page.locator('#tdPulseInstallationsText')).toHaveText('0 hoy · 2 sin confirmar');await page.locator('.tdPulse[data-install-all]').click();const d=page.locator('#tpfInstallRegistryDialog');await expect(d.locator('[data-filter=active]')).toHaveAttribute('aria-pressed','true');await expect(d.locator('tbody tr')).toHaveCount(3);await d.locator('[data-filter=pending]').click();await expect(d.locator('tbody tr')).toHaveCount(2);await d.locator('[data-from]').fill('2026-10-07');await d.locator('[data-until]').fill('2026-10-08');await expect(d.locator('tbody')).toContainText('Ana Ejemplo');await expect(d.locator('tbody')).not.toContainText('Luis Ejemplo');await d.locator('[data-clear-dates]').click();await expect(d.locator('tbody tr')).toHaveCount(2);await d.locator('[data-filter=confirmed]').click();await expect(d.locator('tbody')).toContainText('Sara Ejemplo');
});
test('Customer quick actions preserve holder and recipient and open editors without sending',async({page})=>{
 await fixture(page);await page.addScriptTag({path:path.resolve('js/modules/offer-followup-ui.js')});const results=await page.evaluate(async()=>{const calls=[];window.openWaQuick=x=>calls.push({kind:'message',prefill:x});window.openAgendaComposer=(x,y)=>calls.push({kind:'task',prefill:x,opportunityId:y.opportunityId});window.crmCan=()=>true;const o={id:'quick',record_id:'holder-id',client_name:'Titular Ejemplo',phone:'600000009',title:'CAMBIO VODAFONE',contract_party:{same:false,recipient_contact_id:'manager-id',recipient_name:'Gestora Ejemplo',recipient_phone:'600000001'}};await TPFOfferFollowup.quickAction('message',o.id,o);await TPFOfferFollowup.quickAction('task',o.id,o);let error;try{await TPFOfferFollowup.quickAction('message',o.id,{...o,contract_party:{...o.contract_party,recipient_phone:''}});}catch(e){error=e.message;}return {calls,error};});expect(results.calls[0].prefill).toEqual({phone:'600000001',name:'Gestora Ejemplo',contactId:'manager-id'});expect(results.calls[1].prefill.contactId).toBe('holder-id');expect(results.calls[1].opportunityId).toBe('quick');expect(results.calls[1].prefill.overlay).toBe(true);expect(results.error).toContain('teléfono');expect(await page.evaluate(()=>fixture.calls.length)).toBe(0);
});

test('Confirmed installation keeps its appointment time and actual date visible',async({page},info)=>{
 await fixture(page);await page.evaluate(()=>{fixture.registry=[{opportunity_id:'time',client_name:'Cliente Ejemplo',operator:'MásMóvil',status:'confirmed',appointment_date:'2026-10-05',time_from:'19:33',time_to:'22:36',installed_on:'2026-10-03',confirmation_source:'customer',return_status:'done',return_job_id:'return'}];});await page.evaluate(()=>TPFInstallationRegistry.open());const d=page.locator('#tpfInstallRegistryDialog');await expect(d.locator('tbody')).toContainText('05/10/2026 · 19:33–22:36');await expect(d.locator('tbody')).toContainText('Instalada el 03/10/2026 · Confirmada por el cliente');await expect(d.locator('tbody')).toContainText('Devolución: Enviado');if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/installation-dates-'+info.project.name+'.png'});
});
test('Operator confirmation text and send trigger are clear without the old date question or hour',async({page})=>{
 await fixture(page);await page.evaluate(()=>TPFInstallationSettings.mount(document.getElementById('settings')));const root=page.locator('#settings');await root.locator('[data-notice-kind]').selectOption('confirmed');await expect(root.locator('[data-confirmed-text]')).toBeVisible();await expect(root.locator('[data-preview]')).toContainText('Instalación del');await expect(root.locator('[data-preview-button]')).toBeHidden();await expect(root.locator('[data-send-explanation]')).toContainText('Envío inmediato');await expect(root.locator('[data-date-prompt-text]')).toHaveCount(0);await root.getByRole('tab',{name:'Devolución',exact:true}).click();await expect(root).toContainText('a cualquier hora y también en fin de semana');await expect(root.locator('[data-return-time]')).toHaveCount(0);
});
test('Manage displays the single confirmation and return message and its actual recipient',async({page},info)=>{
 await fixture(page);await page.evaluate(()=>{fixture.i={id:'installation',updated_at:'version',operator:'Vodafone',appointment_date:'2026-10-05',time_from:'19:33',time_to:'22:36',installed_on:'2026-10-03',confirmation_source:'store',previous_operator:'Yoigo',return_status:'done',return_message:'Gracias Gestora. Instalación registrada el 03/10/2026.\n\n📦 Devolución del router de Yoigo\nEntrega el equipo y conserva el justificante.',notice_text:'Aviso de cita guardado'};TPFInstallations.manage('op');});const d=page.locator('#tpfInstallationDialog');await expect(d).toContainText('Confirmada por la tienda');await expect(d).toContainText('05/10/2026 · 19:33–22:36');await d.getByText('Confirmación y devolución · Enviado',{exact:true}).click();await expect(d.locator('.tpfInstallationMessages')).toContainText('Devolución del router de Yoigo');await expect(d.locator('.tpfInstallationMessages')).toContainText('Gestora');await expect(d.locator('[data-confirm-store]')).toHaveCount(0);if(process.env.TPF_VISUAL_REVIEW)await page.screenshot({path:'/tmp/tpf-polish/installation-message-'+info.project.name+'.png'});
});
