const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const source=fs.readFileSync("js/modules/import-mapping.js","utf8");
const context={window:{},document:{readyState:"loading",addEventListener(){}},console};
vm.createContext(context);vm.runInContext(source,context);
const h=context.window.TPFImportMapping;
assert.equal(h.guess("Móvil","contact"),"phone");
assert.equal(h.guess("NIF","contact"),"dni");
assert.equal(h.guess("Correo electrónico","contact"),"email");
assert.equal(h.guess("correo electrónico 1","contact"),"email");
assert.equal(h.guess("teléfono 1","contact"),"phone");
assert.equal(h.guess("teléfono 2","contact"),"phone_2");
assert.equal(h.guess("teléfono 3","contact"),"phone_3");
assert.equal(h.guess("nif/nit","contact"),"dni");
assert.equal(h.guess("Etiquetas","contact"),"labels");
assert.equal(h.guess("observaciones","contact"),"observations");
assert.equal(h.guess("NOTA","contact"),"notes");
assert.equal(h.guess("propietario","contact"),"owner");
assert.equal(h.guess("creado","contact"),"created_at");
assert.equal(h.guess("url de imagen del contacto","contact"),"avatar");
assert.equal(h.guess("importe de oportunidades ganadas","contact"),"ignore");
assert.equal(h.guess("etapa de oportunidad activa","contact"),"ignore");
assert.equal(h.guess("Cierre esperado","opportunity"),"expected_date");
assert.equal(h.guess("Comercial asignado","opportunity"),"custom");
assert.equal(h.digits("+34 695 661 409"),"695661409");
assert.equal(h.number("1.234,50 €"),1234.5);
assert.equal(h.date("04/09/2026"),"2026-09-04");
assert.deepEqual([...h.splitLabels(" holded, WhatsApp api;HOLDÉD\n baja ")],["HOLDED","WHATSAPP API","HOLDÉD","BAJA"]);
console.log("import-mapping: ok");
