-- Durable, permission-protected audit trail for offer follow-up responses.
-- This table is operational only: it never changes opportunity stages or offer status.

create table if not exists public.crm_offer_followup_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  offer_instance_id uuid references public.crm_offer_instances(id) on delete set null,
  opportunity_id uuid references public.sales_opportunities(id) on delete set null,
  contact_id uuid references public.records(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  message_id text,
  job_id uuid references public.crm_server_automation_jobs(id) on delete set null,
  event_type text not null check (event_type in (
    'response_cancelled','pre_send_blocked','verification_deferred',
    'delivery_deferred','followup_failed','followup_sent'
  )),
  result text not null check (result in ('success','warning','error','info')),
  response_text text not null default '',
  detail text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists crm_offer_followup_events_created_idx
  on public.crm_offer_followup_events(created_at desc);
create index if not exists crm_offer_followup_events_offer_idx
  on public.crm_offer_followup_events(offer_instance_id,created_at desc);
create index if not exists crm_offer_followup_events_opportunity_idx
  on public.crm_offer_followup_events(opportunity_id,created_at desc);
create index if not exists crm_offer_followup_events_result_idx
  on public.crm_offer_followup_events(result,created_at desc);

alter table public.crm_offer_followup_events enable row level security;

drop policy if exists crm_offer_followup_events_select on public.crm_offer_followup_events;
create policy crm_offer_followup_events_select
  on public.crm_offer_followup_events for select to authenticated
  using (
    (select public.current_user_is_admin())
    or (select public.current_user_can('can_view_sales'))
  );

revoke all on public.crm_offer_followup_events from public,anon,authenticated;
grant select on public.crm_offer_followup_events to authenticated;
grant all on public.crm_offer_followup_events to service_role;
grant usage,select on sequence public.crm_offer_followup_events_id_seq to service_role;

create or replace function public.crm_list_offer_followup_events(
  p_days integer default 7,
  p_limit integer default 100
)
returns table (
  id bigint,
  event_type text,
  result text,
  response_text text,
  detail text,
  created_at timestamptz,
  offer_instance_id uuid,
  opportunity_id uuid,
  contact_id uuid,
  client_name text,
  opportunity_title text,
  operator text,
  offer_name text
)
language plpgsql
security invoker
set search_path=''
as $$
begin
  if auth.uid() is null or not public.current_user_is_admin() then
    raise exception 'Administrator access required' using errcode='42501';
  end if;
  return query
  select e.id,e.event_type,e.result,e.response_text,e.detail,e.created_at,
    e.offer_instance_id,e.opportunity_id,e.contact_id,
    coalesce(o.client_name,'Cliente'),coalesce(o.title,'Oportunidad'),
    coalesce(i.operator,''),coalesce(i.offer_name,'')
  from public.crm_offer_followup_events e
  left join public.sales_opportunities o on o.id=e.opportunity_id
  left join public.crm_offer_instances i on i.id=e.offer_instance_id
  where coalesce(p_days,7)<=0
     or e.created_at>=now()-make_interval(days=>least(greatest(p_days,1),365))
  order by e.created_at desc
  limit least(greatest(coalesce(p_limit,100),1),250);
end;
$$;

create or replace function public.crm_offer_followup_latest(p_opportunity_id uuid)
returns jsonb
language plpgsql
stable
security invoker
set search_path=''
as $$
declare result jsonb;
begin
  if auth.uid() is null or not (
    public.current_user_is_admin() or public.current_user_can('can_view_sales')
  ) then
    raise exception 'No tienes permiso para ver seguimientos' using errcode='42501';
  end if;
  select jsonb_build_object(
    'event_type',e.event_type,'result',e.result,'response_text',e.response_text,
    'detail',e.detail,'created_at',e.created_at,'offer_instance_id',e.offer_instance_id
  ) into result
  from public.crm_offer_followup_events e
  where e.opportunity_id=p_opportunity_id
  order by e.created_at desc
  limit 1;
  return result;
end;
$$;

revoke all on function public.crm_list_offer_followup_events(integer,integer) from public,anon;
revoke all on function public.crm_offer_followup_latest(uuid) from public,anon;
grant execute on function public.crm_list_offer_followup_events(integer,integer) to authenticated;
grant execute on function public.crm_offer_followup_latest(uuid) to authenticated;

-- Incoming WhatsApp replies cancel offer follow-ups and write one audit row per
-- affected offer. Opportunity columns are deliberately untouched.
create or replace function crm_private.lifecycle_incoming()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare ph text; cid uuid; optout boolean;
begin
  if new.direction is distinct from 'in' or new.chat_id like '%@g.us' then return new; end if;
  ph:=public.crm_server_normalize_phone(split_part(new.chat_id,'@',1));
  if ph is null or length(ph)<8 then return new; end if;
  cid:=public.crm_server_contact_for_phone(ph);
  optout:=crm_private.is_commercial_optout(new.text_content);
  if optout then
    insert into crm_private.commercial_optouts(phone,contact_id,received_at)
    values(ph,cid,new.created_at)
    on conflict(phone) do update set
      contact_id=coalesce(excluded.contact_id,crm_private.commercial_optouts.contact_id),
      received_at=excluded.received_at;
  end if;

  with cancelled as (
    update public.crm_server_automation_jobs j
    set status='cancelled',
      error_message=case when optout then 'Baja comercial solicitada' else 'Cliente respondió: seguimiento detenido' end,
      updated_at=now()
    where j.status in ('pending','running')
      and j.action_type not in ('record_offer_month','record_sale_month')
      and (j.context->>'contact_id'=cid::text or public.crm_server_normalize_phone(j.context->>'phone')=ph)
      and (j.context#>>'{lifecycle,mode}'='offer' or (optout and j.context#>>'{lifecycle,mode}'='after_sale'))
      and coalesce(nullif(j.context->>'event_at','')::timestamptz,j.created_at)<=new.created_at
    returning j.id,j.user_id,j.context
  ), affected as (
    select i.id as offer_id,i.opportunity_id,i.contact_id,c.user_id,count(*)::integer as jobs_cancelled
    from cancelled c
    join public.crm_offer_instances i on i.id::text=c.context->>'offer_instance_id'
    group by i.id,i.opportunity_id,i.contact_id,c.user_id
  )
  insert into public.crm_offer_followup_events(
    event_key,offer_instance_id,opportunity_id,contact_id,user_id,message_id,
    event_type,result,response_text,detail,created_at
  )
  select 'incoming:'||new.id::text||':'||a.offer_id::text,
    a.offer_id,a.opportunity_id,a.contact_id,a.user_id,new.id_message,
    'response_cancelled','success',left(coalesce(new.text_content,''),80),
    a.jobs_cancelled||' seguimiento(s) pendiente(s) cancelado(s)',new.created_at
  from affected a
  on conflict(event_key) do nothing;
  return new;
end;
$$;

revoke all on function crm_private.lifecycle_incoming() from public,anon,authenticated;

comment on table public.crm_offer_followup_events is
  'Operational audit of offer replies, safety deferrals and follow-up delivery; never changes sales stages.';
comment on function public.crm_offer_followup_latest(uuid) is
  'Returns the latest operational follow-up event for one opportunity to authorized CRM users.';
