create table if not exists public.crm_system_events (
  id bigint generated by default as identity primary key,
  fingerprint text not null,
  source text not null default 'frontend',
  module text not null default 'general',
  severity text not null default 'error' check (severity in ('info', 'warning', 'error', 'critical')),
  status text not null default 'active' check (status in ('active', 'resolved', 'ignored')),
  message text not null,
  detail text not null default '',
  route text not null default '',
  device text not null default 'unknown',
  app_version text not null default '',
  reporter_id uuid references auth.users(id) on delete set null,
  context jsonb not null default '{}'::jsonb,
  occurrences integer not null default 1 check (occurrences > 0),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null
);

create unique index if not exists crm_system_events_active_fingerprint_idx
  on public.crm_system_events (fingerprint) where status = 'active';
create index if not exists crm_system_events_last_seen_idx
  on public.crm_system_events (last_seen_at desc);
create index if not exists crm_system_events_status_severity_idx
  on public.crm_system_events (status, severity, last_seen_at desc);
create index if not exists crm_system_events_reporter_id_idx
  on public.crm_system_events (reporter_id);
create index if not exists crm_system_events_resolved_by_idx
  on public.crm_system_events (resolved_by);

alter table public.crm_system_events enable row level security;

drop policy if exists "Admins read system events" on public.crm_system_events;
create policy "Admins read system events"
  on public.crm_system_events for select to authenticated
  using (public.current_user_is_admin());

drop policy if exists "Admins update system events" on public.crm_system_events;
create policy "Admins update system events"
  on public.crm_system_events for update to authenticated
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());

revoke all on public.crm_system_events from anon, authenticated;
grant select, update on public.crm_system_events to authenticated;

create or replace function private.crm_report_system_event_impl(
  p_source text,
  p_module text,
  p_severity text,
  p_message text,
  p_detail text default '',
  p_route text default '',
  p_device text default 'unknown',
  p_app_version text default '',
  p_context jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_source text;
  v_module text;
  v_severity text;
  v_message text;
  v_detail text;
  v_route text;
  v_device text;
  v_version text;
  v_context jsonb;
  v_fingerprint text;
  v_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  v_source := case lower(coalesce(p_source, ''))
    when 'desktop' then 'desktop'
    when 'mobile' then 'mobile'
    when 'manual' then 'manual'
    when 'health' then 'health'
    when 'automation' then 'automation'
    else 'frontend'
  end;
  v_module := left(regexp_replace(coalesce(nullif(trim(p_module), ''), 'general'), '[^a-zA-Z0-9_./ -]', '', 'g'), 80);
  v_severity := case lower(coalesce(p_severity, ''))
    when 'info' then 'info'
    when 'warning' then 'warning'
    when 'critical' then 'critical'
    else 'error'
  end;
  v_message := left(coalesce(nullif(trim(p_message), ''), 'Error desconocido'), 500);
  v_detail := left(coalesce(p_detail, ''), 1000);
  v_route := left(split_part(coalesce(p_route, ''), '?', 1), 180);
  v_device := left(regexp_replace(coalesce(nullif(trim(p_device), ''), 'unknown'), '[^a-zA-Z0-9_./ -]', '', 'g'), 60);
  v_version := left(regexp_replace(coalesce(p_app_version, ''), '[^a-zA-Z0-9_.-]', '', 'g'), 80);

  v_message := regexp_replace(v_message, '([?&](token|key|code|password|secret|access_token|refresh_token)=)[^&#[:space:]]+', '\1[REDACTADO]', 'gi');
  v_detail := regexp_replace(v_detail, '([?&](token|key|code|password|secret|access_token|refresh_token)=)[^&#[:space:]]+', '\1[REDACTADO]', 'gi');
  v_detail := regexp_replace(v_detail, '(authorization[[:space:]]*:[[:space:]]*bearer[[:space:]]+)[^[:space:]]+', '\1[REDACTADO]', 'gi');

  v_context := jsonb_strip_nulls(jsonb_build_object(
    'platform', left(coalesce(p_context ->> 'platform', ''), 80),
    'viewport', left(coalesce(p_context ->> 'viewport', ''), 40),
    'online', case when p_context ? 'online' then (p_context -> 'online') else null end,
    'action', left(coalesce(p_context ->> 'action', ''), 100),
    'http_status', case when (p_context ->> 'http_status') ~ '^[0-9]{3}$' then (p_context -> 'http_status') else null end
  ));
  v_fingerprint := md5(concat_ws('|', v_source, lower(v_module), v_severity, lower(v_message), lower(v_route)));

  insert into public.crm_system_events (
    fingerprint, source, module, severity, message, detail, route, device,
    app_version, reporter_id, context
  ) values (
    v_fingerprint, v_source, v_module, v_severity, v_message, v_detail, v_route,
    v_device, v_version, auth.uid(), v_context
  )
  on conflict (fingerprint) where status = 'active'
  do update set
    last_seen_at = now(),
    occurrences = public.crm_system_events.occurrences + 1,
    detail = excluded.detail,
    device = excluded.device,
    app_version = excluded.app_version,
    reporter_id = excluded.reporter_id,
    context = excluded.context,
    severity = case
      when public.crm_system_events.severity = 'critical' or excluded.severity = 'critical' then 'critical'
      when public.crm_system_events.severity = 'error' or excluded.severity = 'error' then 'error'
      when public.crm_system_events.severity = 'warning' or excluded.severity = 'warning' then 'warning'
      else 'info'
    end
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.crm_report_system_event(
  p_source text,
  p_module text,
  p_severity text,
  p_message text,
  p_detail text default '',
  p_route text default '',
  p_device text default 'unknown',
  p_app_version text default '',
  p_context jsonb default '{}'::jsonb
)
returns bigint
language sql
set search_path = private, public, pg_temp
as $$
  select private.crm_report_system_event_impl(
    p_source, p_module, p_severity, p_message, p_detail, p_route,
    p_device, p_app_version, p_context
  );
$$;

create or replace function private.crm_list_system_events_impl(
  p_days integer default 7,
  p_limit integer default 250,
  p_status text default 'all',
  p_search text default ''
)
returns table (
  id bigint,
  source text,
  module text,
  severity text,
  status text,
  message text,
  detail text,
  route text,
  device text,
  app_version text,
  occurrences integer,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  resolved_at timestamptz,
  reporter_name text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.current_user_is_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  return query
  select e.id, e.source, e.module, e.severity, e.status, e.message, e.detail,
    e.route, e.device, e.app_version, e.occurrences, e.first_seen_at,
    e.last_seen_at, e.resolved_at, coalesce(up.display_name, 'Usuario')
  from public.crm_system_events e
  left join public.user_permissions up on up.user_id = e.reporter_id
  where (coalesce(p_days, 7) <= 0 or e.last_seen_at >= now() - make_interval(days => least(greatest(p_days, 1), 365)))
    and (coalesce(p_status, 'all') = 'all' or e.status = p_status)
    and (
      coalesce(trim(p_search), '') = ''
      or concat_ws(' ', e.source, e.module, e.message, e.detail, e.route, e.device) ilike '%' || left(trim(p_search), 100) || '%'
    )
  order by
    case e.severity when 'critical' then 0 when 'error' then 1 when 'warning' then 2 else 3 end,
    case e.status when 'active' then 0 else 1 end,
    e.last_seen_at desc
  limit least(greatest(coalesce(p_limit, 250), 1), 500);
end;
$$;

create or replace function public.crm_list_system_events(
  p_days integer default 7,
  p_limit integer default 250,
  p_status text default 'all',
  p_search text default ''
)
returns table (
  id bigint,
  source text,
  module text,
  severity text,
  status text,
  message text,
  detail text,
  route text,
  device text,
  app_version text,
  occurrences integer,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  resolved_at timestamptz,
  reporter_name text
)
language sql
set search_path = private, public, pg_temp
as $$
  select * from private.crm_list_system_events_impl(p_days, p_limit, p_status, p_search);
$$;

create or replace function private.crm_set_system_event_status_impl(p_id bigint, p_status text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.current_user_is_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if p_status not in ('active', 'resolved', 'ignored') then
    raise exception 'Invalid status';
  end if;

  update public.crm_system_events
  set status = p_status,
      resolved_at = case when p_status = 'active' then null else now() end,
      resolved_by = case when p_status = 'active' then null else auth.uid() end
  where id = p_id;
  return found;
end;
$$;

create or replace function public.crm_set_system_event_status(p_id bigint, p_status text)
returns boolean
language sql
set search_path = private, public, pg_temp
as $$ select private.crm_set_system_event_status_impl(p_id, p_status); $$;

create or replace function private.crm_cleanup_system_events_impl(p_older_than_days integer default 30)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_count integer;
  v_days integer := least(greatest(coalesce(p_older_than_days, 30), 7), 365);
begin
  if not public.current_user_is_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  delete from public.crm_system_events
  where status in ('resolved', 'ignored')
    and last_seen_at < now() - make_interval(days => v_days);
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.crm_cleanup_system_events(p_older_than_days integer default 30)
returns integer
language sql
set search_path = private, public, pg_temp
as $$ select private.crm_cleanup_system_events_impl(p_older_than_days); $$;

create or replace function private.crm_system_health_snapshot_impl()
returns jsonb
language plpgsql
security definer
set search_path = public, cron, pg_temp
as $$
declare
  v_cron_active integer := 0;
  v_cron_latest_failed integer := 0;
  v_cron_stalled integer := 0;
  v_cron_failed_24h integer := 0;
  v_auto_stuck integer := 0;
  v_auto_failed_24h integer := 0;
  v_wa_overdue integer := 0;
  v_wa_failed_24h integer := 0;
  v_agenda_overdue integer := 0;
  v_agenda_failed_24h integer := 0;
  v_events_active integer := 0;
  v_events_critical integer := 0;
begin
  if not public.current_user_is_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  select count(*) into v_cron_active from cron.job where active is true;
  select count(*) into v_cron_latest_failed
  from cron.job j
  left join lateral (
    select d.status from cron.job_run_details d where d.jobid = j.jobid order by d.start_time desc limit 1
  ) latest on true
  where j.active is true and coalesce(latest.status, 'missing') <> 'succeeded';
  select count(*) into v_cron_stalled
  from cron.job_run_details
  where status = 'running' and start_time < now() - interval '10 minutes';
  select count(*) into v_cron_failed_24h
  from cron.job_run_details
  where start_time >= now() - interval '24 hours' and status not in ('succeeded', 'running');

  select count(*) into v_auto_stuck
  from public.crm_server_automation_jobs
  where (status = 'pending' and run_at < now() - interval '10 minutes')
     or (status = 'running' and updated_at < now() - interval '10 minutes');
  select count(*) into v_auto_failed_24h
  from public.crm_server_automation_jobs
  where status in ('failed', 'error') and updated_at >= now() - interval '24 hours';

  select count(*) into v_wa_overdue
  from public.whatsapp_jobs
  where status in ('pending', 'queued', 'scheduled') and scheduled_for < now() - interval '5 minutes';
  select count(*) into v_wa_failed_24h
  from public.whatsapp_jobs
  where status in ('failed', 'error') and updated_at >= now() - interval '24 hours';
  select count(*) into v_agenda_overdue
  from public.agenda_items
  where whatsapp_enabled is true
    and status = 'pending'
    and coalesce(whatsapp_delivery_status, 'pending') in ('pending', 'queued', 'scheduled')
    and coalesce(whatsapp_scheduled_at, starts_at) < now() - interval '5 minutes';
  select count(*) into v_agenda_failed_24h
  from public.agenda_items
  where whatsapp_enabled is true
    and coalesce(whatsapp_delivery_status, '') in ('failed', 'error')
    and updated_at >= now() - interval '24 hours';

  select count(*), count(*) filter (where severity = 'critical')
    into v_events_active, v_events_critical
  from public.crm_system_events where status = 'active';

  return jsonb_build_object(
    'checked_at', now(),
    'cron', jsonb_build_object(
      'active', v_cron_active,
      'latest_failed', v_cron_latest_failed,
      'stalled', v_cron_stalled,
      'failed_24h', v_cron_failed_24h
    ),
    'automations', jsonb_build_object('stuck', v_auto_stuck, 'failed_24h', v_auto_failed_24h),
    'whatsapp', jsonb_build_object(
      'overdue_jobs', v_wa_overdue,
      'failed_jobs_24h', v_wa_failed_24h,
      'overdue_agenda', v_agenda_overdue,
      'failed_agenda_24h', v_agenda_failed_24h
    ),
    'incidents', jsonb_build_object('active', v_events_active, 'critical', v_events_critical)
  );
end;
$$;

create or replace function public.crm_system_health_snapshot()
returns jsonb
language sql
set search_path = private, public, pg_temp
as $$ select private.crm_system_health_snapshot_impl(); $$;

revoke all on function private.crm_report_system_event_impl(text,text,text,text,text,text,text,text,jsonb) from public;
revoke all on function private.crm_list_system_events_impl(integer,integer,text,text) from public;
revoke all on function private.crm_set_system_event_status_impl(bigint,text) from public;
revoke all on function private.crm_cleanup_system_events_impl(integer) from public;
revoke all on function private.crm_system_health_snapshot_impl() from public;

revoke all on function public.crm_report_system_event(text,text,text,text,text,text,text,text,jsonb) from public, anon;
revoke all on function public.crm_list_system_events(integer,integer,text,text) from public, anon;
revoke all on function public.crm_set_system_event_status(bigint,text) from public, anon;
revoke all on function public.crm_cleanup_system_events(integer) from public, anon;
revoke all on function public.crm_system_health_snapshot() from public, anon;

grant execute on function public.crm_report_system_event(text,text,text,text,text,text,text,text,jsonb) to authenticated;
grant execute on function public.crm_list_system_events(integer,integer,text,text) to authenticated;
grant execute on function public.crm_set_system_event_status(bigint,text) to authenticated;
grant execute on function public.crm_cleanup_system_events(integer) to authenticated;
grant execute on function public.crm_system_health_snapshot() to authenticated;

comment on table public.crm_system_events is 'Registro técnico central del CRM; no almacena cuerpos de peticiones ni datos comerciales.';
comment on function public.crm_cleanup_system_events(integer) is 'Elimina solo incidencias resueltas o ignoradas antiguas; nunca datos comerciales.';
