-- Durable business events for the Offers and Follow-ups Telegram topics.
-- Database triggers preserve short-lived transitions even when the CRM is closed.

create table if not exists public.crm_telegram_business_events (
  id bigint generated by default as identity primary key,
  topic text not null check (topic in ('offers','followups')),
  event_type text not null,
  entity_type text not null check (entity_type in ('offer','opportunity')),
  entity_id uuid not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists crm_telegram_business_events_created_idx
  on public.crm_telegram_business_events(created_at,id);

alter table public.crm_telegram_business_events enable row level security;
revoke all on public.crm_telegram_business_events from public,anon,authenticated;
grant all on public.crm_telegram_business_events to service_role;
grant usage,select on sequence public.crm_telegram_business_events_id_seq to service_role;

create or replace function crm_private.telegram_offer_event()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  previous_status text:=case when tg_op='UPDATE' then old.status else null end;
  previous_sent_at timestamptz:=case when tg_op='UPDATE' then old.sent_at else null end;
  event_name text;
  event_topic text;
  opportunity public.sales_opportunities%rowtype;
  stage_name text;
begin
  select * into opportunity from public.sales_opportunities where id=new.opportunity_id;
  select name into stage_name from public.sales_stages where id=opportunity.stage_id;

  if new.sent_at is not null and previous_sent_at is null then
    event_name:='offer_sent';
    event_topic:='offers';
  elsif tg_op='UPDATE' and previous_status='paused' and new.status='following' then
    event_name:='followup_resumed';
    event_topic:='followups';
  elsif (tg_op='INSERT' or previous_status is distinct from new.status) and new.status='paused' then
    event_name:='followup_paused';
    event_topic:='followups';
  elsif (tg_op='INSERT' or previous_status is distinct from new.status) and new.status='accepted' then
    event_name:='offer_accepted';
    event_topic:='offers';
  elsif (tg_op='INSERT' or previous_status is distinct from new.status) and new.status='processed' then
    event_name:='sale_processed';
    event_topic:='offers';
  elsif (tg_op='INSERT' or previous_status is distinct from new.status) and new.status='won' then
    event_name:='sale_won';
    event_topic:='offers';
  elsif (tg_op='INSERT' or previous_status is distinct from new.status) and new.status='lost' then
    event_name:='sale_lost';
    event_topic:='offers';
  elsif (tg_op='INSERT' or previous_status is distinct from new.status) and new.status='cancelled' then
    event_name:='offer_cancelled';
    event_topic:='offers';
  else
    return new;
  end if;

  insert into public.crm_telegram_business_events(topic,event_type,entity_type,entity_id,payload)
  values(event_topic,event_name,'offer',new.id,jsonb_build_object(
    'client_name',coalesce(opportunity.client_name,''),
    'phone',coalesce(opportunity.phone,''),
    'operator',coalesce(new.operator,''),
    'offer_name',coalesce(new.offer_name,''),
    'total_price',new.total_price,
    'stage_name',coalesce(stage_name,''),
    'status',coalesce(new.status,'')
  ));
  return new;
end $$;

revoke all on function crm_private.telegram_offer_event() from public,anon,authenticated;
drop trigger if exists crm_telegram_offer_event on public.crm_offer_instances;
create trigger crm_telegram_offer_event
after insert or update of status,sent_at on public.crm_offer_instances
for each row execute function crm_private.telegram_offer_event();

create or replace function crm_private.telegram_opportunity_event()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  stage_name text;
  event_name text;
begin
  if exists(select 1 from public.crm_offer_instances where opportunity_id=new.id) then return new;end if;

  if old.status is distinct from new.status and new.status in ('won','lost','cancelled') then
    event_name:=case new.status when 'won' then 'sale_won' when 'lost' then 'sale_lost' else 'offer_cancelled' end;
  elsif old.stage_id is distinct from new.stage_id then
    select lower(btrim(name)) into stage_name from public.sales_stages where id=new.stage_id;
    event_name:=case stage_name when 'tramitado' then 'sale_processed' when 'ganado' then 'sale_won' when 'perdido' then 'sale_lost' else null end;
  end if;
  if event_name is null then return new;end if;

  insert into public.crm_telegram_business_events(topic,event_type,entity_type,entity_id,payload)
  values('offers',event_name,'opportunity',new.id,jsonb_build_object(
    'client_name',coalesce(new.client_name,''),
    'phone',coalesce(new.phone,''),
    'offer_name',coalesce(new.title,''),
    'total_price',new.amount,
    'stage_name',coalesce(stage_name,''),
    'status',coalesce(new.status,'')
  ));
  return new;
end $$;

revoke all on function crm_private.telegram_opportunity_event() from public,anon,authenticated;
drop trigger if exists crm_telegram_opportunity_event on public.sales_opportunities;
create trigger crm_telegram_opportunity_event
after update of stage_id,status on public.sales_opportunities
for each row when (old.stage_id is distinct from new.stage_id or old.status is distinct from new.status)
execute function crm_private.telegram_opportunity_event();

comment on table public.crm_telegram_business_events is
  'Durable queue of important offer, sale and follow-up transitions for Telegram delivery.';
