(function(){
  'use strict';
  const M=window.TPFModules;if(!M)return;
  function installSalesSafeUi(){if(document.getElementById('tpfSalesSafeUi'))return;const s=document.createElement('style');s.id='tpfSalesSafeUi';s.textContent=`
#view-sales #salesScrollLeft,#view-sales #salesScrollRight{display:none!important}#view-sales .salesBoardViewport{padding-left:8px!important;padding-right:8px!important}#view-sales .salesNavWrap{display:block!important}#view-sales #salesScroll{width:100%!important;max-width:100%!important}#view-sales #salesBoard.board{grid-auto-columns:245px!important;gap:10px!important;min-width:max-content!important;width:max-content!important}#view-sales #salesBoard>.stage{width:245px!important;min-width:245px!important;max-width:245px!important}#view-sales .opp{min-height:0!important;max-height:none!important;overflow:visible!important}
.tpfOppMenu,.tpfStageMenu{position:fixed;z-index:26000;width:220px;padding:6px;background:#fff;border:1px solid #dfe5ec;border-radius:10px;box-shadow:0 14px 38px rgba(20,35,55,.20)}.tpfOppMenu button,.tpfStageMenu button{display:block;width:100%;border:0;background:#fff;text-align:left;padding:9px 10px;border-radius:7px;color:#26364a;font-size:12px;font-weight:650}.tpfOppMenu button:hover,.tpfStageMenu button:hover{background:#f3f6fa}.tpfDanger{color:#b42318!important;border-top:1px solid #edf0f4!important;border-radius:0!important;margin-top:4px!important;padding-top:10px!important}`;document.head.appendChild(s)}
  function closeMenus(){document.querySelectorAll('.tpfOppMenu,.tpfStageMenu').forEach(x=>x.remove())}function getOpp(id){try{return (salesCache?.opportunities||[]).find(x=>String(x.id)===String(id))||null}catch(_){return null}}function getStages(){try{return salesCache?.stages||[]}catch(_){return []}}function menuPos(m,el){const r=el.getBoundingClientRect(),w=220;m.style.left=Math.max(8,Math.min(innerWidth-w-8,r.right-w))+'px';m.style.top=Math.max(8,Math.min(innerHeight-m.offsetHeight-8,r.bottom+4))+'px'}
  function openDirectWhatsapp(o){const p=String(o?.phone||'').trim();if(!p)return alert('Esta oportunidad no tiene teléfono.');if(typeof openWaQuick==='function')return openWaQuick({phone:p,name:String(o?.client_name||'').trim(),message:''});if(document.getElementById('waQuickPhone'))document.getElementById('waQuickPhone').value=p;document.getElementById('waQuickModal')?.classList.remove('hidden')}
  function openOppActions(ev,id){ev.preventDefault();ev.stopPropagation();closeMenus();const o=getOpp(id),m=document.createElement('div');m.className='tpfOppMenu';const add=(l,f,c='')=>{const b=document.createElement('button');b.textContent=l;b.className=c;b.onclick=e=>{e.stopPropagation();closeMenus();f()};m.appendChild(b)};add('Abrir ficha',()=>window.openOpportunityCard?.(id));add('Editar oportunidad',()=>window.openOpportunityCard?.(id));add('Mover a otra columna',()=>{const sel=document.querySelector(`.opp[data-opp-id="${CSS.escape(String(id))}"] .oppFooter select`);if(sel){sel.focus();sel.click()}});add('Crear tarea / recordatorio',()=>{try{window.createAgendaFromRecord?.(JSON.stringify({id:'',name:o?.client_name||'',phone:o?.phone||''}))}catch(_){document.querySelector('.nav[data-view="agenda"]')?.click()}});add('Abrir WhatsApp',()=>openDirectWhatsapp(o));add('Programar WhatsApp',()=>{if(document.getElementById('waQuickPhone'))document.getElementById('waQuickPhone').value=String(o?.phone||'');document.getElementById('waScheduleBtn')?.click()});add('Eliminar oportunidad',()=>window.deleteOpp?.(id),'tpfDanger');document.body.appendChild(m);menuPos(m,ev.currentTarget)}
  async function moveStage(id,dir){const rows=[...getStages()],i=rows.findIndex(x=>String(x.id)===String(id)),j=i+dir;if(i<0||j<0||j>=rows.length)return;const a=rows[i],b=rows[j],pa=Number(a.position??i),pb=Number(b.position??j);const r1=await sb.from('sales_stages').update({position:pb}).eq('id',a.id);if(r1.error)return alert(r1.error.message);const r2=await sb.from('sales_stages').update({position:pa}).eq('id',b.id);if(r2.error)return alert(r2.error.message);await loadSales()}async function renameStage(id){const s=getStages().find(x=>String(x.id)===String(id));if(!s)return;const name=prompt('Nombre de la columna',s.name||'');if(!name||name.trim()===String(s.name||'').trim())return;const {error}=await sb.from('sales_stages').update({name:name.trim()}).eq('id',id);if(error)return alert(error.message);await loadSales()}async function deleteStageSafe(id){const s=getStages().find(x=>String(x.id)===String(id));if(!s)return;const count=(salesCache?.opportunities||[]).filter(o=>String(o.stage_id)===String(id)).length;if(count){alert(`No se puede eliminar "${s.name}" porque contiene ${count} oportunidad${count===1?'':'es'}. Muévelas primero a otra columna.`);return}if(!confirm(`¿Eliminar la columna "${s.name}"?`))return;const {error}=await sb.from('sales_stages').delete().eq('id',id);if(error)return alert(error.message);await loadSales()}function newOppInThisStage(id){if(typeof window.newOppInStage==='function')return window.newOppInStage(id);document.querySelector(`.stage[data-stage="${CSS.escape(String(id))}"]`)?.querySelector('button.secondary')?.click()}function newStage(){document.getElementById('newStage')?.click()}
  function openStageActions(ev,id){ev.preventDefault();ev.stopPropagation();closeMenus();const stages=getStages(),i=stages.findIndex(x=>String(x.id)===String(id)),m=document.createElement('div');m.className='tpfStageMenu';const add=(l,f,c='',disabled=false)=>{const b=document.createElement('button');b.textContent=l;b.className=c;b.disabled=disabled;b.style.opacity=disabled?'.4':'1';b.onclick=e=>{e.stopPropagation();if(disabled)return;closeMenus();f()};m.appendChild(b)};add('Nueva oportunidad',()=>newOppInThisStage(id));add('Renombrar columna',()=>renameStage(id));add('Nueva columna',()=>newStage());add('Mover a la izquierda',()=>moveStage(id,-1),'',i<=0);add('Mover a la derecha',()=>moveStage(id,1),'',i<0||i>=stages.length-1);add('Eliminar columna',()=>deleteStageSafe(id),'tpfDanger');document.body.appendChild(m);menuPos(m,ev.currentTarget)}
  function bindMenus(){document.querySelectorAll('#salesBoard .oppMenu').forEach(b=>{if(b.dataset.tpfActions==='1')return;const id=b.closest('.opp')?.dataset?.oppId;if(!id)return;b.dataset.tpfActions='1';b.onclick=e=>openOppActions(e,id);b.title='Acciones de la oportunidad'});document.querySelectorAll('#salesBoard .stageMenu').forEach(b=>{if(b.dataset.tpfStageActions==='1')return;const id=b.closest('.stage')?.dataset?.stage;if(!id)return;b.dataset.tpfStageActions='1';b.onclick=e=>openStageActions(e,id);b.title='Opciones de la columna'})}
  M.register('contacts-sales',{install(){installSalesSafeUi();bindMenus();document.addEventListener('click',e=>{if(!e.target.closest('.tpfOppMenu,.tpfStageMenu,.oppMenu,.stageMenu'))closeMenus()});const board=document.getElementById('salesBoard');if(board)new MutationObserver(bindMenus).observe(board,{childList:true,subtree:true});M.wrapGlobals('contacts-sales',['loadSales','renderSales','renderSalesList','openOpportunityFull','openOpportunityCard','deleteOpp','moveSelectedSalesOpportunities','deleteSelectedSalesOpportunities','loadDatabase','renderDatabase','saveContact','deleteContact'])}});
})();
