(function(){
'use strict';
const M=window.TPFModules;if(!M)return;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let templates=[],mailboxes=[];

function ensureStyles(){if($('tpfMailStyles'))return;const s=document.createElement('style');s.id='tpfMailStyles';s.textContent=`
#view-email{padding:0}.tpfMailHead{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:14px}.tpfMailHead h2{margin:0}.tpfMailAccount{display:flex;align-items:center;gap:10px;padding:10px 12px;border:1px solid #dfe6ef;border-radius:12px;background:#fff}.tpfMailDot{width:9px;height:9px;border-radius:50%;background:#98a2b3}.tpfMailDot.on{background:#12b76a}.tpfMailLayout{display:grid;grid-template-columns:210px 330px 1fr;min-height:610px;border:1px solid #e3e8ef;border-radius:14px;overflow:hidden;background:#fff}.tpfMailFolders,.tpfMailList,.tpfMailReader{padding:14px}.tpfMailFolders,.tpfMailList{border-right:1px solid #e8edf3}.tpfMailFolder{display:block;width:100%;text-align:left;padding:9px 10px;border:0;background:transparent;border-radius:8px;margin-bottom:3px}.tpfMailFolder.active{background:#eef4ff;color:#175cd3;font-weight:700}.tpfMailEmpty{padding:36px 14px;text-align:center;color:#667085}.tpfMailToolbar{display:flex;gap:8px;align-items:center;margin-bottom:12px}.tpfTemplateGrid{display:grid;grid-template-columns:330px 1fr;gap:14px}.tpfTemplateList{border:1px solid #e3e8ef;border-radius:12px;overflow:hidden}.tpfTemplateRow{padding:11px 12px;border-bottom:1px solid #edf1f5;cursor:pointer}.tpfTemplateRow:last-child{border-bottom:0}.tpfTemplateRow:hover{background:#f8fafc}.tpfTemplateEditor{border:1px solid #e3e8ef;border-radius:12px;padding:14px}.tpfTemplateEditor label{display:block;font-size:11px;font-weight:700;margin:0 0 10px}.tpfTemplateEditor input,.tpfTemplateEditor textarea{width:100%;margin-top:5px}.tpfTemplateEditor textarea{min-height:220px}.tpfMailTabs{display:flex;gap:7px;margin:0 0 12px}.tpfMailTabs button.active{background:#eef4ff;color:#175cd3;border-color:#b2ccff}@media(max-width:1000px){.tpfMailLayout{grid-template-columns:170px 1fr}.tpfMailReader{display:none}.tpfTemplateGrid{grid-template-columns:1fr}}`;
document.head.appendChild(s)}

function ensureNav(){if(document.querySelector('.nav[data-view="email"]'))return;const nav=document.querySelector('.referenceNav');if(!nav)return;const el=document.createElement('div');el.className='nav secondaryNav';el.dataset.view='email';el.innerHTML='<b>✉</b><span>Correo</span>';const anchor=document.querySelector('.nav[data-view="labels"]');nav.insertBefore(el,anchor||null);el.addEventListener('click',e=>{e.preventDefault();openMailView();});}

function ensureView(){if($('view-email'))return;const main=document.querySelector('.referenceWorkspace main');if(!main)return;const v=document.createElement('section');v.id='view-email';v.className='hidden';v.innerHTML=`
<div class="tpfMailHead"><div><span class="eyebrow">MICROSOFT 365</span><h2>Correo</h2><p class="small">Correo empresarial integrado sin cargar todo el buzón en el CRM.</p></div><div class="tpfMailAccount"><span id="tpfMailDot" class="tpfMailDot"></span><div><b id="tpfMailAccountName">Microsoft 365 no conectado</b><div id="tpfMailAccountSub" class="small">Conecta tu cuenta empresarial</div></div><button id="tpfMailConnect" class="primary" type="button">Conectar Microsoft 365</button></div></div>
<div class="tpfMailTabs"><button class="secondary active" data-mail-tab="mail">Correo</button><button class="secondary" data-mail-tab="templates">Plantillas de correo</button></div>
<div id="tpfMailTabMail" class="tpfMailLayout"><aside class="tpfMailFolders"><button class="primary" id="tpfMailCompose" style="width:100%;margin-bottom:12px">✎ Redactar</button><button class="tpfMailFolder active">Bandeja de entrada</button><button class="tpfMailFolder">Enviados</button><button class="tpfMailFolder">Borradores</button><button class="tpfMailFolder">Archivados</button><button class="tpfMailFolder">Papelera</button><hr><div class="small">Carga ligera: 20 correos por página. Adjuntos solo al abrirlos.</div></aside><div class="tpfMailList"><div class="tpfMailToolbar"><input id="tpfMailSearch" placeholder="Buscar correos..."><button id="tpfMailRefresh" class="secondary">↻</button></div><div id="tpfMailMessages" class="tpfMailEmpty">Conecta Microsoft 365 para mostrar tus últimos correos.</div></div><div class="tpfMailReader"><div id="tpfMailReaderBody" class="tpfMailEmpty">Selecciona un correo para leerlo.</div></div></div>
<div id="tpfMailTabTemplates" class="hidden"><div class="tpfTemplateGrid"><div><div class="tpfMailToolbar"><button id="tpfTemplateNew" class="primary">+ Nueva plantilla de correo</button></div><div id="tpfTemplateList" class="tpfTemplateList"></div></div><div class="tpfTemplateEditor"><input id="tpfTemplateId" type="hidden"><label>Nombre de la plantilla<input id="tpfTemplateName" placeholder="Ej.: Seguimiento de oferta"></label><label>Asunto<input id="tpfTemplateSubject" placeholder="Ej.: Hola {nombre}, sobre tu oferta"></label><label>Contenido<textarea id="tpfTemplateBody" placeholder="Hola {nombre}, ..."></textarea></label><div class="small" style="margin-bottom:10px">Variables: {nombre}, {dni}, {telefono}, {email}.</div><button id="tpfTemplateSave" class="primary">Guardar plantilla</button> <button id="tpfTemplateDelete" class="danger hidden">Eliminar</button><span id="tpfTemplateMsg" class="small"></span></div></div>`;main.appendChild(v);
$('tpfMailConnect').onclick=()=>{window.location.href='/api/m365-auth?returnTo='+encodeURIComponent(location.pathname+location.search)};
$('tpfMailRefresh').onclick=loadMailboxState;$('tpfMailCompose').onclick=()=>alert(mailboxes.some(x=>x.connected)?'Redacción disponible al completar la conexión Microsoft 365.':'Primero conecta Microsoft 365.');
document.querySelectorAll('[data-mail-tab]').forEach(b=>b.onclick=()=>selectTab(b.dataset.mailTab));
$('tpfTemplateNew').onclick=()=>editTemplate(null);$('tpfTemplateSave').onclick=saveTemplate;$('tpfTemplateDelete').onclick=deleteTemplate;
}

function openMailView(){document.querySelectorAll('.referenceWorkspace main > section').forEach(s=>s.classList.add('hidden'));$('view-email')?.classList.remove('hidden');document.querySelectorAll('.referenceNav .nav').forEach(n=>n.classList.remove('active'));document.querySelector('.nav[data-view="email"]')?.classList.add('active');loadAll();}
function selectTab(tab){document.querySelectorAll('[data-mail-tab]').forEach(b=>b.classList.toggle('active',b.dataset.mailTab===tab));$('tpfMailTabMail').classList.toggle('hidden',tab!=='mail');$('tpfMailTabTemplates').classList.toggle('hidden',tab!=='templates');if(tab==='templates')loadTemplates();}
async function loadMailboxState(){try{const {data,error}=await sb.from('microsoft_mailboxes').select('id,email,display_name,connected,last_sync_at').order('created_at',{ascending:false});if(error)throw error;mailboxes=data||[]}catch(_){mailboxes=[]}const connected=mailboxes.find(x=>x.connected);$('tpfMailDot')?.classList.toggle('on',!!connected);if(connected){$('tpfMailAccountName').textContent=connected.display_name||connected.email;$('tpfMailAccountSub').textContent=connected.email;$('tpfMailConnect').textContent='Cuenta conectada';$('tpfMailConnect').className='secondary';}else{$('tpfMailAccountName').textContent='Microsoft 365 no conectado';$('tpfMailAccountSub').textContent='Conecta tu cuenta empresarial';$('tpfMailConnect').textContent='Conectar Microsoft 365';$('tpfMailConnect').className='primary';}}
async function loadTemplates(){try{const {data,error}=await sb.from('email_templates').select('*').eq('active',true).order('name');if(error)throw error;templates=data||[]}catch(_){templates=[]}const box=$('tpfTemplateList');if(!box)return;box.innerHTML=templates.length?templates.map(t=>`<div class="tpfTemplateRow" data-email-template-id="${t.id}"><b>${esc(t.name)}</b><div class="small">${esc(t.subject)}</div></div>`).join(''):'<div class="tpfMailEmpty">Todavía no hay plantillas de correo.</div>';box.querySelectorAll('[data-email-template-id]').forEach(r=>r.onclick=()=>editTemplate(templates.find(x=>x.id===r.dataset.emailTemplateId)));window.TPFEmailOptions={templates,mailboxes};enhanceAutomationBuilder();}
function editTemplate(t){$('tpfTemplateId').value=t?.id||'';$('tpfTemplateName').value=t?.name||'';$('tpfTemplateSubject').value=t?.subject||'';$('tpfTemplateBody').value=t?.body_html||'';$('tpfTemplateDelete').classList.toggle('hidden',!t);$('tpfTemplateMsg').textContent='';}
async function saveTemplate(){const name=$('tpfTemplateName').value.trim(),subject=$('tpfTemplateSubject').value.trim(),body_html=$('tpfTemplateBody').value;if(!name){$('tpfTemplateMsg').textContent='Pon un nombre.';return}const id=$('tpfTemplateId').value;const payload={name,subject,body_html,active:true,updated_at:new Date().toISOString()};let q=id?sb.from('email_templates').update(payload).eq('id',id):sb.from('email_templates').insert(payload);const {error}=await q;if(error){$('tpfTemplateMsg').textContent=error.message;return}$('tpfTemplateMsg').textContent='Guardada ✓';await loadTemplates();editTemplate(null);}
async function deleteTemplate(){const id=$('tpfTemplateId').value;if(!id||!confirm('¿Eliminar esta plantilla de correo?'))return;const {error}=await sb.from('email_templates').update({active:false,updated_at:new Date().toISOString()}).eq('id',id);if(error){$('tpfTemplateMsg').textContent=error.message;return}await loadTemplates();editTemplate(null);}
async function loadAll(){await Promise.all([loadMailboxState(),loadTemplates()]);}

function optionHtml(items,value,label){return '<option value="">Elige…</option>'+items.map(x=>`<option value="${x.id}" ${String(value||'')===String(x.id)?'selected':''}>${esc(label(x))}</option>`).join('')}
function enhanceAutomationBuilder(){const builder=$('tpfFlowBuilder');if(!builder)return;const select=builder.querySelector('#tpfStepEditor select[data-key="action_type"]');if(select&&!select.querySelector('option[value="send_email_template"]')){const o=document.createElement('option');o.value='send_email_template';o.textContent='Enviar plantilla de correo';select.appendChild(o)}const selected=select?.value;if(selected!=='send_email_template')return;const cfg=builder.querySelector('#tpfStepEditor .tpfStepConfig');if(!cfg||cfg.querySelector('[data-tpf-email-config]'))return;const wrap=document.createElement('div');wrap.dataset.tpfEmailConfig='1';wrap.className='full';wrap.innerHTML=`<div class="tpfVarHelp">El correo se enviará desde la cuenta Microsoft 365 elegida. Puedes dispararlo con <b>Se asigna una etiqueta</b>.</div><label class="full">Cuenta remitente<select data-cfg="mailbox_id">${optionHtml(mailboxes.filter(x=>x.connected),'',x=>x.display_name||x.email)}</select></label><label class="full">Plantilla de correo<select data-cfg="email_template_id">${optionHtml(templates,'',x=>x.name)}</select></label>`;cfg.appendChild(wrap);}
function observeAutomations(){const obs=new MutationObserver(()=>enhanceAutomationBuilder());obs.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target?.closest?.('.nav[data-view="automations"]'))setTimeout(()=>{loadAll().then(enhanceAutomationBuilder)},250);});}
function install(){ensureStyles();ensureNav();ensureView();observeAutomations();loadAll();}
M.register('email-m365',{install});
})();