(function(){
'use strict';
const M=window.TPFModules;if(!M)return;const $=id=>document.getElementById(id),txt=v=>String(v||'').trim(),money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(v||0));
function norm(v){return txt(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function style(){if($('tpfMonthlyCloseStyle'))return;const s=document.createElement('style');s.id='tpfMonthlyCloseStyle';s.textContent='#tpfMonthlyClose{position:fixed;inset:0;z-index:100700;background:#10182899;display:grid;place-items:center;padding:18px}.tpfMonthlyCard{width:min(1120px,96vw);max-height:92vh;overflow:auto;background:#fff;border-radius:16px;box-shadow:0 24px 60px #0004}.tpfMonthlyHead,.tpfMonthlyFoot{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:18px 22px;border-bottom:1px solid #e4e7ec}.tpfMonthlyHead h2{margin:0}.tpfMonthlyBody{padding:18px 22px}.tpfMonthlyStats{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:16px}.tpfMonthlyStat{padding:12px 16px;border:1px solid #d9e2f1;border-radius:10px;background:#f8fbff}.tpfMonthlyStat b{display:block;font-size:20px}.tpfMonthlyTable{width:100%;border-collapse:collapse}.tpfMonthlyTable th,.tpfMonthlyTable td{padding:10px;border-bottom:1px solid #eaecf0;text-align:left}.tpfMonthlyTable th{font-size:12px;color:#475467}.tpfMonthlyPending{margin-top:22px}.tpfMonthlyPending summary{font-weight:800;cursor:pointer}.tpfMonthlyPending ul{margin:10px 0;padding-left:20px}.tpfMonthlyFoot{border-top:1px solid #e4e7ec;border-bottom:0;justify-content:flex-end}.tpfMonthlyFoot button,.tpfMonthlyHead button{border:1px solid #d0d5dd;border-radius:9px;background:#fff;padding:10px 13px;font-weight:700;cursor:pointer}.tpfMonthlyFoot .primary{background:#155eef;border-color:#155eef;color:#fff}.tpfMonthlyWarn{padding:10px 12px;background:#fffaeb;color:#7a2e0e;border-radius:9px;margin-top:13px;font-size:13px}@media(max-width:680px){.tpfMonthlyTable th:nth-child(3),.tpfMonthlyTable td:nth-child(3){display:none}.tpfMonthlyHead,.tpfMonthlyBody,.tpfMonthlyFoot{padding-left:14px;padding-right:14px}}';document.head.appendChild(s)}
function data(){const stages=window.salesCache?.stages||[],opps=window.salesCache?.opportunities||[],stage=id=>stages.find(x=>String(x.id)===String(id)),tramitado=opps.filter(o=>norm(stage(o.stage_id)?.name)==='tramitado'),pending=opps.filter(o=>{const n=norm(stage(o.stage_id)?.name);return o.status!=='lost'&&n&&n!=='tramitado'&&n!=='ganado'&&n!=='perdido'&&n!=='archivo'});return{stages,tramitado,pending}}
function close(){document.querySelector('#tpfMonthlyClose')?.remove()}
function open(){style();close();const d=data(),total=d.tramitado.reduce((n,o)=>n+Number(o.amount||0),0),root=document.createElement('div');root.id='tpfMonthlyClose';root.innerHTML='<section class="tpfMonthlyCard" role="dialog" aria-modal="true"><header class="tpfMonthlyHead"><div><h2>Cierre de mes</h2><small>Revisa antes de pasar las tramitadas a Ganado.</small></div><button type="button" data-close>×</button></header><div class="tpfMonthlyBody"><div class="tpfMonthlyStats"><div class="tpfMonthlyStat"><b>'+d.tramitado.length+'</b><small>en Tramitado</small></div><div class="tpfMonthlyStat"><b>'+money(total)+'</b><small>importe para cerrar</small></div><div class="tpfMonthlyStat"><b>'+d.pending.length+'</b><small>ofertas pendientes</small></div></div><table class="tpfMonthlyTable"><thead><tr><th><input id="tpfMonthlyAll" type="checkbox" checked></th><th>Cliente / oportunidad</th><th>Importe</th><th>Fecha prevista</th></tr></thead><tbody>'+d.tramitado.map(o=>'<tr><td><input type="checkbox" data-monthly-id="'+o.id+'" checked></td><td><b>'+txt(o.client_name||o.title||'Sin nombre')+'</b><br><small>'+txt(o.title||'')+'</small></td><td>'+money(o.amount)+'</td><td>'+txt(o.expected_date||'—')+'</td></tr>').join('')+(d.tramitado.length?'':'<tr><td colspan="4">No hay oportunidades en Tramitado para cerrar.</td></tr>')+'</tbody></table><details class="tpfMonthlyPending"><summary>Ofertas pendientes ('+d.pending.length+')</summary><ul>'+d.pending.map(o=>'<li><b>'+txt(o.client_name||o.title||'Sin nombre')+'</b> · '+txt(d.stages.find(s=>String(s.id)===String(o.stage_id))?.name||'')+' · '+money(o.amount)+'</li>').join('')+(d.pending.length?'':'<li>No hay ofertas pendientes.</li>')+'</ul></details><div class="tpfMonthlyWarn">Las ofertas pendientes solo se muestran: no se mueven. Las fechas previstas y las revisiones de 3 y 11 meses no se modifican.</div></div><footer class="tpfMonthlyFoot"><button type="button" data-close>Cancelar</button><button id="tpfMonthlySave" class="primary" type="button">Marcar seleccionadas como Ganado</button></footer></section>';document.body.appendChild(root);root.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);const all=$('tpfMonthlyAll');all.onchange=()=>root.querySelectorAll('[data-monthly-id]').forEach(x=>x.checked=all.checked);$('tpfMonthlySave').onclick=async()=>{const ids=[...root.querySelectorAll('[data-monthly-id]:checked')].map(x=>x.dataset.monthlyId);if(!ids.length)return alert('Selecciona al menos una oportunidad.');if(!confirm('Se moverán '+ids.length+' oportunidad(es) a Ganado. Las fechas y revisiones no cambiarán.'))return;const b=$('tpfMonthlySave');b.disabled=true;try{const r=await sb.rpc('crm_close_month_selected',{p_opportunity_ids:ids});if(r.error)throw r.error;await window.loadSales?.();close();alert((r.data?.moved||ids.length)+' oportunidades marcadas como Ganado.')}catch(e){alert(e?.message||'No se pudo cerrar el mes.')}finally{b.disabled=false}}}
function mount(){style();const anchor=$('newOpp');if(!anchor||$('tpfMonthlyCloseBtn'))return;const b=document.createElement('button');b.type='button';b.id='tpfMonthlyCloseBtn';b.className='secondary';b.textContent='Cierre de mes';b.onclick=open;anchor.after(b)}
M.register('monthly-close',{install(){mount();window.addEventListener('tpf:sales-updated',mount);setInterval(mount,1000)}});
})();
