/* Shared, confirmed follow-up scheduling for desktop and mobile. */
(function(){
'use strict';
async function choose(id,client=window.sb){
 if(document.getElementById('tpfResumeOffer'))return false;
 const r=await client.from('crm_offer_instances').select('id,updated_at,status').eq('id',id).single();if(r.error)throw r.error;
 if(r.data?.status!=='paused')throw Error('La oferta cambió. Actualiza antes de reanudar.');
 const d=document.createElement('dialog');d.id='tpfResumeOffer';d.setAttribute('aria-label','Reanudar seguimiento');
 d.style.cssText='width:min(480px,calc(100vw - 24px));box-sizing:border-box;max-height:calc(100dvh - 24px);overflow:auto;border:1px solid #cbd5e1;border-radius:14px;padding:20px;color:#24354b;background:white';
 d.innerHTML='<form><h3>Reanudar seguimiento</h3><label>Próximo WhatsApp<select name="mode" style="display:block;width:100%;padding:12px;margin:8px 0"><option value="now">Ahora, en la primera franja permitida</option><option value="days">En 2 días, a la hora guardada</option><option value="custom">Elegir fecha y hora</option></select></label><label data-custom hidden>Fecha y hora · Madrid<input name="at" type="datetime-local" style="display:block;width:100%;box-sizing:border-box;padding:12px"></label><p data-preview role="status">Calculando…</p><small>Respeta el horario del seguimiento y los fines de semana. Si comparte mensaje con otros servicios, se reanuda el grupo.</small><p data-error role="alert"></p><div style="display:flex;gap:10px;margin-top:16px"><button type="button" data-cancel>Cancelar</button><button type="submit" data-save disabled>Confirmar reanudación</button></div></form>';
 document.body.appendChild(d);const form=d.querySelector('form'),mode=form.elements.mode,at=form.elements.at,save=d.querySelector('[data-save]'),error=d.querySelector('[data-error]');let revision=0,valid=false,busy=false;
 const args=()=>({p_offer_id:id,p_mode:mode.value,p_local_at:mode.value==='custom'?at.value:null});
 const refresh=async()=>{const rev=++revision;valid=false;save.disabled=true;error.textContent='';d.querySelector('[data-custom]').hidden=mode.value!=='custom';at.required=mode.value==='custom';if(at.required&&!at.value){d.querySelector('[data-preview]').textContent='Elige la fecha y la hora.';return;}try{const {data,error}=await client.rpc('crm_offer_resume_preview',args());if(error)throw error;if(rev!==revision||!d.isConnected)return;if(!Number.isFinite(Date.parse(data?.send_at)))throw Error('No se pudo comprobar la fecha.');d.querySelector('[data-preview]').textContent='Próximo WhatsApp: '+new Date(data.send_at).toLocaleString('es-ES',{timeZone:'Europe/Madrid',dateStyle:'full',timeStyle:'short'})+'. Se enviará si el cliente no ha respondido.';valid=true;save.disabled=false;}catch(e){if(rev===revision)error.textContent=e.message||'No se pudo calcular el horario.'}};
 mode.onchange=refresh;at.onchange=refresh;
 return new Promise(resolve=>{d.onclose=()=>{const ok=d.returnValue==='saved';d.remove();resolve(ok);};d.querySelector('[data-cancel]').onclick=()=>{if(!busy)d.close('cancel');};d.addEventListener('cancel',e=>{if(busy)e.preventDefault();});form.onsubmit=async e=>{e.preventDefault();if(busy||!valid)return;busy=true;save.disabled=true;mode.disabled=true;at.disabled=true;try{const {data,error}=await client.rpc('crm_resume_offer_at',{...args(),p_expected_at:r.data.updated_at});if(error)throw error;if(data?.ok!==true)throw Error('No se confirmó la reanudación.');d.close('saved');window.dispatchEvent(new CustomEvent('tpf:sales-updated'));}catch(e){error.textContent=e.message||'No se pudo guardar';}finally{busy=false;if(d.isConnected){mode.disabled=false;at.disabled=false;save.disabled=!valid;}}};d.showModal();void refresh();});
}
window.TPFOfferResume={choose};
})();
