(function(){
'use strict';
if(window.TPFModules&&window.TPFModules.version>=2)return;
const states=new Map(),errs=[];
function emit(name,state,detail=''){const x={name,state,detail:String(detail||''),at:new Date().toISOString()};states.set(name,x);try{window.dispatchEvent(new CustomEvent('tpf:module-status',{detail:x}))}catch(_){}return x}
function report(name,e,c=''){console.error('[TPF:'+name+']',c,e);const item={module:name,error:String(e?.message||e||'Error'),context:String(c||''),at:new Date().toISOString()};errs.push(item);if(errs.length>100)errs.shift();try{window.dispatchEvent(new CustomEvent('tpf:module-error',{detail:item}))}catch(_){}return emit(name,'error',item.error)}
function register(name,d={}){emit(name,'loading');try{const result=d.install?.(api);if(result&&typeof result.then==='function')return Promise.resolve(result).then(()=>emit(name,'ready'),e=>report(name,e,'install'));return emit(name,'ready')}catch(e){return report(name,e,'install')}}
function guard(name,fn){if(typeof fn!=='function')return fn;function guarded(...a){try{const value=fn.apply(this,a);if(value&&typeof value.then==='function')return Promise.resolve(value).catch(e=>{report(name,e);throw e});return value}catch(e){report(name,e);throw e}}return guarded}
function wrapGlobals(name,names=[]){const wrapped=[];for(const key of names){const fn=window[key];if(typeof fn!=='function'||fn.__tpfGuarded)continue;const safe=guard(name,fn);Object.assign(safe,fn);Object.defineProperty(safe,'__tpfGuarded',{value:true});window[key]=safe;wrapped.push(key)}return wrapped}
const api={version:2,register,guard,wrapGlobals,report,emit,status:()=>[...states.values()],errors:()=>[...errs],clearErrors:()=>{errs.length=0}};window.TPFModules=api;emit('runtime','ready');
(function(){const Native=window.MutationObserver;if(!Native||Native.__tpfSafe)return;function SafeMutationObserver(callback){let automationTarget=false,queued=false,pending=[],proxy=null;const native=new Native(records=>{if(!automationTarget){callback(records,proxy);return}pending.push(...records);if(queued)return;queued=true;setTimeout(()=>{queued=false;const batch=pending.splice(0,300);try{callback(batch,proxy)}catch(e){report('mutation-observer',e,'automations')}},60)});proxy={observe(target,options){try{automationTarget=!!(target&&(target.id==='view-automations'||target.closest?.('#view-automations')))}catch(_){automationTarget=false}return native.observe(target,options)},disconnect(){pending.length=0;queued=false;return native.disconnect()},takeRecords(){return native.takeRecords()}};return proxy}SafeMutationObserver.__tpfSafe=true;SafeMutationObserver.prototype=Native.prototype;window.MutationObserver=SafeMutationObserver})();
const files=['automations-stability-guard.js','contacts-active-only.js','contact-label-picker.js','contacts-list-ui.js','contacts-list-layout-fix.js','contacts-filter-layout.js','contacts-final-fix.js','contacts-approved-fixes.js','contacts-four-fixes.js','contact-profile.js','contact-bank-native.js','contact-activity-tabs.js','contact-opportunity-actions.js','contact-open-nonblocking.js','contact-actions-bridge.js','automations-auth-guard.js','automations-flow-status.js','dashboard-performance-guard.js','email-m365-lazy.js','whatsapp-read-guard.js','whatsapp-ui-fixes.js','whatsapp-status-throttle.js','whatsapp-performance-max.js','whatsapp-templates-persistence-bridge.js','whatsapp-templates-library-v3.js','whatsapp-template-first-name.js','whatsapp-template-picker-direct.js','whatsapp-schedule-direct-v3.js','search-fallback.js','contacts-lock-final.js','sales-list-ui.js','whatsapp-large-screen.js','sidebar-fixed-safe.js','sidebar-clean-compact.js','whatsapp-five-fixes.js','whatsapp-reply-isolated.js','whatsapp-contact-reuse.js','whatsapp-contact-edit-back.js','labels-modern-ui.js','automations-flow-builder.js','automations-pro-v2.js','automations-pro-v2-fix.js','automations-builder-pro-ui.js','automations-final-polish.js','automations-execution-controls.js','automations-edit-flow-fix.js','contact-automation-consistency.js','offers-pro.js'];for(const file of files){const s=document.createElement('script');s.src='/js/modules/'+file+'?v='+(file==='offers-pro.js'?'20260906-offers-1':file==='contact-open-nonblocking.js'?'20260906-fresh-contact-1':file==='whatsapp-ui-fixes.js'||file==='whatsapp-five-fixes.js'?'20260906-contact-create-stable-1':file==='labels-modern-ui.js'?'20260906-label-editor-1':file==='whatsapp-templates-library-v3.js'?'20260906-search-focus-1':file==='whatsapp-contact-reuse.js'?'20260906-contact-wait-1':file==='automations-final-polish.js'?'20260906-no-flicker-2':file==='contacts-lock-final.js'?'20260906-task-overlay-1':file==='contact-profile.js'?'20260906-profile-cancel-1':file==='contacts-final-fix.js'||file==='sales-list-ui.js'||file==='contact-label-picker.js'||file==='contacts-list-ui.js'||file==='contacts-approved-fixes.js'?'20260906-sales-identity-2':file==='automations-flow-builder.js'||file==='automations-builder-pro-ui.js'||file==='automations-pro-v2.js'||file==='automations-execution-controls.js'?'20260906-single-builder-1':'20260904-03');s.async=false;document.head.appendChild(s)}
})();
