(function(){
'use strict';const M=window.TPFModules;if(!M)return;
function css(){if(document.getElementById('tpfSalesListUi'))return;const s=document.createElement('style');s.id='tpfSalesListUi';s.textContent=`#salesListView{height:100%;min-height:0;overflow:auto}#salesListView .salesListHeader{position:sticky;top:0;z-index:8;background:#f8fafc}#salesListRows .salesListRow{cursor:pointer;position:relative;transition:background .12s ease;min-height:54px!important;padding-top:5px!important;padding-bottom:5px!important;align-items:center!important;padding-right:54px!important}#salesListRows .salesListRow:hover{background:#f8fbff}#salesListRows .salesListTitle{font-weight:750;color:#17263a}#salesListRows .tpfListExpired{border-left:3px solid #d92d20}#salesListRows .tpfListToday{border-left:3px solid #f79009}#salesListRows .tpfListSoon{border-left:3px solid #12b76a}.tpfListMenuBtn{position:absolute!important;right:12px!important;top:50%!important;transform:translateY(-50%)!important;border:0!important;background:transparent!important;font-size:18px!important;line-height:1!important;padding:6px 8px!important;border-radius:7px!important;cursor:pointer!important;margin:0!important}.tpfListMenuBtn:hover{background:#edf3fa!important}.tpfListMenu{position:fixed;z-index:27000;width:215px;padding:6px;background:#fff;border:1px solid #dfe5ec;border-radius:10px;box-shadow:0 14px 38px rgba(20,35,55,.2)}.tpfListMenu button{display:block;width:100%;border:0;background:#fff;text-align:left;padding:9px 10px;border-radius:7px;font-size:12px;font-weight:650;color:#26364a}.tpfListMenu button:hover{background:#f3f6fa}.tpfListMenu .danger{color:#b42318;border-top:1px solid #edf0f4;margin-top:4px}`;document.head.appendChild(s)}
function opp(id){try{return(salesCache?.opportunities||[]).find(o=>String(o.id)===String(id))}catch(_){return null}}
function open(id){try{return (0,eval)(`openOpportunityCard(${JSON.stringify(String(id))})`)}catch(e){console.error('sales-list native open',e);return false}}
function close(){document.querySelectorAll('.tpfListMenu').forEach(x=>x.remove())}
function wa(o,schedule){const p=String(o?.phone||'').trim();if(!p)return alert('Esta oportunidad no tiene teléfono.');if(typeof openWaQuick==='function'){openWaQuick({phone:p,name:String(o?.client_name||''),message:''});if(schedule)setTimeout(()=>document.getElementById('waScheduleBtn')?.click(),20);return}if(document.getElementById('waQuickPhone'))document.getElementById('waQuickPhone').value=p;document.getElementById('waQuickModal')?.classList.remove('hidden');if(schedule)document.getElementById('waQuickSend')?.click()}
function menu(ev,id){ev.preventDefault();ev.stopPropagation();close();const o=opp(id),m=document.createElement('div');m.className='tpfListMenu';const add=(t,f,c='')=>{const b=document.createElement('button');b.textContent=t;b.className=c;b.onclick=e=>{e.preventDefault();e.stopPropagation();close();f()};m.appendChild(b)};add('Ver / Editar',()=>open(id));add('Mover de estado',()=>document.querySelector(`#salesListRows .salesListCheck[data-opp-id="${CSS.escape(String(id))}"]`)?.closest('.salesListRow')?.querySelector('select')?.focus());add('Crear tarea',()=>window.createAgendaFromRecord?.(JSON.stringify({id:'',name:o?.client_name||'',phone:o?.phone||''})));add('WhatsApp',()=>wa(o,false));add('Programar WhatsApp',()=>wa(o,true));add('Eliminar',()=>window.deleteOpp?.(id),'danger');document.body.appendChild(m);const r=ev.currentTarget.getBoundingClientRect();m.style.left=Math.max(8,Math.min(innerWidth-223,r.right-215))+'px';m.style.top=Math.max(8,Math.min(innerHeight-m.offsetHeight-8,r.bottom+4))+'px'}
function decorate(){document.querySelectorAll('#salesListRows .salesListRow').forEach(row=>{const cb=row.querySelector('.salesListCheck'),id=cb?.dataset.oppId;if(!id)return;row.dataset.oppId=id;row.onclick=e=>{if(e.target.closest('input,select,button,a,.tpfListMenu'))return;e.preventDefault();e.stopPropagation();open(id)};const title=row.querySelector('.salesListTitle');if(title){title.style.cursor='pointer';title.onclick=e=>{e.preventDefault();e.stopPropagation();open(id)}}const o=opp(id),raw=String(o?.expected_date||'');if(raw){const x=new Date(raw+'T00:00:00'),n=new Date();n.setHours(0,0,0,0);const diff=Math.round((x-n)/86400000);row.classList.toggle('tpfListExpired',diff<0);row.classList.toggle('tpfListToday',diff===0);row.classList.toggle('tpfListSoon',diff>0&&diff<=7)}let b=row.querySelector('.tpfListMenuBtn');if(!b){b=document.createElement('button');b.type='button';b.className='tpfListMenuBtn';b.textContent='•••';b.title='Acciones';row.appendChild(b)}b.onclick=e=>menu(e,id)})}
M.register('sales-list-ui',{install(){css();decorate();const r=document.getElementById('salesListRows');if(r)new MutationObserver(()=>requestAnimationFrame(decorate)).observe(r,{childList:true,subtree:true});document.addEventListener('click',e=>{if(!e.target.closest('.tpfListMenu,.tpfListMenuBtn'))close()})}});
})();