(function(){
'use strict';const M=window.TPFModules;if(!M)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const GENERAL=[['app','Aplicación / Vercel'],['supabase','Supabase / sesión'],['green','GREEN-API / WhatsApp'],['frontend','Frontend / JavaScript'],['http','HTTP / API'],['ci','GitHub CI'],['e2e','Playwright / Chrome'],['auth','Autenticación / permisos'],['conflicts','Conflictos / handlers'],['integrity','Regresiones / integridad de datos']];
const MODULES=['whatsapp','agenda','contacts-sales','automations-settings','system-status','contact-profile','contact-activity','contact-opportunities','contact-navigation','contact-edit','automations-auth','whatsapp-read','search','automations-flow','runtime-guard'];
const MODULE_ALIASES={'contact-navigation':['contact-open','contact-actions'],'automations-auth':['auth-guard'],'runtime-guard':['runtime']};
// El historial técnico del navegador no es una alerta activa. Conservamos en
// esta vista solo errores recientes: los resueltos se guardan aparte en el
// registro central y no deben mantener un indicador rojo indefinidamente.
const RECENT_BROWSER_ERROR_MS=15*60*1000;
function nonBlockingGoogleConflict(item){const type=String(item?.type||'').toLowerCase(),text=`${String(item?.message||'')} ${String(item?.detail||'')}`.toLowerCase();return type.includes('409')&&text.includes('/api/google-contacts?action=proxy')}
function errors(){try{const rows=JSON.parse(localStorage.getItem('tpf_system_errors_v1')||'[]');const now=Date.now();const fresh=(Array.isArray(rows)?rows:[]).filter(row=>{if(nonBlockingGoogleConflict(row))return false;const at=new Date(row?.at||row?.created_at||0).getTime();return !Number.isFinite(at)||now-at<=RECENT_BROWSER_ERROR_MS});if(fresh.length!==(Array.isArray(rows)?rows.length:0))localStorage.setItem('tpf_system_errors_v1',JSON.stringify(fresh));return fresh}catch(_){return[]}}
function conflicts(){try{return typeof M.conflicts==='function'?M.conflicts()||[]:[]}catch(_){return[]}}
function external(){try{return JSON.parse(localStorage.getItem('tpf_external_checks_v1')||'{}')}catch(_){return{}}}
function saveExternal(x){try{localStorage.setItem('tpf_external_checks_v1',JSON.stringify(x||{}))}catch(_){}}
let externalSync=null,externalPoll=0;
function pollExternal(){clearTimeout(externalPoll);if(document.hidden)return;const checking=['ci','e2e'].some(id=>externalState(id)==='pending');if(checking)externalPoll=setTimeout(()=>{if(!document.hidden)syncExternal();},15000);}
function currentCommit(){try{return String(document.getElementById('tpfBuildBadge')?.dataset?.tpfFullCommit||document.getElementById('tpfBuildBadge')?.dataset?.tpfCommit||'').trim().toLowerCase()}catch(_){return''}}
function sameCommit(current,saved){return !!(current&&saved&&(saved.startsWith(current)||current.startsWith(saved)))}
function isCurrentExternal(item){if(!item)return false;const host=String(item.host||'');if(host!==location.host)return false;const current=currentCommit(),saved=String(item.sha||'').trim().toLowerCase();if(current&&saved&&!sameCommit(current,saved))return false;return true}
function externalState(id){const item=external()[id];if(!isCurrentExternal(item))return'info';return item.state||'info'}
function moduleState(name){try{const rows=M.status()||[];const names=[name,...(MODULE_ALIASES[name]||[])];const found=rows.filter(v=>names.includes(v.name));if(!found.length)return'pending';return found.some(x=>['error','bad'].includes(x.state))?'bad':found.some(x=>['ready','ok'].includes(x.state))?'ok':'pending'}catch(_){return'pending'}}
function generalState(id){const txt=(document.getElementById({app:'systemAppText',supabase:'systemSupabaseText',green:'systemGreenText',frontend:'systemFrontText'}[id])?.textContent||'').toLowerCase();if(id==='frontend'){const recent=errors().filter(x=>{const t=new Date(x?.at||0).getTime();return Number.isFinite(t)&&Date.now()-t<3600000});return recent.length?'bad':txt?'ok':'pending'}if(['app','supabase','green'].includes(id))return /fallo|error|degrad|sin conexión|unauthorized/.test(txt)?'bad':txt?'ok':'pending';if(id==='conflicts')return conflicts().length?'bad':'ok';if(id==='http')return errors().some(e=>/http|4\d\d|5\d\d/i.test(e.message||e.detail||''))?'bad':'ok';if(id==='auth')return errors().some(e=>/auth|login|password|permiso|401|403/i.test(e.message||e.detail||''))?'bad':'ok';if(id==='integrity')return errors().some(e=>/guardar|persist|regresi|integridad|duplic/i.test(e.message||e.detail||''))?'bad':'ok';if(id==='ci'||id==='e2e')return externalState(id);return'pending'}
function dot(s){return s==='ok'?'🟢':s==='bad'?'🔴':s==='info'?'🔵':'🟡'}function label(s){return s==='ok'?'Correcto':s==='bad'?'Error detectado':s==='info'?'Información':'Comprobando'}
function externalDetail(id){const item=external()[id];if(!item)return'Sin prueba automática para este cambio; no es un error';if(String(item.host||'')!==location.host)return'Resultado de otro deployment ignorado';const current=currentCommit(),saved=String(item.sha||'').trim().toLowerCase();if(current&&saved&&!sameCommit(current,saved))return'Resultado de otro commit ignorado';if(item.state==='bad')return item.detail||'La prueba externa ha fallado y requiere revisión';return item.detail||'Sin prueba automática para este cambio; no es un error'}
function ensure(){const host=document.getElementById('view-system');if(!host||document.getElementById('tpf25Checks'))return;const card=document.createElement('div');card.id='tpfModuleStatusCard';card.className='card';card.innerHTML='<div id="tpf25Checks"><div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap"><div><h3 style="margin:0">25 comprobadores del CRM</h3><div class="small">Comprobaciones técnicas de esta sesión y pruebas de esta versión. Las incidencias centrales se consultan en su propio apartado.</div></div><b id="tpf25Summary"></b></div><div id="tpf25General" style="margin-top:14px"></div><h4>15 módulos independientes</h4><div id="tpf25Modules"></div><div id="tpf25Problems" style="margin-top:14px"></div></div>';host.querySelector('.systemStatusCard')?.after(card)}
function row(name,state,detail=''){return `<div style="display:flex;gap:9px;padding:8px 0;border-bottom:1px solid #edf0f3"><span>${dot(state)}</span><div><b>${esc(name)}</b><div class="small">${label(state)}${detail?' · '+esc(detail):''}</div></div></div>`}
function render(){ensure();const gs=GENERAL.map(([id,n])=>({id,n,s:generalState(id)}));const ms=MODULES.map(n=>({n,s:moduleState(n)}));const all=[...gs,...ms];const ok=all.filter(x=>x.s==='ok').length,bad=all.filter(x=>x.s==='bad').length,pending=all.filter(x=>x.s==='pending').length,info=all.filter(x=>x.s==='info').length;document.getElementById('tpf25Summary').textContent=`${ok}/25 correctos · ${bad} controles con error${pending?` · ${pending} comprobando`:''}${info?` · ${info} informativos`:''}`;document.getElementById('tpf25General').innerHTML='<h4>10 comprobadores generales</h4>'+gs.map(x=>row(x.n,x.s,x.id==='ci'||x.id==='e2e'?externalDetail(x.id):'')).join('');document.getElementById('tpf25Modules').innerHTML=ms.map(x=>row(x.n,x.s)).join('');const probs=[...errors().slice(0,30).map(e=>({src:e.source||e.module||'Sistema',msg:e.message||e.detail||e.error||'Error',at:e.at||e.created_at})),...conflicts().slice(0,20).map(c=>({src:'Conflicto '+(c.control||''),msg:`${c.owner||''} / ${c.module||''}`,at:c.at}))];document.getElementById('tpf25Problems').innerHTML='<h4>Errores recientes de este navegador</h4>'+(probs.length?probs.map(p=>`<div style="padding:8px 0;border-bottom:1px solid #edf0f3"><b>🔴 ${esc(p.src)}</b><div class="small">${esc(p.msg)}${p.at?' · '+esc(new Date(p.at).toLocaleString('es-ES')):''}</div></div>`).join(''):'<div class="small">No hay errores recientes registrados en este navegador.</div>')}
async function syncExternal(){
 if(externalSync)return externalSync;
 externalSync=(async()=>{
  let sha=currentCommit();
  const saveInfo=detail=>{const out=external();for(const id of ['ci','e2e'])out[id]={state:'info',detail,sha,host:location.host,at:new Date().toISOString()};saveExternal(out);render();};
  try{
   // The page already identifies its exact deployment. Do not launch a second
   // page request on focus just to discover its SHA.
   if(!/^[a-f0-9]{40}$/.test(sha)){saveInfo('Recarga el CRM para consultar las pruebas de esta versión.');return;}
   const r=await fetch(`https://api.github.com/repos/jramon07-lab/the_phone_face/actions/runs?head_sha=${encodeURIComponent(sha)}&per_page=20`,{headers:{Accept:'application/vnd.github+json'},cache:'no-store',signal:AbortSignal.timeout(8000)});
   if(!r.ok){saveInfo('No se pudo consultar GitHub para esta versión. Pulsa Actualizar para reintentar.');return;}
   const d=await r.json(),runs=(d.workflow_runs||[]).filter(x=>String(x.head_sha||'').toLowerCase()===sha.toLowerCase());
   const state=x=>!x?'info':x.status!=='completed'?'pending':x.conclusion==='success'?'ok':['failure','timed_out','action_required'].includes(x.conclusion)?'bad':'info';
   const out=external();
   for(const [id,names] of [['ci',['CRM modules check','CRM Modular CI']],['e2e',['CRM Browser Validation']]]){
    const run=runs.filter(x=>names.includes(x.name)).sort((a,b)=>Number(b.run_number||0)-Number(a.run_number||0)||Number(b.run_attempt||0)-Number(a.run_attempt||0))[0];
    out[id]={state:state(run),detail:run?.conclusion||run?.status||'Sin prueba automática para este cambio; no es un error',sha,host:location.host,at:new Date().toISOString()};
   }
   saveExternal(out);render();
  }catch(e){saveInfo('No se pudo consultar la prueba externa. Pulsa Actualizar para reintentar.');console.warn('Sincronización controles externos',e);}
  finally{externalSync=null;pollExternal();}
 })();return externalSync;
}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncExternal();else clearTimeout(externalPoll);});
window.tpfSetExternalCheck=function(id,state,detail){if(!['ci','e2e'].includes(id))return;const x=external();x[id]={state:state==='ok'?'ok':state==='bad'?'bad':'pending',detail:String(detail||''),sha:currentCommit(),host:location.host,at:new Date().toISOString()};saveExternal(x);render()};
M.register('system-status',{install(){M.wrapGlobals('system-status',['loadSystemStatus']);const old=external();let changed=false;for(const id of ['ci','e2e']){if(old[id]&&String(old[id].host||'')!==location.host){delete old[id];changed=true}}if(changed)saveExternal(old);window.addEventListener('tpf:module-status',()=>setTimeout(render,0));window.addEventListener('tpf:ownership-conflict',()=>setTimeout(render,0));window.addEventListener('error',()=>setTimeout(render,0));window.addEventListener('unhandledrejection',()=>setTimeout(render,0));document.addEventListener('click',e=>{if(e.target?.closest?.('.nav[data-view="system"]')||e.target?.id==='systemRefresh'||e.target?.id==='systemClearErrors'){setTimeout(render,150);setTimeout(syncExternal,250)}});setTimeout(render,0);setTimeout(syncExternal,500)}});
})();
