(function(){
'use strict';const M=window.TPFModules;if(!M)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const GENERAL=[['app','Aplicación / Vercel'],['supabase','Supabase / sesión'],['green','GREEN-API / WhatsApp'],['frontend','Frontend / JavaScript'],['http','HTTP / API'],['ci','GitHub CI'],['e2e','Playwright / Chrome'],['auth','Autenticación / permisos'],['conflicts','Conflictos / handlers'],['integrity','Regresiones / integridad de datos']];
const MODULES=['whatsapp','agenda','contacts-sales','automations-settings','system-status','contact-profile','contact-activity','contact-opportunities','contact-navigation','contact-edit','automations-auth','whatsapp-read','search','automations-flow','runtime-guard'];
function errors(){try{return JSON.parse(localStorage.getItem('tpf_system_errors_v1')||'[]')}catch(_){return[]}}
function conflicts(){try{return typeof M.conflicts==='function'?M.conflicts()||[]:[]}catch(_){return[]}}
function moduleState(name){try{const x=(M.status()||[]).find(v=>v.name===name);return x?(['ready','ok'].includes(x.state)?'ok':'bad'):'pending'}catch(_){return'pending'}}
function generalState(id){const txt=(document.getElementById({app:'systemAppText',supabase:'systemSupabaseText',green:'systemGreenText',frontend:'systemFrontText'}[id])?.textContent||'').toLowerCase();if(['app','supabase','green','frontend'].includes(id))return /fallo|error|degrad|no |sin conexión|unauthorized/.test(txt)?'bad':txt?'ok':'pending';if(id==='conflicts')return conflicts().length?'bad':'ok';if(id==='http')return errors().some(e=>/http|4\d\d|5\d\d/i.test(e.message||e.detail||''))?'bad':'ok';if(id==='auth')return errors().some(e=>/auth|login|password|permiso|401|403/i.test(e.message||e.detail||''))?'bad':'ok';if(id==='integrity')return errors().some(e=>/guardar|persist|regresi|integridad|duplic/i.test(e.message||e.detail||''))?'bad':'ok';if(id==='ci'||id==='e2e'){try{const x=JSON.parse(localStorage.getItem('tpf_external_checks_v1')||'{}')[id];return x?.state||'pending'}catch(_){return'pending'}}return'pending'}
function dot(s){return s==='ok'?'🟢':s==='bad'?'🔴':'🟡'}function label(s){return s==='ok'?'Correcto':s==='bad'?'Error detectado':'Pendiente de sincronizar'}
function ensure(){const host=document.getElementById('view-system');if(!host||document.getElementById('tpf25Checks'))return;const card=document.createElement('div');card.id='tpf25Checks';card.className='card';card.innerHTML='<div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap"><div><h3 style="margin:0">25 comprobadores del CRM</h3><div class="small">Todos los controles visibles en un único sitio. Los externos muestran pendiente hasta recibir su resultado.</div></div><b id="tpf25Summary"></b></div><div id="tpf25General" style="margin-top:14px"></div><h4>15 módulos independientes</h4><div id="tpf25Modules"></div><div id="tpf25Problems" style="margin-top:14px"></div>';host.prepend(card)}
function row(name,state,detail=''){return `<div style="display:flex;gap:9px;padding:8px 0;border-bottom:1px solid #edf0f3"><span>${dot(state)}</span><div><b>${esc(name)}</b><div class="small">${label(state)}${detail?' · '+esc(detail):''}</div></div></div>`}
function render(){ensure();const gs=GENERAL.map(([id,n])=>({id,n,s:generalState(id)}));const ms=MODULES.map(n=>({n,s:moduleState(n)}));const all=[...gs,...ms];const ok=all.filter(x=>x.s==='ok').length,bad=all.filter(x=>x.s==='bad').length,pending=all.filter(x=>x.s==='pending').length;document.getElementById('tpf25Summary').textContent=`${ok}/25 correctos · ${bad} errores · ${pending} pendientes`;document.getElementById('tpf25General').innerHTML='<h4>10 comprobadores generales</h4>'+gs.map(x=>row(x.n,x.s,x.id==='ci'||x.id==='e2e'?'Resultado externo GitHub/Playwright':'')).join('');document.getElementById('tpf25Modules').innerHTML=ms.map(x=>row(x.n,x.s)).join('');const probs=[...errors().slice(0,30).map(e=>({src:e.source||e.module||'Sistema',msg:e.message||e.detail||e.error||'Error',at:e.at||e.created_at})),...conflicts().slice(0,20).map(c=>({src:'Conflicto '+(c.control||''),msg:`${c.owner||''} / ${c.module||''}`,at:c.at}))];document.getElementById('tpf25Problems').innerHTML='<h4>Todos los errores conocidos</h4>'+(probs.length?probs.map(p=>`<div style="padding:8px 0;border-bottom:1px solid #edf0f3"><b>🔴 ${esc(p.src)}</b><div class="small">${esc(p.msg)}${p.at?' · '+esc(new Date(p.at).toLocaleString('es-ES')):''}</div></div>`).join(''):'<div class="small">No hay errores registrados en el CRM.</div>')}
window.tpfSetExternalCheck=function(id,state,detail){if(!['ci','e2e'].includes(id))return;let x={};try{x=JSON.parse(localStorage.getItem('tpf_external_checks_v1')||'{}')}catch(_){}x[id]={state:state==='ok'?'ok':state==='bad'?'bad':'pending',detail:String(detail||''),at:new Date().toISOString()};localStorage.setItem('tpf_external_checks_v1',JSON.stringify(x));render()};
M.register('system-status',{install(){M.wrapGlobals('system-status',['loadSystemStatus']);window.addEventListener('tpf:module-status',()=>setTimeout(render,0));window.addEventListener('tpf:ownership-conflict',()=>setTimeout(render,0));window.addEventListener('error',()=>setTimeout(render,0));window.addEventListener('unhandledrejection',()=>setTimeout(render,0));document.addEventListener('click',e=>{if(e.target?.closest?.('.nav[data-view="system"]')||e.target?.id==='systemRefresh')setTimeout(render,100)});setTimeout(render,0)}});
})();
