const crypto=require('crypto');
const zlib=require('zlib');

const SB_URL=String(process.env.SUPABASE_URL||'https://overfzbjtpjqxzbujezg.supabase.co').replace(/\/$/,'');
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const CLIENT_ID=process.env.GOOGLE_DRIVE_CLIENT_ID||'';
const CLIENT_SECRET=process.env.GOOGLE_DRIVE_CLIENT_SECRET||'';
const BACKUP_KEY=process.env.CRM_BACKUP_ENCRYPTION_KEY||'';
const CRON_SECRET=process.env.CRON_SECRET||'';
const B=require('../lib/crm-backup-core');
const TABLES=B.TABLES;
const json=(res,status,body)=>{res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.status(status).json(body)};
const configured=()=>!!(SERVICE_KEY&&CLIENT_ID&&CLIENT_SECRET&&BACKUP_KEY);
const sbHeaders=(extra={})=>({apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',...extra});
function seal(value){const key=crypto.createHash('sha256').update(BACKUP_KEY).digest(),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64')}
function open(value){const raw=Buffer.from(value,'base64'),key=crypto.createHash('sha256').update(BACKUP_KEY).digest(),dec=crypto.createDecipheriv('aes-256-gcm',key,raw.subarray(0,12));dec.setAuthTag(raw.subarray(12,28));return Buffer.concat([dec.update(raw.subarray(28)),dec.final()]).toString('utf8')}
function stateToken(userId){const payload=Buffer.from(JSON.stringify({userId,exp:Date.now()+10*60e3})).toString('base64url'),sig=crypto.createHmac('sha256',BACKUP_KEY).update(payload).digest('base64url');return `${payload}.${sig}`}
function verifyState(value){const [payload,sig]=String(value||'').split('.'),good=crypto.createHmac('sha256',BACKUP_KEY).update(payload||'').digest('base64url');if(!sig||Buffer.byteLength(sig)!==Buffer.byteLength(good)||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(good)))throw new Error('Autorización no válida');const data=JSON.parse(Buffer.from(payload,'base64url'));if(data.exp<Date.now())throw new Error('Autorización caducada');return data}
async function admin(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const r=await fetch(`${SB_URL}/rest/v1/rpc/current_user_permissions`,{method:'POST',headers:{apikey:process.env.SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_ANON_KEY||'',Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:'{}'});if(!r.ok)return null;const p=await r.json();if(!p?.is_admin)return null;const part=token.split('.')[1];try{return {id:JSON.parse(Buffer.from(part,'base64url')).sub}}catch(_){return null}}
async function credential(){const r=await fetch(`${SB_URL}/rest/v1/crm_external_credentials?provider=eq.google_drive&select=encrypted_value`,{headers:sbHeaders()});if(!r.ok)return'';const rows=await r.json();return rows[0]?.encrypted_value?open(rows[0].encrypted_value):''}
async function saveCredential(refreshToken,userId){const r=await fetch(`${SB_URL}/rest/v1/crm_external_credentials?on_conflict=provider`,{method:'POST',headers:sbHeaders({Prefer:'resolution=merge-duplicates'}),body:JSON.stringify({provider:'google_drive',encrypted_value:seal(refreshToken),updated_by:userId,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('No se pudo guardar la autorización de Drive')}
async function accessToken(){const refresh_token=await credential();if(!refresh_token)throw new Error('Google Drive no está conectado');const body=new URLSearchParams({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,refresh_token,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.error_description||'Google no renovó el acceso');return d.access_token}
const PRIMARY_KEYS={app_settings:['key'],crm_external_credentials:['provider'],user_permissions:['user_id'],user_google_settings:['user_id'],crm_contact_labels:['contact_id','label_id'],sales_custom_values:['opportunity_id','field_id'],user_field_permissions:['user_id','section','field_key'],crm_welcome_requests:['contact_id']};
async function rows(table){const out=[],size=500,order=(PRIMARY_KEYS[table]||['id']).map(k=>k+'.asc').join(',');for(let from=0;;from+=size){const r=await fetch(`${SB_URL}/rest/v1/${table}?select=*&order=${order}&offset=${from}&limit=${size}`,{headers:sbHeaders()});if(!r.ok)throw Error(`${table}: HTTP ${r.status}`);const part=await r.json();if(!Array.isArray(part))throw Error('Respuesta no válida: '+table);out.push(...part);if(part.length<size)break;}return out;}
async function driveUpload(token,name,content){const metadata={name,mimeType:'application/octet-stream'};if(process.env.GOOGLE_DRIVE_FOLDER_ID)metadata.parents=[process.env.GOOGLE_DRIVE_FOLDER_ID];const boundary=`tpf-${crypto.randomUUID()}`,body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/octet-stream\r\n\r\n`),content,Buffer.from(`\r\n--${boundary}--`)]);const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,size,md5Checksum',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'No se pudo subir la copia a Drive');return d}
async function history(limit=30){const r=await fetch(`${SB_URL}/rest/v1/crm_backup_runs?select=id,started_at,completed_at,status,file_name,bytes,record_counts,verified_at,error_message&order=started_at.desc&limit=${limit}`,{headers:sbHeaders()});if(!r.ok)throw Error('No se pudo consultar el historial de copias');return r.json();}
async function runBackup(){
 const started=new Date().toISOString();
 const run=await fetch(`${SB_URL}/rest/v1/crm_backup_runs`,{method:'POST',headers:sbHeaders({Prefer:'return=representation'}),body:JSON.stringify({status:'running',started_at:started})});
 if(!run.ok)throw Error('No se pudo iniciar el registro de copia');const runId=(await run.json())[0].id;
 const finish=async value=>{const r=await fetch(`${SB_URL}/rest/v1/crm_backup_runs?id=eq.${runId}`,{method:'PATCH',headers:sbHeaders(),body:JSON.stringify(value)});if(!r.ok)throw Error('No se pudo registrar el resultado de la copia');};
 try{
  const data={},counts={};for(const table of TABLES){data[table]=await rows(table);counts[table]=data[table].length;}
  const document={format:'the-phone-face-backup-v2',created_at:started,coverage:B.COVERAGE,counts,data};
  const encrypted=B.encode(document,BACKUP_KEY),checksum=B.checksum(encrypted),name=`the-phone-face-${started.replace(/[:.]/g,'-')}.tpfbak`;
  const token=await accessToken(),file=await driveUpload(token,name,encrypted);
  if(!file.id)throw Error('Drive no confirmó el identificador de la copia');
  const download=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}?alt=media`,{headers:{Authorization:`Bearer ${token}`}});
  if(!download.ok)throw Error('No se pudo descargar la copia para verificarla');
  B.verify(Buffer.from(await download.arrayBuffer()),checksum,BACKUP_KEY);
  await finish({status:'verified',completed_at:new Date().toISOString(),verified_at:new Date().toISOString(),file_id:file.id,file_name:name,bytes:encrypted.length,record_counts:counts,checksum});
  return {ok:true,file:name,bytes:encrypted.length,counts,verification:'download-decrypt-counts',coverage:B.COVERAGE};
 }catch(error){try{await finish({status:'failed',completed_at:new Date().toISOString(),error_message:String(error.message||error).slice(0,500)})}catch(logError){console.error(logError.message)}throw error;}
}
module.exports=async function(req,res){const action=String(req.query?.action||'status');if(!configured())return json(res,action==='status'?200:503,{ok:action==='status',configured:false,connected:false,message:'Pendiente de configurar credenciales privadas'});try{
  if(action==='callback'){const state=verifyState(req.query?.state),body=new URLSearchParams({code:String(req.query?.code||''),client_id:CLIENT_ID,client_secret:CLIENT_SECRET,redirect_uri:`https://${req.headers.host}/api/crm-backup?action=callback`,grant_type:'authorization_code'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}),d=await r.json();if(!r.ok||!d.refresh_token)throw new Error(d.error_description||'Google no entregó permiso permanente');await saveCredential(d.refresh_token,state.userId);res.status(302).setHeader('Location','/?drive=connected#system');return res.end()}
  if(action==='cron'){if(!CRON_SECRET||req.headers.authorization!==`Bearer ${CRON_SECRET}`)return json(res,401,{ok:false,error:'No autorizado'});const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));if(parts.hour!=='03')return json(res,200,{ok:true,skipped:true,reason:'Fuera de la ventana 03:30 Europe/Madrid'});if(!B.due(new Date(),await history(5)))return json(res,200,{ok:true,skipped:true,reason:'Ya existe una copia verificada hoy'});return json(res,200,await runBackup())}
  const who=await admin(req);if(!who)return json(res,403,{ok:false,error:'Solo el administrador puede gestionar las copias'});
  if(action==='authorize'){const redirect=`https://${req.headers.host}/api/crm-backup?action=callback`,url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:CLIENT_ID,redirect_uri:redirect,response_type:'code',scope:'https://www.googleapis.com/auth/drive.file',access_type:'offline',prompt:'consent',state:stateToken(who.id)});return json(res,200,{ok:true,url:String(url)})}
  if(action==='run'){if(req.method!=='POST')return json(res,405,{ok:false,error:'Utiliza POST para crear una copia'});return json(res,200,await runBackup())}
  const connected=!!(await credential()),runs=await history();const lastVerified=runs.find(x=>x.status==='verified');const age=lastVerified?Date.now()-new Date(lastVerified.completed_at||lastVerified.started_at).getTime():Infinity;
  return json(res,200,{ok:true,configured:true,connected,history:runs,stale:age>36*60*60*1000,coverage:B.COVERAGE,verification:'download-decrypt-counts'});
}catch(error){return json(res,500,{ok:false,error:String(error.message||error)})}}
