const crypto=require('crypto');
const zlib=require('zlib');

const SB_URL=String(process.env.SUPABASE_URL||'https://overfzbjtpjqxzbujezg.supabase.co').replace(/\/$/,'');
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const CLIENT_ID=process.env.GOOGLE_DRIVE_CLIENT_ID||'';
const CLIENT_SECRET=process.env.GOOGLE_DRIVE_CLIENT_SECRET||'';
const BACKUP_KEY=process.env.CRM_BACKUP_ENCRYPTION_KEY||'';
const CRON_SECRET=process.env.CRON_SECRET||'';
const TABLES=['records','sales_opportunities','sales_stages','agenda_items','whatsapp_jobs','crm_automations','crm_server_automation_jobs','crm_labels','crm_contact_labels','app_settings','user_permissions','crm_custom_fields'];
const json=(res,status,body)=>{res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.status(status).json(body)};
const configured=()=>!!(SERVICE_KEY&&CLIENT_ID&&CLIENT_SECRET&&BACKUP_KEY);
const sbHeaders=(extra={})=>({apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',...extra});
function seal(value){const key=crypto.createHash('sha256').update(BACKUP_KEY).digest(),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64')}
function open(value){const raw=Buffer.from(value,'base64'),key=crypto.createHash('sha256').update(BACKUP_KEY).digest(),dec=crypto.createDecipheriv('aes-256-gcm',key,raw.subarray(0,12));dec.setAuthTag(raw.subarray(12,28));return Buffer.concat([dec.update(raw.subarray(28)),dec.final()]).toString('utf8')}
function stateToken(userId){const payload=Buffer.from(JSON.stringify({userId,exp:Date.now()+10*60e3})).toString('base64url'),sig=crypto.createHmac('sha256',BACKUP_KEY).update(payload).digest('base64url');return `${payload}.${sig}`}
function verifyState(value){const [payload,sig]=String(value||'').split('.'),good=crypto.createHmac('sha256',BACKUP_KEY).update(payload||'').digest('base64url');if(!sig||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(good)))throw new Error('Autorización no válida');const data=JSON.parse(Buffer.from(payload,'base64url'));if(data.exp<Date.now())throw new Error('Autorización caducada');return data}
async function admin(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const r=await fetch(`${SB_URL}/rest/v1/rpc/current_user_permissions`,{method:'POST',headers:{apikey:process.env.SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_ANON_KEY||'',Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:'{}'});if(!r.ok)return null;const p=await r.json();if(!p?.is_admin)return null;const part=token.split('.')[1];try{return {id:JSON.parse(Buffer.from(part,'base64url')).sub}}catch(_){return null}}
async function credential(){const r=await fetch(`${SB_URL}/rest/v1/crm_external_credentials?provider=eq.google_drive&select=encrypted_value`,{headers:sbHeaders()});if(!r.ok)return'';const rows=await r.json();return rows[0]?.encrypted_value?open(rows[0].encrypted_value):''}
async function saveCredential(refreshToken,userId){const r=await fetch(`${SB_URL}/rest/v1/crm_external_credentials?on_conflict=provider`,{method:'POST',headers:sbHeaders({Prefer:'resolution=merge-duplicates'}),body:JSON.stringify({provider:'google_drive',encrypted_value:seal(refreshToken),updated_by:userId,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('No se pudo guardar la autorización de Drive')}
async function accessToken(){const refresh_token=await credential();if(!refresh_token)throw new Error('Google Drive no está conectado');const body=new URLSearchParams({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,refresh_token,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.error_description||'Google no renovó el acceso');return d.access_token}
async function rows(table){const out=[],size=1000;for(let from=0;;from+=size){const r=await fetch(`${SB_URL}/rest/v1/${table}?select=*&offset=${from}&limit=${size}`,{headers:sbHeaders()});if(r.status===404)return[];if(!r.ok)throw new Error(`${table}: HTTP ${r.status}`);const part=await r.json();out.push(...part);if(part.length<size)break}return out}
async function driveUpload(token,name,content){const metadata={name,mimeType:'application/octet-stream'};if(process.env.GOOGLE_DRIVE_FOLDER_ID)metadata.parents=[process.env.GOOGLE_DRIVE_FOLDER_ID];const boundary=`tpf-${crypto.randomUUID()}`,body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/octet-stream\r\n\r\n`),content,Buffer.from(`\r\n--${boundary}--`)]);const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,size,md5Checksum',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'No se pudo subir la copia a Drive');return d}
async function runBackup(){const started=new Date().toISOString(),run=await fetch(`${SB_URL}/rest/v1/crm_backup_runs`,{method:'POST',headers:sbHeaders({Prefer:'return=representation'}),body:JSON.stringify({status:'running',started_at:started})});if(!run.ok)throw new Error('No se pudo iniciar el registro de copia');const runId=(await run.json())[0].id;try{const entries={},counts={};for(const table of TABLES){entries[table]=await rows(table);counts[table]=entries[table].length}const plain=Buffer.from(JSON.stringify({format:'the-phone-face-backup-v1',created_at:new Date().toISOString(),counts,data:entries})),gz=zlib.gzipSync(plain,{level:9}),iv=crypto.randomBytes(12),key=crypto.createHash('sha256').update(BACKUP_KEY).digest(),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),encrypted=Buffer.concat([Buffer.from('TPFB1'),iv,cipher.update(gz),cipher.final(),cipher.getAuthTag()]),checksum=crypto.createHash('sha256').update(encrypted).digest('hex'),name=`the-phone-face-${new Date().toISOString().replace(/[:.]/g,'-')}.tpfbak`,token=await accessToken(),file=await driveUpload(token,name,encrypted);if(crypto.createHash('sha256').update(encrypted).digest('hex')!==checksum)throw new Error('La verificación local de la copia no coincide');await fetch(`${SB_URL}/rest/v1/crm_backup_runs?id=eq.${runId}`,{method:'PATCH',headers:sbHeaders(),body:JSON.stringify({status:'verified',completed_at:new Date().toISOString(),verified_at:new Date().toISOString(),file_id:file.id,file_name:name,bytes:encrypted.length,record_counts:counts,checksum})});return {ok:true,file:name,bytes:encrypted.length,counts}}catch(error){await fetch(`${SB_URL}/rest/v1/crm_backup_runs?id=eq.${runId}`,{method:'PATCH',headers:sbHeaders(),body:JSON.stringify({status:'failed',completed_at:new Date().toISOString(),error_message:String(error.message||error).slice(0,500)})});throw error}}
module.exports=async function(req,res){const action=String(req.query?.action||'status');if(!configured())return json(res,200,{ok:true,configured:false,connected:false,message:'Pendiente de configurar credenciales privadas'});try{
  if(action==='callback'){const state=verifyState(req.query?.state),body=new URLSearchParams({code:String(req.query?.code||''),client_id:CLIENT_ID,client_secret:CLIENT_SECRET,redirect_uri:`https://${req.headers.host}/api/crm-backup?action=callback`,grant_type:'authorization_code'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}),d=await r.json();if(!r.ok||!d.refresh_token)throw new Error(d.error_description||'Google no entregó permiso permanente');await saveCredential(d.refresh_token,state.userId);res.status(302).setHeader('Location','/?drive=connected#system');return res.end()}
  if(action==='cron'){if(!CRON_SECRET||req.headers.authorization!==`Bearer ${CRON_SECRET}`)return json(res,401,{ok:false,error:'No autorizado'});const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));if(parts.hour!=='03'||parts.minute!=='30')return json(res,200,{ok:true,skipped:true,reason:'Fuera de la ventana 03:30 Europe/Madrid'});return json(res,200,await runBackup())}
  const who=await admin(req);if(!who)return json(res,403,{ok:false,error:'Solo el administrador puede gestionar las copias'});
  if(action==='authorize'){const redirect=`https://${req.headers.host}/api/crm-backup?action=callback`,url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:CLIENT_ID,redirect_uri:redirect,response_type:'code',scope:'https://www.googleapis.com/auth/drive.file',access_type:'offline',prompt:'consent',state:stateToken(who.id)});return json(res,200,{ok:true,url:String(url)})}
  if(action==='run'){return json(res,200,await runBackup())}
  const connected=!!(await credential()),h=await fetch(`${SB_URL}/rest/v1/crm_backup_runs?select=id,started_at,completed_at,status,file_name,bytes,record_counts,verified_at,error_message&order=started_at.desc&limit=30`,{headers:sbHeaders()}),history=h.ok?await h.json():[];return json(res,200,{ok:true,configured:true,connected,history});
}catch(error){return json(res,500,{ok:false,error:String(error.message||error)})}}
